[#35_0]
== SQUADRON GROUND SUPPORT UNITS

COMMENTARY:

All planes are attached to a specific squadron, and each squadron is represented
by a Squadron Ground Support Unit (SGSU), which is the base for that squadron.
Each squadron has its own Squadron Composition Sheet, and the planes and pilots
— as well as supplies — attached and available to that squadron are listed
on it. The squadron is the basic unit for the Air Game, and finds its
counterpart in the German "Staffel" and Italian "Squadriglia." Actually, the
Squadron was next-to-lowest in air hierarchy (above the Flight); squadrons were
part of wings, which were, in turn, part of groups (and their Axis
counterparts). However, most of this was for purely administrative purposes.
Therefore, the only organizational level CNA covers is the Squadron.

GENERAL RULE:

Squadrons — specifically the SGSU's — are used to maintain and supply the
‘aircraft assigned to them. Each SGSU may contain only one class of airplane,
and it is limited-as to the number of planes it may handle effectively. The SGSU
counters are considered vehicles (medium trucks) and have their own Capability
Point Allowance printed on the counter. They have no combat values.

[#35_1]
=== SGSU CHARACTERISTICS

[#35_11]*[35.11]* An SGSU counter acts as base for all planes assigned to that
squadron. Each SGSU counter is placed on the game-map to indicate where that
squadron is located. They are usually placed at air facilities. SGSU counters do
not include the airplanes attached to the squadron; SGSU's are the mechanics,
trucks, equipment, etc., that are part of that squadron. They are not “air”
units.

[#35_12]*[35.12]* SGSU's have their Capability Point Allowance printed on the
counter; they are vehicles. SGSU's move in the Truck Convoy Phase. They have no
Stacking Point Value and may stack freely with other units. (Their capability to
handle the planes in their squadron is limited by the Capacity Level of the air
facility they are based at.) SGSU's have no combat strength of any type; if an
Enemy combat unit moves adjacent to an SGSU that has no Friendly combat unit
stacked with it, that SGSU may react (if possible). If it cannot react, it is
eliminated.

[#35_13]*[35.13]* SGSU‘s arrive according to the orders of the player (See Case
<<34_8>>. Each SGSU has a unit designation (squadron ID number). These numbers
are historical, but they are not used historically. If an SGSU counter is
eliminated, it may be returned to play, as per <<34_8>>, one GameTurn later.

[#35_14]*[35.14]* SGSU's require a certain amount of supplies themselves to
function. Each SGSU must expend one Stores Point per Game-Turn. In addition,
each SGSU requires one Fuel Point and one Water Point per Operations Stage.
SGSUs without the required supplies (for themselves) may not repair their
planes. (Maintaining the planes will, of course, require additional supplies of
Fuel and Ammunition).

[#35_15]*[35.15]* Truck units may be attached to an SGSU as First Line
Transport. They are used to carry the supplies that the SGSU needs to keep its
planes fit and readied.

[#35_16]*[35.16]* SGSUs may be used to construct air landing facilities or
flying boat alighting areas (see Case <<24_7>>.

[#35_17]*[35.17]* SGSUs are necessary to refuel and refit airplanes; only SGSUs
can perform such tasks.  Aircraft may refuel at any SGSU: their own squadron or
another squadron base. However, refitting must be performed at their assigned
squadron base (SGSU) for maximum efficiency. If a plane attempts to refit at an
SGSU other than its assigned squadron, the Player adds one to his dieroll for
refit. In addition, Players should remember that planes may not be refueled or
refitted beyond the capacity of the air facility (see Case 36.12, 36.2,
<<36_3>>and <<36_4>>.

[#35_18]*[35.18]* The United States Army Air Force (USAF on the counters) SGSU's
may not be used prior to Aug. 1, 1942.

[#35_2]
=== SQUADRON COMPOSITION

[#35_21]*[35.21]* Each Squadron must contain the same class of aircraft: i.e.,
bomber, fighter or transport (recon planes may be assigned anywhere).
Fighterbombers may go into either. Furthermore, it is recommended (but nota
rule) that only one type of plane (e.g., Hurricane IIC or Ju87D, etc.) be
assigned to a squadron. The latter is for ease in handling and supervision. The
composition of each squadron is noted on the squadron's Composition Sheet.

[#35_22]*[35.22]* Planes may not change squadron assignments, with two exceptions:

a. The squadron's SGSU has been eliminated. In such case the aircraft are free
to transfer to any other squadron, or they may be placed in reserve.
b. A squadron falls below 50% ready Capacity.  Planes may then be transferred
from other squadrons to bring that squadron back to a more than 50% capacity.

Planes reassigned to a new squadron are given a transfer mission (to fly to
their new base), unless the new SGSU is in the same hex as the plane.

[#35_23]*[35.23]* The number of planes that may be assigned to a squadron is
limited and dependent on the nationality of the squadron. Each squadron's limit
is the maximum number of ready planes it can handle; a squadron can always keep
4 more in reserve (whether ready or not). Thus, a squadron with a capacity of 12
may contain 16 planes: 12 ready to fly, and 4 (4 of 12) in reserve (and
incapable of performing a mission). The capacities are as follows:

[%header]
|===
| Nationality | Ready Capacity | Reserve Capacity
| Italian Squadriglia | 9 | 3 (12 total)
| German Staffel | 12 | 4 (16 total)
| Commonwealth Squadron (1940-June '41) |  15 | 5 (20 total)
| Commonwealth Squadron (July 41-43) | 18 | 6 (24 total)
|===

Players will note that starting with July 1941 Commonwealth Squadrons increase their capacity.

[#35_24]*[35.24]* Pilots (see Case <<40_1>> for fighter and fighter bombers are
assigned to squadrons, not to specific planes. A record of pilots in a squadron
is kept on the Squadron Composition Sheet, and pilots are given specific planes
when they fly missions.

[#35_25]*[35.25]* Assignment and transfer of planes, where flying is
unnecessary, is done in the Organization Phase. Otherwise, assignment and
transfer are done in the Mission Deployment Segment (as a transfer mission).

[#35_26]*[35.26]* As noted, each squadron may keep a certain number of planes in
reserve. These planes may be readied and armed (or not, as the Player sees fit),
but they cannot fly if the ready capacity of that squadron is flying. Reserves
are used to supplement aircraft that were not readied. Reserves may not
scramable. They amy use emergency flight (see Case <<37_3>>.

[#35_27]*[35.27]* If an SGSU is eliminated (see Case <<35_12>> and there are
planes on the ground with the SGSU, the plari[s are captured. They may be used
by the opposing Player one Game-Turn later or destroyed as he sees fit.

[#35_28]*[35.28]* Italian and German planes may not coexist in the same
squadron. They require separate maintenance. However, Italian squadrons may
consist entirely of German planes (but ot vice versa).

[#35_29]*[35.29]* A historical note: Although the Commonwealth and Italian
SGSU's are indistinguishable as to type of aircraft handled (at least on the
face of the counter), the German SGSU's are not. Each SGSU represents a specific
type of plane. The Players need not follow this representation, as the SGSU's do
not represent strict squadron OB. However, for those so inclined, JG Squadrons
are Fighters, St.G. Squadrons are for Dive Bombers, KG for Bombers, ZG for
Fighter-Bombers, and H and F Squadrons for Recon. (All, of course, with a few
exceptions.)
