
[#27_0]
== DESERT RAIDERS & COMMANDOS

COMMENTARY:

On an operational level, Desert Raiders (The Long Range Desert Group and Die
Sonderkommando Almasy) had little effect on the war. However, the designers felt
that they would be missed in a simulation of this magnitude — and they do add a
lot of fun to the game. Desert Raiders are useful for "annoyance" raids: blowing
supply dumps, attacking convoys, etc. A bit of honesty is required for this
rule.

CASES:

[#27_1]
=== THE LONG RANGE DESERT GROUP

[#27_11]*[27.11]* The Commonwealth desert raiders consist of two units of the
Long Range Desert Group (LRDG). These are represented by two LRDG counters,
There may never be more than two LRDG units in play at any one time.

[#27_12]*[27.12]* LRDG units must be formed from other units, already in play,
that have reached their maximum Morale Level through training. Untrained units
may never be used to form LRDG's.

[#27_13]*[27.13]* LRDG's are formed from Recce and Armored Car TOE Strength
Points — and only from these type of units. To form an LRDG, the Player, in his
Organization Phase, simply removes the TOE Strength Point from the Reece/AC unit
and places an LRG unit on the game-map in its place.  Once formed, an LRDG unit
may not return to Recce/AC status.

[#27_14]*[27.14]* LRDG's have a Capability Point Allowance of fifty (50).
However, they have no combat ratings and may not engage in normal combat (see
Case <<27_3>>). They have no Stacking Points.

[#27_15]*[27.15]* There is no cost in Capability Points to form an LRDG unit.

[#27_16]*[27.16]* If an LRDG unit is eliminated, a new one may be formed (from
that eliminated counter) four Game-Turns later. Thus, an LRDG unit eliminated in
Operations Stage 2 of the July II Game-Turn would be formed in the Organization
Phase of the 3rd Operations Stage of the August II Game-Turn.

[#27_2]
=== DIE SONDERKOMMANDO ALMASY

The Axis desert raiders were a small group under the command of Count Laslo von
Almasy. DSA operates in the same way — and is formed in the same way — as LRDG
units, with two exceptions:

a. There may be only one DSA unit in play at any one time.

b. DSA may be formed only from German (not Italian) Armored Recce/AC units.

[#27_3]
=== HOW DESERT RAIDERS ARE USED

[#27_31]*[27.31]* Desert raiders are represented by actual counters. However,
for the most part, their movement is "hidden."

[#27_32]*[27.32]* At the time of initial formation, a desert raider unit is
placed on the game-map. After that, its movement is secret: i.e., the owning
Player records all movement and location of the unit(s) on a separate piece of
paper (against a case of a “Matter of Disbelief Between Gentlemen"). The desert
raiders follow all the normal rules of Movement (they are vehicle units, Recce
type) except that they are usually not on the game-map.

[#27_33]*[27.33]* Desert raiders remain hidden until either of the following
occurs:

a. They engage in a raid (Case <<27_5>>); or

b. They are spotted (Case <<27_4>>)

When either one of the above occurs, the desert raider counter is placed on the
game-map in the hex in which the event occurred.

[#27_34]*[27.34]* Desert raiders have no Zone of Control.  Furthermore, they do
not have to stop when entering an Enemy Zone of Control, although such movement
risks being spotted (see Case <<27_6>>. To enter an Enemy-occupied hex is to raid
(Case <<27_5>>).

[#27_35]*[27.35]* Desert raider units need supplies but not the same as normal
units. Once a week — during a given Game-Turn (not Operations Stage) — they must
pass through a Friendly supply dump, oasis or bir (well), As it passes through
the supply dump, it picks up (and expends) from the supply dump one Ammunition
Point and two Fuel Points. If such supply is not available, the desert raider
unit must wait until it becomes available. It may not travel without those two
Fuel Points per Game-Turn. Water is taken on in the same way, but can come from
any oasis or bir. If a desert raider has not drawn water by the end of a given
Game-Turn, it is eliminated. (Players will note that they can go 5 Operations
Stages without resupplying, by getting supplies in Stage 1 of a Game-Turn, then
resupplying in Stage 3 of the following Game-Turn,

[#27_36]*[27.36]* If necessary, desert raiders have Reaction capability (see
Case <<27_44>>).

[#27_37]*[27.37]* Raiders may never exceed their 50 point Capability Point
Allowance. If for any reason they are forced to do so, they are eliminated.

[#27_38]*[27.38]* Desert Raiders do not consume fuel (except <<27_35>>) nor do
they breakdown.

[#27_4]
=== SPOTTING DESERT RAIDERS

[#27_41]*[27.41]* At any time a desert raider enters an Enemy-controlled hex, or
at any time an Enemy combat unit enters a hex occupied by a Friendly desert
raider, the desert raider may be spotted.

[#27_42]*[27.42]* Desert raiders may never enter Enemy occupied hexes unless they
are going to raid.

[#27_43]*[27.43]* If a Raider performs either action listed in Case <<27_41>>, the
raider Player must announce the fact and roll one die. If he rolls a 6, the
raider has been spotted. If a raider unit is spotted, it is eliminated. Any
other dieroll has no effect; the raider has not been spotted.

[#27_44]*[27.44]* If an Enemy unit is moving (and enters the raider hex) it must
expend 1 Capability Point to try to spot the raider, even though the Enemy
Player knows that the raider is there. In other words, the moving Enemy Player
may choose not to go after the raider. A Phasing unit may. only try to spot a
raider once per Operations Stage.

[#27_5]
=== RAIDS

[#27_51]*[27.51]* The type of raid a desert raider may perform usually depends
on the objective. Most raids are "harassment" in nature, as they can cause
little real damage (except for Case <<27_6>>. They invariably take place behind
Enemy lines.

[#27_52]*[27.52]* Desert raiders may be used to blow up a water pipeline. If a
desert raider enters a hex with a water pipeline, and there are no Enemy combat
units in that hex the raider may attempt to blow the pipeline. The Player
announces the raid, places the raider on the game-map, and rolls one die. If he
rolls a 1-4, the pipe is blown; a 5-6 the pipeline is safe. Such a raid may be
attempted only once in an Operations Stage. It occurs during Movement and
expends five Capability Points (the unit may, of course, move after the raid —
away from harm).

[#27_53]*[27.53]* Desert Raiders may attempt to destroy airfields. (Air landing
strips are immune from raids; they are simply not the type of facility that can
be rendered ineffective by desert raiders). If an Enemy airfield has no Enemy
combat units in that hex, the desert raider may enter the airfield hex, reveal
itself, and attempt to cripple the field. The Player rolls one die. If he rolls
a 1 or 2, the capacity of the airfield is reduced by one level (see Case <<36_0>>).
On a dieroll of 3-6, nothing happens. The cost of the Raid is five Capability
Points, and no casualties are suffered (as there are no Enemy combat units
present). The raid may not take place if there are Enemy combat units present.
(Squadron Ground Support Units of any type are not combat units for this
purpose.) An airfield destruction raid may be attempted only once per airfield
per Game-Turn. However, it may be combined with a plane destruction raid (see
Case <<27_54>>). Airfields in major cities may not be raided.

[#27_54]*[27.54]* Desert raiders may attempt to destroy Enemy airplanes that are
on the ground. The planes may be in airfields or air landing strips.  (Raiders
can have no effect on flying boats or their facilities.) Planes in air
facilities that have Enemy combat units in the hex or are in major cities may
not be so raided, The raider unit enters the hex, reveals itself and expends
five Capability Points.  The Player rolls one die. If the result is a 1 or 2,
10% (at least) of all planes in the hex are destroyed, the choice of planes
being up to the raiding player. If a 3-6 is rolled, the raid fails.  However, if
the Player rolls a 6, the raider unit is eliminated. This raid may be combined
with attempted destruction of an airfield, as long as all Capability Point costs
are paid.

[#27_55]*[27.55]* Raiders may attack Supply Dumps. Any dump may be a target,
except for dumps in major cities. Unlike other raids, a desert raider may attack
a guarded dump. The raider unit enters the hex with the dump, reveals itself and
expends five Capability Points. Then one of two things can happen:

a. The Dump has no Enemy combat units: The Player rolls one die. If he rolls a 1
or 2, 10% of all supplies are destroyed. A 3-6 and the raid fails, and nothing
happens.

b. The Dump is guarded by Enemy combat units: The raiding player rolls two dice,
adding them together. If the total is Aigher than the Raw Defensive Assault
Strength of the units guarding the dump, the raid is on, and the Player proceeds
as in (a) above. However, unlike (a) above, if he rolls a 6, the unit is
eliminated. If the total of both dice is not higher than the Raw Defensive
Strength of the guards, the raider is simply eliminated.

[#27_56]*[27.56]* After any raiders-guards conflict is resolved, if any raiders
survive, and the dump is a dummy that fact must be revealed immediately. The
raid is then off, in terms of destroying supplies, but all other results (for
guards and elimination) stillapply.

[#27_57]*[27.57]* Desert raiders may attack unescorted truck convoys in order to
destroy trucks and supplies. This may be ddne in one of two ways:

a. The Raider enters a hex that has a truck convoy; or

b. The raider uses interception (see Case <<27_59>> during the opposing Player's
Convoy Movement Phase.

[#27_58]*[27.58]* The mechanics of a truck convoy raid are the same regardless
of the way it is initiated. The raider expends five Capability Points, enters
the hex, and the Player rolls one die. If the dierollis a 1 or 2, one Truck TOE
Point (plus cargo) is destroyed. The type of truck (heavy, medium, or light) is
up to the "defender;" the type of cargo is then up to the raider. If the dieroll
is 3-6, the raid fails. If any one of the trucks is carrying Replacement Points,
the raider adds one to the dieroll, and a 6 will result in the elimination of
the raider. If a// the trucks are carrying Replacernent Points, the Raider is
automatically eliminated, and there are no Truck losses.

[#27_59]*[27.59]* Raiders may use interception to attack truck convoys. If,
during a Truck Convoy Movement Phase, a truck convoy passes within four Movement
Capability Points of a desert raider, the Player who has the raider may halt the
convoy and attack it, using the above rules. In such a case the convoy uses five
Capability-Points (but is not required to exceed its CPA) as does the raider.
The raider may then expend up to five additional Capability Points.to leave
the hex. (Remember, the Raider pays for all Capability Points he uses.)

[#27_6]
=== RAID ON ROMMEL

This rule has been included because we felt it would add a bit of fun, although
it is based on solid historical events.

[#27_61]*[27.61]* Commonwealth LRDG units may attempt to Assassinate or Capture
General Rommel by attempting a Raid on Rommel.

[#27_62]*[27.62]* To perform this raid, the LRDG simply enters the hex which the
Rommel counter occupies.

[#27_63]*[27.63]* The Commonwealth Player rolls two dice and consults the Raid
on Rommel TAble <<27_64>>.  The results of that table are self-explanatory. The
cost for such a raid is 10 Capability Points, and if the LRDLG has no Capability
Points remaining it is also eliminated.

[#27_64]*[27.64]* The Commonwealth Player may attempt no more than four Raids on
Rommel during the course of a Campaign Game, and only one in any shorter
Scenario.

[#27_65]*[27.65]* If the Commonwealth Player is related to Alistair McLean,
Richard Burton, Franchot Tone, or Jack Higgins he adds one to his diceroll. If
the Axis Player is an intimate friend of Erich von Stroheim or James Mason,
well, that's nice.

[#27_7]
=== COMMANDOS: "Layforce"

[#27_71]*[27.71]* One of the Commando units in the game is: "A" Battalion of
the Special Service Brigade (Commonwealth), also known as Layforce because of
its Commander: Lt. Col. R.E. Laycock, of the Royal Horse Guards.

[#27_72]*[27.72]* Layforce "A" Battalion is the same as any other infantry unit
with one exception: if Layforce starts an Operations Stage in Alexandria, it may
be placed during that Operations Stage in any coastal hex on the game-map (see
Case <<27_77>>.

[#27_73]*[27.73]* Layforce "A" Battalion must spend one full Game-Turn in
Alexandria before. it can be landed. Such commando landing expends 5 Capability
Points from the unit for every 50 hexes moved by the transporting ships in that
OpStage, in addition to the cost of terrain in the hex.

[#27_74]*[27.74]* Layforce "A" Battalion needs no supplies for the first Area
Operations Stages after its landing, including the Stage in which it lands.
After that, it must be supplied like any other unit.

[#27_75]*[27.75]* If Layforce "A" Battalion is being used for a Commando raid,
trucks may not be loaded with it.

[#27_76]*[27.76]* Layforce "A" may take Replacement Points. To replace one lost
point requires three Infantry Replacement Points trained for 12 OpStages with
the Lay Force unit in Alexandria.

[#27_77]*[27.77]* Layforce may be transported by a unit from the Commonwealth
Fleet. If such ship (or ships) remain in the coastal hex in which Layforce was
landed, then the Layforce battalion may, if necessary, retreat into the ship.
Such a retreat satisfies any and all mandated retreats. The Commonwealth Player
may also freely embark the Layforce back onto a ship. Once Layforce has been
moved into the ship, the ship immediately moves back to Alexandria.

[#27_8]
=== COMMANDOS: The Special Air Service Brigade

The Commonwealth Special Air Service Brigade (SAS) was a specially-trained unit
whose primary function was the disruption and destruction of Axis air facilities
and planes. It was trained to raid by land, sea or air, and in several raids it
managed to destroy over 50 Axis planes. As such, the SAS operated closely with
the LRDG, which often arranged for transportation of the SAS after its raids.

[#27_81]*[27.81]* The Special Air Service Brigade is a “battalion-size" infantry unit with
a basic Capability Point Allowance of 15 (see the OA Sheets Section <<4_46>>.
It may be motorized; however, if being used on a raid where it is transported by
air or sea it may not be motorized. The SAS Brigade may operate as a normal
infantry unit (a waste) or as a Commando unit.

[#27_82]*[27.82]* The SAS Brigade raids Enemy airfields. It may raid guarded
(with Axis troops) or unguarded facilities. It may complete its raid (and roll
for plane destruction) only if there are no Axis combat units in the hex. Thus,
if the SAS Brigade raids a facility with Axis combat units, it must either
eliminate such units or force such units to retreat in some way. Any such combat
is conducted normally.

[#27_83]*[27.83]* The SAS Brigade may move by land (see Case <<27_81>>. If it
does so it moves like any other land combat unit. It may also be transported by
any one Commonwealth Ship counter and debarked in any coastal hex, at a cost of
five Capability Points to the SAS for every 50 Movement Points or fraction
thereofused by the ship. It may also be airdropped (see Case <<42_4>> at a cost
of 5 Capability Points to the SAS unit.

[#27_84]*[27.84]* If the SAS Brigade travels by land, it uses normal supply
restrictions and rules. If it is transported by sea or airdropped, it is in
supply for three consecutive OpStages. This means that the unit has all the
necessary ammunition, water, and stores it needs for those three OpStages
(including the one of its transportation). After that, it is on its own.

[#27_85]*[27.85]* The SAS Brigade may attempt to destroy planes on any Axis Air
Facility that has no Axis combat units present at the time the raid is attempted
(see Case <<27_82>>. The SAS unit may attempt its raid in any Movement/Combat
Segment.

[#27_86]*[27.86]* To destroy Axis Planes by an SAS raid the Commonwealth Player
consults the SAS Raid Table, rolls one die, and removes the resultant percentage
of each type and make of plane present (see Case <<27_9>>). The TOE Strength of
the SAS Brigade at the time of such raid is irrelevant.

[#27_87]*[27.87]* Attempting a raid costs the SAS Brigade three Capability
Points, in addition to any other Capability Points it may have expended during
that OpStage. Only one such raid may be performed per month, and there must be
at least six OpStages between raids.

[#27_88]*[27.88]* The SAS Brigade-may move after a raid as far as it wishes,
within the parameters of continual movement and cohesion. However, if the
Commonwealth Player stacks that SAS Brigade unit with an LRDG unit at any time
the SAS Brigade increases its Capability Point Allowance to 30, is removed from
"physical sight" (in the fashion of an LRDG unit; see Case 00.00 and moves as
an LRDG unit. The LRDG unit must escort the SAS unit to the point where it (the
SAS Brigade) is placed on the game-map — i.e., it has returned home.

[#27_89]*[27.89]* The SAS Brigade may replace eliminated TOE Strength Points,
three Infantry Replacement Points trained for a 12 OpStage period for every TOE
point needing replacement. If the SAS Brigade is eliminated entirely, it may not
be received or replaced in any way.

[#27_9]
=== DESERT RAIDER RAIDS TABLES

(see Charts and Tables)

[#27_91]*[27.91] Desert Raider Raid Table*

(see Charts and Tables)

[#27_92]*[27.92] Raid on Rommel Table*

(see Charts and Tables)

[#27_93]*[27.93] Special Air Service Brigade Raid Table*

(see Charts and Tables)
