[#32_0]
== ABSTRACT LOGISTICS AND AIR RULES

COMMENTARY:

The design thrust of CNA is logistics: the availability and proper use of
supplies and trucks.  As a simple experiment to test the efficacy of this, try
motorizing all Italian divisions in 1940, doubling Italian initial supply outlay
and arrival. Watch them winter in Cairo. However, both designer and developer,
men of some mercy, felt that there were those who might want to try CNA from a
purely military viewpoint. To this end, they have formulated the rules below,
enabling players to work within a simpler logistics format. The game is not
really simplified, it is just a lot less work; it should also cut playing time
in half (from endless to simply horrendous).Moreover, because virtually all of
the design effort went into the stardard game, using these rules will have some
effect on game balance. How much is up to how well and how historically the
players perform. (see Section 65.0).

GENERAL RULE:

This Section applies if the Players are playing the Land Game without the Air
and Logistics Games.  All supply expenditures in the Land and Air ‘Games rules
are ignored and are replaced by those Ammo andFuel costs listed in this section.
Players will not receive any trucks but rather receive Motorization Points which
may beused to increase the CPA of non-motorized units or to transport “Supply
Units." Supply Units contain Ammo and Fuel Points which must be expended in
order for units to move and fight. Supply units are received in lieu of and,
with some adjustments, in the same manner as standard supplies.

[#32_1]
=== SUPPLY UNITS AND SUPPLY

[#32_11]*[32.11]* The Players ignore all references to usage and expenditure of
Ammo, Fuel, Stores and Water. (Thus, no unit will ever suffer attrition from
lack of Stores, etc.). Only those rules for sup ply given below apply.

[#32_12]*[32.12]* The Players will be receiving Supply Units, which are abstract
substitutes for all of the aforementioned points. A Supply Unit is represented
by a Supply Dump counter.

[#32_13]*[32.13]* A Supply Unit has no combat capabilities.  If any enemy combat
unit enters a Supply Unit's hex, that unit is captured (and its supplies used
immediately and freely).

[#32_14]*[32.14]* A Supply Unit possesses a stacking value of zero. However,
only five such units may be placed in a Major City hex while only three units
may be placed in any other type of hex off-map.  The boxes of the
Tripoli/Tunisia region may contain an unlimited number of Supply Units.

[#32_15]*[32.15]* A Supply Unit initially contains and may never contain more
than 40 Ammo Points and 60 Fuel Points. Expenditures will reduce these numbers,
When both Ammo and Fuel Points are at zero, the Supply Unit is removed. Supplies
may be rearranged (at no cost) among Supply Units occupying the same hex during
the Organization Phase. Movement and combat supply requirements may be satisfied
by any Friendly Supply Unit within range.

[#32_16]*[32.16]* A Supply Unit may be drawn upon by any Friendly combat unit if
it is within one-half (1/2) of that combat unit's CPA. Thus, a nonmotorized
infantry unit would have to be within 5 CP's of a Supply Unit, while a heavy
weapons unit being transported by Motorization Points would have to be within 10
CP's and a typical recce unit unit within 23 CP's. The distance is calculated
from the unit to the Supply Unit as though it is being traversed by a medium
Truck unless the unit is a non-motorized infantry unit in which case it is
traced as infantry movement. The supply line may not be traced thru impassable
terrain or enemy ZOC's unoccupied by Friendly units.

[#32_17]*[32.17]* Players may attempt to destroy Supply Units they are with. To
do.so the Player expends one-half of the CPA of all units in the hex (rounding
upwards) and rolls one die for each Supply Unit in the hex. If he rolls a 1, 2
or 3 the Supply Unit is destroyed, any other result and it is unaffected. If the
sum of the Stacking Points in the hex during the attempt is one or less, add one
to the die roll. Attempting destruction of Supply Unit(s) occurs prior to any
movement in a given sub-segment of a Movement/Combat Segment. Only one attempt
may be made per Supply Unit per subSegment.

[#32_18]*[32.18]* Players may use dummy Supply Units to confuse their
opponent(s). For every three Supply Units a Player receives and/or begins a
scenario with, a Player may place one dummy Supply Unit on the map. It is moved
int he same fashion as the real thing (although it requires less Motorization
Points) and is removed upon discovery.

[#32_2]
=== SUPPLY EXPENDITURES

The Players will be required to keep track of the number of Ammo and Fuel Points
in each supply unit. The Supply Dump, Truck Convoy and TOE Log Sheets may be
used for this purpose. Note that for this Case's purposes, the Commonwealth
Fleet and TOE Strength Points being used to Patrot do not require supplies.

[#32_21]*[32.21]* Ammo Points are expended by the number of individual
battalion-equivalents supplied (that is, a five Stacking Point value division
expends ammo by its component counters — not as a whole). A non-Phasing Bn-Eq
requires one Ammo Point to participate in an Assault and two Ammo Points to
participate in a Barrage. A Phasing unit requires twice the appropriate number
of Ammo Points as a non-Phasing Unit.

[#32_22]*[32.22]* Ammo Points must be expended at the instant of combat.

[#32_23]*[32.23]* Fuel Points are expended per Operations State. Basically, each
battalion-equivalent expends one Fuel Point in any Operations State in which it
is moved by land (as opposed to rail or sea). In each Operations Stage, the
first time a fuel requiring unit is moved, the required one (or two) Fuel Points
are expended from a Supply Unit. This unit may now be moved up to its CPA in any
combination of movements and halts within that Operations State. If the unit
exceeds its CPA in that OpStage, additional Fuel Points must be expended at the
instant the unit exceeds its CPA.

[#32_24]*[32.24]* Each tank battalion equivalent requires two fuel points for
movement. Each tank Company-Eq requires one fuel point to move, All Gun-Class
and Recce-type (excluding camel reconnaissance) battalion-equivalents require
one Fuel Point to move. Any Motorization Points transporting infantry units (not
Replacement Points) or gun unit battalion-equivalents or a real Supply Unit
require one Fuel Point. (Companyequivalents or Motorization Points used for
purposes other than listed above do not require Fuel Points).

[#32_25]*[32.25]* Patrolling does not require supply expenditure.

[#32_3]
=== MOVEMENT OF SUPPLY UNITS

[#32_31]*[32.31]* Supply Units may be moved by land, -rail, sea, and air. A
Supply Unit may be moved by land or rail during the OpStage in which it arrives.

[#32_32]*[32.32]* Supply Units may be transported by Motorization Points. Thirty
Motorization Points are required to transport one real supply unit. Six
Motorization Points are required to transport a dummy supply unit. Motorization
Points may be attached/detached to supply units only during the Organization
Phase of an OpStage. A supply unit not assigned the minimum necessary number of
Motorization Points may not be moved.

[#32_33]*[32.33]* A supply unit being transported by Motorization Points may be
moved in the owning Player's Movement/Combat Phase or Truck Convoy Phase but not
both. It may be moved in the friendly Movement and Combat Phase only if it
begins and remains stacked with a Friendly combat unit. Not that this
restriction has no effect on the normal non-Phasing movement.

[#32_34]*[32.34]* The Commonwealth Player may transport any two supply units
(real and/or dummy) by rail in any one direction as the total load for a given
Operation Stage. Normal rail movement rules apply.

[#32_35]*[32.35]* The Axis Player may transport supply units by Axis Coastal
Shipping. Each supply unit requires 2000 tons of coastal shipping (he may use
two ships on one mission).

[#32_36]*[32.36]* The Commonwealth Player may transport a total of one supply
unit per OpStage by sea to/from the ports of Alexandria, Benghazi, and Torbruk.
The port of destination must currenly possess an efficiency level permitting the
usage of at least 50% of the port's listed capacity. This sea transport occurs
during the Naval Convoy Arrival Phase andis in lieu of any combat unit transport
from the port of origin and into the port of destination.

[#32_37]*[32.37]* Only supply units may be transported by
air. Each Player may air transport one supply unit per Game-Turn. The air
transport occurs during the Organization Phase of an OpStage (Motorization
Points may be detached in order for the supply unit to be air transported).  The
supply unit is simply picked up and placed in a new hex. The hex of origin and
destination must be a major city, village, or Tripoli/Tunisia box. The owning
Player must expend 12 Fuel Points before transport from any supply unit in the
hex or origin. The supply unit may not be transported from a hex if there are
any Enemy combat units within five hexes of that hex. The supply unit may not be
transported further east (if Axis), or west (if Commonwealth) than the
easternmost/westernmot hexrow (respectively) occupied by a Friendly division
(shell or full). In addition, the destination hex must be occupied by a Friendly
division or brigade (not battle-group) headquarters counter. An air-transported
supply unit (and its supplies) may not be moved at all by the owning Player that
OpStage, although it may be drawn upon (see Case<<32_16>>.

[#32_4]
=== AVAILABLILITY OF SUPPLY UNITS

[#32_41]*[32.41]* At the start of each scenario the Players receive a specified
number of Supply Units (see the Simplified Supply case in each scenario). In
addition, the Players receive Supply Units from the Simplified Supply Unit
Availability Tables (see case<<32_46>>and<<32_47>>.

[#32_42]*[32.42]* Supply Units for the Axis Player arrive as per convoy,
see<<32_6>>Commonwealth Supply Units are placed in Cairo unless more than three
are received in a single Game-Turn. In sucha case, one Supply Unit for every
three received may be placed in Alexandria.

[#32_43]*[32.43]* At the beginning of each Game-Turn, the Players plan for the
arrival of their supply units.  The Axis Player plans two Game-Turns in advance,
the Commonwealth four Game Turns in advance. Players may do as much planning as
is necessary to that, with the exception of the starting Game-Turn of a
scenario, Supply Units arrive on all Game-Turns (if permitted by the planning
die rolls).

[#32_44]*[32.44]* The Axis Player plans his supply using the following
procedure. He consults the Axis Naval Convoy <<00_00>> and determines the
appropriate Availability Chart Tonnage Availability Letter for the month in
which he is planning (not the month in which it is arriving). He then consults
the Axis Simplified Supply Availability Table. He rolls one die and cross
indixes the roll with the column matching the letter. The result is the number
‘of Real Supply Units he may bring in on Axis Naval Convoys two Game-Turns from
then.

[#32_43]*[32.43]* The Commonwealth Player plans his supply using the following
procedure. He consults the Commonwealth Simplified Supply Availability Table and
determines the time period involved.  This time period is that of the arrival of
the Supply Units, not the one in which they are being planned.  He then rolls
one die, cross indexing it with the proper column. The result is the number of
Real Supply Units he receives four Game-Turns hence.

[#32_46]*[32.46] Axis Simplified Supply Availability Table*

(see Charts and Tables)

[#32_47]*[32.47] Commonwealth Simplified Supply Availability Table*

(see charts and tables)

[#32_5]
=== MOTORIZATION POINTS

[#32_53]*[32.53]* Motorization Points are used in place of Truck Points. They
are used to transport (motorize)units and may also be assigned to transport
Supply Units. Motorization Points are treated in all aspects as Medium Truck
Points except as modified in this Major Case.

[#32_52]*[32.52]* Each scenario lists the number of Motorization Points
initially available to the Players. Additional Motorization Points are received
as reinforcements as per scenario instructions. In addition, Players may bring
in Motorization Points as Replacements at a rate equal to their ability to bring
in Mdium Truck Replacement Points.

[#32_53]*[32.53]* Motorization Points may be used to transport units and all
Guns with a CPA of 0+.  All normal units are considered to possess their own
‘built-in' transport, as in the standard game.

[#32_54]*[32.54]* All ‘leg' infantry units may be motorized.  However, a Player
must assign Motorization Points sufficient to transport all historically
motorized infantry units (i.e., those with CPA's of 8+ and 10+) before assigning
them to any other infantry-type units.

[#32_55]*[32.55]* Motorization points are not subject to Breakdown. All other
Breakdown rules apply.

[#32_56]*[32.56]* Motorization Points are normally subject to loss only if the
unit they are assigned to is eliminated. If their assigned unit is captured, the
Motorization Points are also captured and may be used by the Enemy. Note that a
Barrage Combat Result against Trucks never occurs.

[#32_57]*[32.57]* Motorization Points are subject to (abstract) loss from
various factors (mostly Enemy aircraft). During the first Naval Convoy Stage of
each month, Motorization Points losses for the previous month are determined.
The Players consult the Abstract Motorization Point Loss Chart and read the
result for the appropriate month. The number to the left of the stroke is the
percentage of Motorization Points lost by the Commonwealth Player; the number to
the right of the stroke the percentage lost by the Axis Player. The percentage
is that of the total Motorization Points belonging to the Player on the map
(which includes Tripolitania-Tunis boxes) at that point in time.  The points
lost may be removed from anywhere on map Section E for the Commonwealth Player
or anywhere on Section A (including the off-map region) for the Axis Player.

[#32_58]*[32.58]* Motorization Points transporting a supply unit have the
following attributes:

A. They possess a CPA of 15.

B. If forced to exceed their CPA for any reason, they must be returned to the
last hex in which they had not exceeded their CPA.

C. Are not required to expend CP's if stacked with combat units participating in
combat.

D. May react unless the unit moving adjacent possesses a CPA of 35 or more.

[#32_59]*[32.59] Abstract Truck/Motorization Loss Chart*

(see Charts and Tables)

[#32_6]
=== SIMPLIFIED AXIS NAVAL CONVOYS

[#32_61]*[32.61]* In the abstract Logistics game system, Axis Naval Convoys
consist of all Supply Units, Motorization Points and Replacement Points for that
Game-Turn. These items may be divided and assigned to any Convoy Lane available,
as per rules for such assignment <<56_0>>. These are no tonnage limitation.

[#32_62]*[32.62]* The Axis Player may never assign more than three Supply Units
and twenty Motorization Points to any one Convoy Lane in any one Naval Convoy
Stage. Note that the Axis Player is limited by the Replacement Pool's charts as
to the maximum number of each type item that may be assigned to Axis Naval
Convoys (total) for arrival during a particular Game-Turn.

[#32_63]*[32.63]* The Commonwealth Player may attempt to destroy whatever is
being shipped by a particular convoy. He may attack all convoys regardless of
the weather on the map. The attack(s) occur in the Naval Convoy Phase of the
OpStage. The Axis Player announces which convoy lanes are being used. The
Commonwealth Player then attacks each arriving convoy separately.

[#32_64]*[32.64]* Each attack is carried out as follows: The Commonwealth Player
consults the Simple Axis Naval Convoy Bombing Chart <<32_66>> and reads down the
proper Convoy Lane column until reaching the westernmost location of a
qualifying Commonwealth division. He then reads across that row to determine the
number of Bomb Points to be used in the attack. The Commonwealth Player then
consults the Air Bombardment Combat Results Table, rolls two dice reading them
sequentially and refers to the previously determined Bomb Points column to yield
the result. The result is expressed in percentage of supply units, Motorization
Points and Replacement Points assigned to that convoy lane that are destroyed.

[#32_65]*[32.65]* The result obtained above on the Axis Naval' Convoy is
modified as follows:

A. A result of 10% applies only to Motorization Points and Replacement Points,
rounding fractions down for the former and rounding fractiongs up for the
latter.

B. A result of 20% or greater applies to all items being conveyed, rounding
fractions down. However, at least one point of each and Supply Unit is always
eliminated.

Losses of tanks and guns, within each nationality, are in percentages of the
total, not the individual types. For example, a convoy carrying one point of CV
33's, two points of PzII's, two points of PzIIIJ's and two points of PzIVH's
that suffers a 10% loss only has the CV 33 and one German tank point eliminated
(the Axis Player's choice).

[#32_66]*[32.66] Simple Axis Naval Convoy Bombing Chart*

(see Charts and Tables)

[#32_7]
=== BOMBARDMENT OF THE COMMONWEALTH FLEET

[#32_71]*[32.71]* The Axis Player may perform a limited number of Bombardment
attacks on the Commonwealth Fleet in Alexandria Harbor.

[#32_72]*[32.72]* The Axis Player determines the number of such attacks he is
permitted to make in the scenario as follows: He rolls one die secretly, adding
two to the number if playing a Campaign Game. The result is the number of
attacks the Axis Player may perform against Commonwealth ships using the Air
Bombardment and Secondary Barrage Targets Combat Results Table in that Scenario.

[#32_73]*[32.73]* The Axis Player may only perform one such attack per
Operations Stage. Each attack must be plotted secretly during the' Commonwealth
Fleet Assignment Segment of an Operations Stage. Once planned, it occurs in the
Tactical Naval Movement Segment of that Operations Stage.

[#32_74]*[32.74]* The attack is performed as follows:

a. The Axis Player determines the strength of the attack by consulting the Air
Bombardment and Secondary Barrage Target Combat Results Table and rolling one
die, adding two to the die roll if playing the Campaign Game. The attack is
determined on that number of columns in from the left hand side of the table
(that is, a roll of 1 would result in the attack being performed on the Bomb
Points: 1-20 column, etc.)

b. The Axis Player rolls two dice, reading them sequentially. He cross-indexes
the dice roll with the proper column to determine the result. The result is the
number of damage points (see the Chariot Raid Table,<<30_46>> inflicted upon the
ships in Alexandria Harbor (only). The Axis Player may distribute these Damage
Points in any manner he wishes.

[#32_75]*[32.75]* No Bombardment attack may be made if Game-map section "E"'s
weather is either rain storm or sand storm.

[#32_8]
=== ANTI-ARR UNIT MODIFICATIONS

[#32_81]*[32.81]* The Commonwealth Player removes all Anti-air units and all
Light and Heavy Anti-air TOE Strength Points (regardless of where assigned) from
play. This includes anti-air Replacement Points. Captured Axis anti-air TOE
Strength Points are immediately removed from play.

[#32_82]*[32.82]* The Axis Player removes all German antiair units with ID Codes
of "z" and "bb" from play. All assigned light anti-air TOE Strength Points and
Replacement Points are removed from play. Heavy anti-air TOE Strength Points and
Replacement Points are unaffected.

[#32_83]*[32.83]* The Axis Player's Italian forces are affected as follows:

1. All anti-air units (.e., those with ID Codes of “ss" “tt" and "uu") are
removed from play.

2. All anti-air TOE Strength Points assigned to emplaced gun units (ID Code
"pp") are removed from play (just the AA points);

3. Artillery units that may be assigned anti-air points (ID Code "kk") lose all
assigned Heavy anti-air TOE Strength Points.

4. All Heavy anti-air (i.e., 75mm and 90mm) Replacement Points are lost.

5. Light anti-air Replacement Points may only be brought in at a rate of one per
month (effectively halving the number of available points).

[#32_84]*[32.84]* All of the above modifications and restrictions apply to
anti-air TOE Strength Points and Replacement Points. They do not affect
non-antiair TOE Strength Points/Replacement Points that possess an anti-air
rating.

[#32_9]
=== ROAD AND TRACK STACKING MODIFICATION

The Players ignore all Road and Track (only) Stacking Point restrictions listed
in Section <<9_0>>.

[#32_10]
== ADDENDA

The following addenda to the rules and counters of Campaign for North Africa are
the result of continuing testing and fine tuning by the design/development team.
In a game the size of CNA, it is a virtual certainty that some points will be in
need of clarification — or even correction, despite the most elaborate
precautions. The following addenda are included as the game goes to press in
order to provide the most up-to-date game possible.

<<3_1>> (clarification) Parent Unit. The terms Parent Unit and Parent Formation
have been used interchangeably. It was intended that they express the following
distinction: a Parent Unit has counters attached while a Parent Formation has
counters assigned.

<<3_4>> (clarification) Coast Defense Guns. There are three types of coast
defense guns in CNA:

A. Inname only: A number of units possess the title of Coastal Defense Artillery
that are nothing of the sort. These may be distinguished by. the fact that their
guns possess CPA's of 15. They were simply artillery units (theoretically)
assigned to a coastal defense role. They may contain any type of artillery.

B. Sited Guns: These units and/or TOE Strength Points possess a CPA of ‘0+."
This indicates that while the guns did not possess organic transport, had
transport been available, the guns could have been moved with little trouble.

C. Emplaced Guns: The units and/or TOE Strength Points possess a CPA of "0.'?
This indicates that the guns have been "fixed" in revetments and may never be
moved. Note that there were emplaced guns at Benghazi that are not represented
in CNA due to their inability to fire at shoreward targets coupled with the game
restriction as to how far west Commonwealth warships may operate.

<<3_6>> LIMITED INTELLIGENCE (addition). CNA relies heavily on the Players'
willingness to trust one another. Virtually all of the information in the game
is kept hidden from your opponent.  Even in land combat, only the totals are
revealed, not the units producing them.

[#3_61]*[3.61]* Players are not entitled to any knowledge
of the status, composition, or any other attributes
of any opposing counter in CNA except as expressly indicated in the rules.

[#3_62]*[3.62]* The following is a partial listing of the information available
to opposing Players:

Map:: A Player may examine any stack of counters
on the game map. What is in those counters is
another story.

Anti-armor Fire:: The types of tanks and selfpropelled guns, presence of armored
recce-type and/or halftracks actively participating in Assault in a hex but not
the numbers, hex(es) of origin or which TOE Strength Points absorbed the Damage
Points.

Close Assault:: The unit types actively participating in Close Assault (or
forced into it via Overrun) but not the numbers, weapon systems what took
losses, etc.

Prisoners:: Nothing. All you get is the prisoners
and captured equipment; they may not be quizzed.

Patrol:: No mention of the state of supplies or attached trucks (other than whether the unit is
motorized).

Broken down vehicles/destroyed tanks/abandoned vehicles:: The contents of the marker is secret.

POW's/POW Camps/Guards:: The numbers (and nationality, if Axis) are secret.

Construction:: The item undergoing construction/demolition is secret.

Trucks & Replacement Points:: The numbers, types, etc., are secret.

Air reconnaissance:: Even less detail than Patrol.

Planes:: The Players are entitled to know the exact makes of opposing planes
engaged in air-air combat but the pilot ratings are secret up to the instant of
combat. Land units without any Anti-air TOE Strength Points or an SGSU in a hex
in which a bombing or strafing mission occurs are not entitled to know the
numbers or types of planes engaged in the mission(s), only the type of mission
being performed.

<<12_0>> *(clarification)* For the purposes of this Section, all references to
artillery units apply to any unit comprised of TOE Strength Points with a
Barrage Rating.

[#12_23]*[12.23]* (addition) Commonwealth warships are always considered to be
historically identified targets.

[#12_46]*[12.46]* (clarification) Trucks do not receive terrain benefits.

<<14_0>> *(clarification)* Anti-armor fire occurs within a hex occupied by the
non-Phasing Player's units. However, either Player may be the attacker and/or
the defender.

[#14_15]*[14.15]* (addition) A parenthesized anti-armor rating may only be used
if there are no units comprising TOE Strength Points possessing nonparenthesized
anti-armor ratings. Note that replacement points do not affect this ability.

[#14_27]*[14.27]* (clarification) The Phasing Player may send TOE Strength
Points from a unit into different hexes, regardless of whether all are engaging
in anti-armor or all in close assault.

[#16_51]*[16.51]* (clarification) Note that the Patrolling Player does not
identify the types of TOE Strength Points comprising the unit. Example: A tank
battalion comprising four Shermans, two Stuarts, and two Mark VI Lights (8 TOE
Points) can be simply reported as a tank battalion of six points (8 + 2 points).

[#19_62]*[19.62]* (addition) Any eliminated unit whose maximum TOE Limit is one
or two TOE Strength Points. If the unit's assigned spot has been taken by the
time it is recreated, it is treated as an independent unit.

[#20_63]*[20.63]* The Axis Player is required to schedule at least fwo weeks in
advance, those Replacement Points (from his Axis Replacement Pool) he is sen
ding to NorthAfrica via the Axis naval convoys.  Replacement Points may be
scheduled to arrive during any OpStage of a Game-Turn, as per the naval convoy
rules. For example, Replacement Points arriving during the third week of August,
1941 must be scheduled for Axis naval convoys in the first week of August's
Naval Convoy Schedule Phase. (Players should note that the maximum tonnage that
the Axis naval convoys of the third week of August is determined during the
second week of August!)

[#21_11]*[21.11]* (addition) TOE Strength Points comprising a headquarters unit
are not subject to breakdown, regardless of type.

[#21_63]*[21.63]* (clarification) Any portion of the broken down vehicles in a
hex may be towed. However, if only some are towed, the owning Player will have
to place an additional marker in the new location and adjust his information on
the control sheet (see Case<<21_67>>.

[#21_67]*[21.67]* (addition) Players should avoid proliferating masses of broken
down vehicles and destroyed tank markers over the game map.

[#23_15]*[23.15]* (addition) The Commonwealth Player receives, via the
Reinforcement Track, two tank battalions completely refitted (re-equipped) with
Scorpion tanks (historically the 42nd and 44th Royal Tank Regiments). These two
battalions are engineer units but possess only anti-minefield capabilities. Each
battalion is considered to possess engineer unit status while it contains at
least six Scorpion TOE Strength Points. Note that the points may not be
transferred to other units for any reason, including the elimination of the
"tank" battalion.

[#24_79]*[24.79]* (addition) A maximum of one flying boat facility and one
non-flying boat facility may be built in any hex. Air landing strips and flying
boat alighting areas may be upgraded to airfield and flying boat basin status
respectively. However, the facility may not be used while the upgrading is
underway and no benefit in reduction of construction is applied.

[#27_32]*[27.32]* (clarification) This includes pipeline in railroad hexes
(although the railroad itself may not be harmed by a raid).

[#30_36]*[30.36]* (addition) If the warship is eliminated while transporting a
commando unit, the commando unit is also eliminated.

=== COUNTER ADDENDA

Counter Section Nr. 1

A. The following headquarters units are missing their identifying stripe: 63
Cir, 157 (63), 158 (63), 64 Cat, 141 (64), 142 (64), 101 Tst, 65 (101), 66
(101), 9 Brs (101), 102 Trn, 61 (102), 62 (102), 7 Brs (102), Ariete, 132 RC
(Ariete), 8 Brs (Ariete), Littorio, 133 RC (Littorio), 12 Brs (Littorio), and
the 136 GGFF.

B. The 101st Trieste Division's divisional and regimental headquarters counters
(i.e., 102 Tst, 65, and 66) should show a motorized infantry instead of
mechanized infantry symbols.

C. The 2/8Brs (Ariete) Anti-tank Battalion is assigned directly to the Ariete's
divisional headquarters and should bear a counter abbreviation and parent
formation indicator of “‘2 (Ariete)." It is correctly listed on the Ariete's OA
Sheet.

D. 141st Regiment of the 64th Catanzaro Division is missing its organization
size indicator of "III"

E. The IV/66 (101st Trieste) Company should show Heavy Weapons and not an
Anti-tank symbol.
