[#7_0] 
== INITIATIVE 

GENERAL RULE:

Initiative is an abstract, numerical rating represen tative of the strategic
leadership capabilities of a given army. It is used, in the game, to determine
who has the choice to act first within a given Operations Stage. The fact that a
Player has the ability to choose when he will move is a great advantage, and the
army with better initiative will often find that it has the upper hand
operationally — if not materially.

[#7_1] 
=== THE MECHANICS OF INITIATIVE

[#7_11]*[7.11]* The Player who has "Initiative" for a Game-Turn may choose
whether he wishes to move first or last in a given Operations Stage.

[#7_12]*[7.12]* The Player who will have the Initiative is determined at the
beginning of each Game-Turn (not Operation Stage). The Player who gains the
Initiative keepts that Initiative for all three Operations Stages in that
Game-Turn. Thus, the Player with Initiative may choose to move first in the
first Operations Stage, last in the second stage and then first in the third
Stage (which would give him, in effect, two "turns" ina row).

[#7_13]*[7.13]* Each side possesses an Initiative Rating (<<7_2>>), which is
dependent on the date of the GameTurn.

[#7_14]*[7.14]* To determine which Player has the Initiative for a given
Game-Turn, each Player, in the Initiative Determinate Stage, rolls one die and
adds his Initiative Rating to the result of the thrown die. The Player with the
highest total (ties roll again) gains the Initiative. Thus, in October of 1940,
if the Italian Player, with an Initiative Rating of '1', were to roll a '4',
and the Commonwealth Player, with an Initiative Rating of '3', were to roll a
'1', the Italian Player would gain the Initiative by virtue of having a total
of five (1 + 4 = 5) to the Commonwealth total of '4' (3 + 1 = 4). The Italian
Player would now be able to choose, in his Initiative Declaration Phase,
whether he wants to move first or last in the Operations Stage for each of
three Operations Stages in the Game-Turn.

[#7_15]*[7.15]* The Player with Initiative for the first Game-Turn of a given scenario
is usually predetermined, Check the individual scenarios for who has the
Initiative for the first Game-Turn.

[#7_16]*[7.16]* For purposes of the Sequence of Play, the Player who moves
first in an Operations Stage is called "Player A"; the Player who moves last
in an Operations Stage is called "Player B".

[#7_2] 
=== INITIATIVE RATINGS CHART

This chart lists the Axis and CW initiative ratings for all units at any given
point in the game. (See Separate Sheets)

