[#20_0]
== REINFORCEMENTS, REPLACEMENTS AND COMMONWEALTH WITHDRAWALS

GENERAL RULE:

Both sides receive Reinforcements and Replacements. Reinforcements are entire
units; Replacements are TOE Strength Points of particular Classes. Both Players
receive Reinforcements according to the schedule listed on the Reinforcement
Track. In addition, the Commonwealth Player receives Replacements according to
Commonwealth Production, and the Axis Player receives Replacements more or less
at his whim out of the Axis Replacement Pool.

Important: Any Replacement die rolls may be kept secret from the other Players
(including other members of your own team).

CASES:

[#20_1]
=== REINFORCEMENTS

[#20_11]
*[20.11]* Reinforcements are new, whole units that arrive as specified
by the Reinforcement Track.  Thus, in the September 3/2, Operations Stage,
the Commonwealth Player receives the 6th New Zealand Brigade (and its three
battalions) as well as the 6th NZ Field Artillery Regiment.

[#20_12]
*[20.12]* Reinforcements enter the game at the beginning of the Naval
Convoy Arrival Phase of the Operations Stage. There is no Capability Point cost
for debarking; arriving units may be moved in the first Operations Stage of
arrival. (The arrival dates have been adjusted to account for the logistical
problems of debarkation, etc.) Units do not pay a Capability Point cost for the
first hex they are placed in.

[#20_13]
*[20.13]* Reinforcements are treated as any other units as soon as they
have arrived, and they may perform any and all game functions normally.

[#20_14]
*[20.14]* Commonwealth reinforcements, unless noted below, arrive at
Cairo. Layforce Commando unit (Game-Turn 19) and the Tiger Convoy (Game-Turn 32)
of Tank Replacement Points (which are reinforcements) arrive in Alexandria.
Returning withdrawn units arrive at Cairo or Alexandria at the Commonwealth
Player's option (subject to stacking restrictions).

[#20_15]
*[20.15]* All Axis reinforcements arrive in Tripoli, However, if there
are no Commonwealth land combat units west of Mersa Matruh (inclusive) then the
Axis Player may divert forces to Benghazi. The Axis Player may bring in one
battalion-equivalent combat unit or two companyequivalent combat units and up to
ten Truck (or Motorization) Points assigned to arrive with that unit (or its
parent unit). The Axis Player may not divert units to Benghazi if this will
exceed stacking restrictions or if Benghazi has worse than a Level three
efficiency at that point in time. This use of Benghazi does affect its port
capacity for that Operations Stage (see Case <<55_1>>).

[#20_2]
=== REPLACEMENT POINTS

Replacement Points are designated by Class as follows: Infantry Points, Gun
Points, Tank Points, and Recce Points. Replacement Points usually enter the game
for Axis Replacement Points only — at the option of the Axis Player from the
Axis Replacement Points Pool (see Case <<20_6>>),-or — for the Commonwealth Player
only — in accordance with the Commonwealth Production System (see Case
<<20_7>>). All Replacement Points, regardless of the method in which they enter
the game, are covered by the same restrictions as listed in this Case.

[#20_21]
*[20.21]* All Replacement Points "arrive" in the Naval Convoy Arrival
Phase of an Operations Stage. Replacement Points mandated by the Reinforcement
Track arrive in a particular Stage of a particular Game-Turn as designated.
Replacement Points from the Axis Replacement Points Pool arrive in a particular
Stage as determined by the Axis Player; however, he must plan such arrivals two
full Game-Turns in advance (see Case <<20_6>>).  Replacement Points from
Commonwealth Production also arrive in particular Stages as determined by the
Commonwealth Player; these must be determined four Game-Turns in advance (see
Case <<20_7>>).

[#20_22]
*[20.22]* Commonwealth Replacement Points may be—rarely—listed on the
Reinforcement Track.They are designated by type (e.g., the Commonwealth Player
will receive "27 points of Matildas," not merely "27 points of tanks").

[#20_23]
*[20.23]* Replacement Points that are available in the Axis Replacement
Pool are designated by type only. He is limited as to how many points of each
type may be brought in during any one turn. See the Axis Replacement Pool.

[#20_24]
*[20.24]* Similarly, Replacement Points available according to the
Commonwealth Production System are designated by type and limited as to
availability.

[#20_3]
=== REPLACEMENT POINT CONVERSION CHART

(see Charts and Tables)

[#20_4]
=== HOW REPLACEMENT POINTS

[#20_41]
*[20.41]* Trained Replacement Points may be assigned to (and absorbed
by) a unit any place on the game-map (even in an Enemy Zone of Control).
However, the Replacement Point and the receiving unit must be in the same hex.
This means that "Mohammed usually goes to the Mountain,”' rather than the
latter. Points must be assigned for eventual delivery to specific units
immediately upon arrival. Should the designated unit be eliminated, or
withdrawn, such points must be reassigned immediately.

[#20_42]
*[20.42]* Counters are provided to represent the Replacement Points.
Replacement Point counters have all the characteristics of an actual unit, with
several major exceptions:

a. They may never voluntarily enter an Enemy Zone of Control unless the hex is
occupied by a Friendly unit;

b. They may never be used in any type of combat other than defending against
Close Assault, regardless of the strategic or tactical situation;

c. They all have a Basic Morale of — 3 (in their unabsorbed state);

d. They may never exceed their Capability Point Aliowance (which is that of the
unit they are being assigned to); if they ever exceed their CPA — for any reason
— they are considered to have a Cohesion Level of — 26.

[#20_43]
*[20.43]* Replacement Points (both Axis and Commonwealth) are required
to undergo Training. They must train for a specific number of Operations Stages,
which may include the Stage of arrival, Players should consult the rules on
Training (<<17_3>>) for particulars, as the same rules that apply to Training
Reinforcements apply to Replacements. Axis points train in Tripoli or any major
city. Commonwealth units train in those locations listed in Case <<17_32>>. When
in doubt as to unit size, five Replacement Points equals one battalion. The
schedule for Replacement Training is as follows:

[cols="2,3", options="header"]
|===
| Type of Replacement | OpStages of Training

| Gun Replacement
| One (Actually, not Training; more un-crating)

| Infantry Replacement
| Three

| Tank, AC, Recce Replacement
| Six
|===

*Note*: This has nothing to do with Commonwealth
training for Morale.

[#20_44]
*[20.44]* In essence, within the parameters of Case <<20_42>>, Trained
Infantry Replacement Points are usually trucked (if available) to the Front Line
after undergoing Training, where they are transferred to the unit of
assignation. Trained Tank, Gun and Recce Replacement Points may move on their
own, use Railroads (Commonwealth), etc.

[#20_45]
*[20.45]* Like other normal units, Replacement Points require Stores and
Fuel (if vehicles) when moving. Remember, five Replacement Points is the
equivalent of a battalion for all purposes. They can be assigned ammunition, but
this is pretty much a waste of supplies, given the maxims of Case <<20_42>>.

[#20_46]
*[20.46]* Replacement Points moving toward the Front for purposes of
assignment are considered Truck Convoys and move only in the Truck Convoy
Movement Phase.

[#20_47]
*[20.47]* Players should use the Replacement Point Availability and
Assignment Sheets for keeping track of what is happening with their Replacement
Points.

[#20_48]
*[20.48]* The cost in Capability Points to attach Replacement Points to
units is listed on the Capability Point Cost Summary (<<6_3>>) Replacement Point
units are considered as Assigned units for this purpose.

[#20_49]
*[20.49]* Replacement Points may be absorbed only during the
Reorganization Segment. They then acquire the assigned unit's cohesion,
breakdown and other levels.

[#20_5]
=== UPGRADING ARMORED CAR EFFECTIVENESS

At the beginning of the campaign, most Armored Car and Reconnaissance (Recce)
units were "light" in nature, using lightly armored cars, carriers, and AP
trucks mostly equipped with antipersonnel weapons. As the war progressed, this
equipment was often upgraded with the addition of light tanks and better-armed
cars and carriers.  This rule reflects that increase in effectiveness.

[#20_51]
*[20.51]* All armored reconnaissance and armored car (i.e., Italian ID
Code "ww" German ID Code "go" and Commonwealth ID Code "hh" thru "tt"
inclusive) units that arrive/deploy with an Anti-armor Rating of zero (even
those also possessing an Offensive Close Assault Rating of "3" — see Case
<<20_54>>) may be increased in effectiveness with the following exception. None
of the Commonwealth Player's Recce units assigned to Infantry Divisions (for
this purpose, the 18th Brigade of the 7th Australian Division is. considered a
division) may be upgraded (i.e., the 51st Recce Regiment of the 51st Highland
division could not be upgraded).

[#20_52]
*[20.52]* To upgrade an Armored Recce or A/C unit, the Player simply
adds one TOE Strength Point of certain types of tanks (as listed in <<20_53>>)
to the Recce or A/C units, remembering that the unit may never exceed its stated
TOE maximum.  Thus, he may add the TOE to replace a lost TOE Point, or he may
simply add the Tank TOE in and not increase the TOE Strength Points, if the
Recce or A/C unit is already at maximum level.

[#20_53]
*[20.53]* Commonwealth Players may use Stuarts to upgrade their Recce/AC
units. German units may be upgraded by adding Pz JJ TOE points.  Italian units
may be upgraded by adding M/11 or L6/40 Tank Points, or armored recce/armored
car Replacement Points.

[#20_54]
*[20.54]* An "upgraded" Recce or A/C unit's TOE Strength Point has an
Anti-Armor Rating of 1, instead of zero, and an Offensive Close Assault Rating
of 3, instead of 2.

[#20_55]
*[20.55]* No units may be upgraded until 1/39, at the earliest.

[#20_6]
=== AXIS PLANNED REPLACEMENTS

Italian and German Replacement Points enter the game from the Axis Replacement
Pool (<<20_66>>) as a result of direct planning by the Axis Player.

[#20_61]
*[20.61]* In the Axis Replacement Pool, the Axis Player will find the
maximum number of Replacement Points for each type of point for the entire
Campaign Game. (Each Scenario lists the maximum available for that Scenario, if
any). The Axis Player may never use more Replacement Points than are provided.
This is further limited by the maximum points available per turn, per type.

[#20_62]
*[20.62]* The Axis Player may bring in any number of Replacement Points
of any and all Classes during any one OpStage (see Case <<20_23>>) limited of
course by the pool restrictions. However, each Replacement Point is counted
against the Shipping Tonnage allowance for that Game-Turn (see Case 51.5). The
equivalent tonnage of each Point is given in the Pool Table. Thus, if the Axis
Player wishes to bring in 10 Italian Infantry Replacement Points, he would need
350 Tons of Shipping availability.

[#20_63]
*[20.63]* All Axis Replacement Points coming from the Axis Replacement
Pool must be Planned for at least two turns in advance. In other words, Axis
Planned Replacements for July, 1941 must be determined in the Naval Convoy
Arrival Phase of the 1/III Game-Turn of June, 1941. Replacement planned in
June III may arrive in any OP Stage Navel Convoy Arrival Phase of July I.

[#26_64]
*[26.64]* Replacement Points have priority in Shipping Space over any
type of supplies. The Axis Logistics Commander thus has to keep a close watch
(and tight rein) on what he is shipping at what time, as he rarely knows that
far in advance exactly how much shipping he will have available (see Section
<<51_0>>). Remember, Axis Shipping is subject to Commonwealth air Raid, so keep
aneye on Malta and the location of Commonwealth airfields.

[#20_65]
*[20.65]* Replacement Points may not be absorbed by units that have no
place for them, so remember to space your Replacements carefully.

[#20_66]
*[20.66] The Axis Replacement Pool Table*

(see Charts and Tables)

[#20_67]
*[20.67] Axis Replacement Point Type Limitations Chart*

(see Charts and Tables)

[#20_7]
=== COMMONWEALTH PRODUCTION

[#20_71]
*[20.71]* Most Commonwealth units and some of their Replacements arrive
via the Reinforcement Track. However, most -Replacements — mostly "drafts" and
transport — arrive somewhat randomly as mandated by the Commonwealth Production
Tables (<<20_78>>).

[#20_72]
*[20.72]* The Commonwealth Player must plan two months in advance
(unless specified in a given Scenario) for the arrival of Replacement Points via
Production. Thus, for Points required for August, 1942, the Commonwealth Player
must plan — using the Production Systems. — in the first Naval Convoy Schedule
Phase of July, 1942. However, the Commonwealth Player always uses the
Production Table for the month (one months in the future) in which he wishes his
units to arrive — not the month in which he is consulting it.

[#20_73]
*[20.73]* The Commonwealth Production System functions like the Axis
Pools except for Infantry and Truck Points. The Player uses a random dice roll
to determine what Infantry and Truck Points he receives per turn, depending upon
the date of arrival.

[#20_74]
*[20.74]* Replacement Points scheduled for any given turn must be
divided among the OpStagesas evenly as possible. This refers to the total Points
for all types. Thus the Commonwealth Player may bring 10 Medium Trucks in one
OpStage and 10 Infantry Points in the next.

[#20_75]
*[20.75]* Replacement Points listed in the Reinforcement Schedule arrive
in addition to any Production. The Commonwealth Player has no Shipping Problems;
his Replacement Points simply arrive.

[#20_76]
*[20.76]* All Planned Replacements arrive in any hex in Cairo or
Alexandria. They, like other Replacements, must undergo Training (see Case
<<20_43>>).

[#20_77]
*[20.77]* The Commonwealth Player may “upgrade”? his Infantry units in
much the same fashion as his Recce/AC units. This applies only to infantry units
with a 1/2 (Off/Def) Close Assau]t Rating. The Commonwealth Player simply
uses one Infantry Replacement Point for each TOE Strength Point in the unit he
wishes to upgrade. Furthermore, the Commonwealth Player must upgrade a// TOE
Points in that unit at the same time. The Replacement Point used is absorbed to
increase the Assault Rating to 2/2; it does not increase the TOE Strength
itself. No upgrading may take place before the July 1/I, 1942 Game-Turn,
which means they may be "planned" in June, 1942. Infantry Replacement
Points scheduled for upgrading need not be Trained. Once upgraded additional
replacements assigned to that unit only require 1 Infantry Replacement Point per
TOE Point, not 2 (1&1) Infantry Replacement Points.

[#20_78]
*[20.78] Commonwealth Production System*

(see Charts and Tables)

[#20_8]
=== COMMONWEALTH MANDATORY WITHDRAWALS

During the Desert Campaign, Commonwealth units were often withdrawn and sent
elsewhere (Crete, Greece, Syria, Iraq, Cyprus, Sudan, etc.).  This is reflected
in the Commonwealth Reinforcement Schedule, which tells the Commonwealth Player
if, when, and how many units must be removed from the game.

[#20_81]
*[20.81]* Withdrawals are listed in the Reinforcement Schedule. They are
listed as either actual units or as types of units (e.g., "Withdraw any two
Armor Brigades").

[#20_82]
*[20.82]*. When a Withdrawal is listed by type, the unit chosen for
Withdraw! must be at 75% maximum TOE Strength (at least), or, if no units are up
to that level, the highest TOE Strength-level unit of its type available.

[#20_83]
*[20.83]* Units to be Withdrawn must be moved to Cairo or Alexandria on
or before the Game-Turn or Stage they are to be withdrawn. If they are not
present or at required TOE Strength (<<20_75>>) by that time, they are eliminated.
(This is a play mechanism to forestall procrastination.) Units so eliminated may
not return (as many Withdrawls do, later in the game).

[#20_84]
*[20.84]* Once the units have reached Cairo or Alexandria, they are
simply removed from play.

[#20_85]
*[20.85]* If a unit scheduled for Mandatory Withdrawal is less than 75%
TOE Strength, it must be brought up to that level by Replacement Points before
Withdrawal Date (see Case <<20_82>>) or an equivalent substitute unit of similar
type that is at least at 75% TOE strength.

[#20_9]
=== VOLUNTARY COMMONWEALTH WITHDRAWALS

Throughout the Campaign, the Commonwealth was under great military and political
pressure to support a wide variety of activities in such places as Cyprus,
Sudan, Iraq, etc. Case <<20_8>> discusses large mandatory troop withdrawals. In
addition, the Commonwealth, during lulls in action, would often send several ad
hoc battalions to duty elsewhere; these units often shuffled back and forth in
almost random fashion, dependent on the situation. It would be folly to list all
such movements and even sillier to require a Player to follow them.  (We are not
too happy with Mandatory Withdrawals, but such unit absences on a large scale
must be accounted for.) The Commonwealth Player therefore has the option to
withdraw small forces at any time, thereby gaining Victory Points.  Victory
Points are given because these forces would aid campaigns elsewhere, put
additional pressure on the enemy, etc. Returning voluntarily withdrawn units
penalizes the Commonwealth Player. See the Campaign Game Victory Conditions.

