[#64_0]
== SCENARIO GROUP
FIVE: THE CAMPAIGN
FOR NORTH AFRICA

[#64_1]
=== INTRODUCTION

If you have gotten this far you will by now have
surmised that the full campaign game of CNA
is,far and away, the most ambitious undertaking a
gamer could ever want to get involved with. The
campaign game requires not so much a commitment in time (which is always relative), but more
so a commitment to planning and foresight. A
campaign game will need at least ten players,
perhaps more. Ideally, each land division should
have a commander, plus an Air Commander anda
Logistics Commander. On top of this should be
one Player as Supreme Commander. This means a
lot of players, and, again, this is the ideal situation. The fewest number of players would be three
to a side. Lastly, it would be hard to underestimate the amount of paperwork and planning
that are involved in a campaign game. Keeping on
top of the situation is half the battle . . . and more
than half the fun. And speaking of fun, the campaign game can be a lot of fun. If you are interested in a challenge, interested in wrestling with
the problems of organizing and running a campaign, and if you simply want to experience the
complexities of. modern warfare at all levels, you
will get much satisfaction from CNA.

[#64_2]
=== SCENARIO LENGTH

There are two campaign game scenarios in CNA.
The first covers the entire war in Northeast Africa
and begins in the third week of September, 1940
(.e., the Italian Offensive, lst OpStage of GameTurn 1). The "shorter" campaign begins with the
arrival of General Erwin Rommel and the
Deutsches Afrika Korps during the fourth week of
March, 194] (i.e., the Desert Fox, 3rd OpStage of
Game-Turn 26). Both campaign games end with
the completion of the third OpStage of GameTurn 111.

[#64_3]
=== INITIAL DEPLOYMENTS

If the entire campaign is being played, the Players
use the information provided in Section <<60_0>> for
the initial placement and distribution of their land,
sea, and air forces, supplies and construction. If
the Players are starting the campaign with the arrival of Rommel, the information in Section <<61_0>>
is used.

[#64_4]
=== INITIATIVE

The Players determine Initiative using the information provided in Section <<60_0>> or <<61_0>> depending
upon where they are starting their campaign. Iniative is determined normally once the restrictions
in the appropriate section expire.

[#64_5]
=== SPECIAL RULES/ADJUSTMENTS

[#64_51]*[64.51]* There are no restrictions on normal game
actions (i.e., Raids on Rommel, the Commonwealth Fleet, etc. may be performed as per the
appropriate rules).

[#64_52]*[64.52]* The Axis Player's Malta Air Availability
is determined using the appropriate campaign
game row on the Axis Strategic Airforce Commitment Chart.

[#64_53]*[64.53]* If the shorter campaign game is being
played the Axis Replacement Pool must be adjusted as follows:

A. German Production Chart: No change.

B. Axis Truck Production Chart: The total trucks
the Axis Player may bring in are reduced to 800
Light, 2400 Medium and 500 Heavy.

C. Italian Production Chart: One-half of all
replacement points (rounding fractions up) that
could be planned up thru (i.e., including) GameTurn 24 are no longer available with the following
exception: the Axis Player still has 60 CV L.3 &
CV 33/35 tank replacement points available.

[#64_54]*[64.54]* If the shorter campaign game is being
played the Commonwealth Production System
must be adjusted as follows:

A. Commonwealth Truck Production Table: No
change.

B. Commonwealth Infantry Proudction Table:
No change.

C. Commonwealth Production Chart: The
replacement points listed below are reduced to (not
by) those numbers, all other replacement points
are unaffected:

Item Number
Armored Car/Armored Recce 75
Light Anti-air 70
25-pounder artillery 230
2-pounder AT guns 50
Mk VI Light tanks 5
A9 crusiers 3
AJ0 crusiers

A13 crusiers

Matildas 20

[#64_6]
=== ADR & LOGISTICS GAMES'
ABSTRACTIONS

Why anyone would play a campaign game without
the Air and/or Logistics Game(s) is beyond me.
However, the Players should pick their start point
(Italian Offensive or Desert Fox) and use the rules
in the appropriate section(s)  <<32_0>>, <<47_0>>, <<58_0>>) and
the abstracted set-up for that scenario group and
the replacement point adjustments in Case <<64_5>>.

[#64_7]
=== VICTORY CONDITIONS

It would be hard to imagine anything more exasperating than playing a game for five years, getting to the end, and finding out that you have lost
by one point or two hexes, or something of that ilk
Victory conditions for a game of this size and
scope are almost meaningless: survival itself is a
victory. However, you have to have some sort of
objective, and the Designer has to make some sort
of decision. Our decision here is to use Victory
Conditions that compare to what actually happened, not what each side needed to do. The reason
for this is that the Axis situation was a foregone
conclusion by 1942, what with the pending Allied
invasion of Africa from the West. Thus, the Axis
had to take Alexandria (and the Delta) or else be
caught in the desert between two armies. And
Alexandria is thus the Axis objective, historically.
As for gaming, it becomes a matter of points, or
who can hold onto what.

[#64_71]*[64.71]* If the Axis Player occupies all hexes of
Alexandria and Cairo for one full Game-Turn,
and sucn occupying units can trace a line of supply
(i.e., convoy route) back to a Supply Dump which
in turn can be supplied from Tobruk or Tripoli in
any way, and that line is 90 movement points by
truck or less, the Axis wins the game—regardless
of the turn or date. Failing that, we count points,
as below.

[#64_72]*[64.72]* Starting with the first OpStage of GameTurn 35, if there are no Axis Combat units that can
trace a line of supply of 60 Movement Points
(Truck) to a Supply Dump and thence to Tobruk
or Tripoli as per case <<64_71>> , game-map, the Commonwealth wins the game automatically. This
does not include air or coastal shipping units.

[#64_73]*[64.73]* Failing the above two cases, players
receive points for doing (or not doing) certain
things. The first of these points are Geographical
Occupation Points. The Player occupying the
given cities/villages gains the points listed. Occupation for these purposes means having a combat unit of at least 1 TOE Strength in the hex. That
combat unit, at the end of the game, must have
enough Stores and Water for one Week, and
enough Fuel and Ammunition to fire its weapons
three times and move 20 CP's. Any units failing
these "tests" do not occupy for victory conditons.

City/Village Axis V.P.'s C'wlth V.P.'s
Mersa.Matruh 100 10
Sidi Barrani 50 10
Siwa 20 10
Jalo 10° 20
Giarabub 15 10
Bardia 100 50
Sollum 25 - 10
Tobruk 200 100
Derna 25 50
Benghazi 75 100

[#64_74]*[64.74]* The next series of points are replacement
Victory Points. Each Player receives one point for
each unused Replacement Point allotted to him in
his Production Charts, not including planes
and/or Trucks and, for the Commonwealth
Player only, Infantry. Thus, if the Commonwealth Player had a total of 35 Crusader I

3/7

38

Tank Replacement Points available for the game,
but he uses only 18, he gains 17 points.

[#64_75]*[64.75]* The final type of Victory Points apply
solely to the Commonwealth Player: Withdrawal
Points. (Unit, not Drug). These apply to battalions
withdrawn from the game, other than those
Withdrawn via The Reinforcement Track. These
are voluntary withdrawals, not mandatory
withdrawals. They are earned as follows:

A. For every combat battalion (not company) or
battalion-equivalent of infantry, armour, artillery or anti-tank guns (not AA) that is at
least 75% TOE Strength that is Withdrawn
from the game the Player receives 4 point for
each week that unit is gone, to a maximum of
three points per unit. To be Withdrawn a unit
must start the Stage in Alexandria or Cairo.

B. Every time that a battalion withdrawn under
A. above is returned to the game,the Commonwealth Player loses two points. A unit
voluntarily Withdrawn and then returned to
the game may not be Withdrawn until six
months from the date of return. (This may
not be entirely accurate, but it will stop
players from doing the One-Point Two Step,
shuffling a single unit in and out to get one
point).

[#64_76]*[64.76]* The levels of Victory are as follows.
Again, anyone who actually finishes this game can
consider himself a winner (much as the soldier who
fights two-three years does when he survives.)
Questions about the balance of the campaign
scenario received before 1981 will be considered
with the seriousness which they deserve. The
following schedule is consulted after both sides
total their points, comparing the totals as a ratio of
most to least.

Ratio Result
Even (1 to 1) Draw (My God, what a waste of
time!)
Better than 1-1,
up to1%-1 Marginal Victory
Better than 1%-1
up to2%2-1 Decisive Victory
Better than
2-1 A Smashing Victory
