[#63_0]
== SCENARIO GROUP FOUR: EL ALAMEIN

[#63_1]
=== GENERAL DESCRIPTION

There are two scenarios which can be played from this scenario Group. The first
is a short scenario in which the Axis Player has one week (one gameTurn) to try
to break through the Commonwealth lines and reach Alexandria (a relatively
impossible task). The second scenario is one of survival: can the Axis army
survive the end of the campaign intact? For those familiar with El Alamein they
will realize that both scenarios are, militarily (and in terms of game-playing)
quite stultifying. They are included for historical reference, mostly.
Playtesting proved them to be as equally dull as their gaming predecessors. The
first scenario has the advantage of being remarkably short; the other scenario
is for those who like to retreat or chase fleeing troops.

[#63_2]
=== SCENARIO LENGTH AND
DURATION

Both scenarios begin with the Ist OpStage of Game-Turn 1OZ. "The Last Chance"
Scenario ends with the completion of the 3rd OpStage of Game Turn 102 lst
OpStage of Game-Turn 111. "The Long Retreat" ends at the completion of the
December 3/IV, 1942 Game-Turn. "The Last Chance" should take about ten hours
to play, excluding set-up; "The Long Retreat" should take from 50to 100 hours.

[#63_3]
=== COMMONWEALTH FORCES

[#63_31]*[63.31]* Commonwealth Land Forces Deployment

Initial

(Hex: Units)

E 3101: 9th Aus Div (Det: 24 Aus Bde; Att: 40 RTR 23/8)

Trucks: 30 Light, 55 Medium, 15 Heavy.

E3001: 24th Aus Bde (9 Aus)

Trucks: 5 Light, 25 Medium, 6 Heavy.

D 3033: S5ist Inf Div (Att: 50 RTR 23/8).

Trucks: 40 Light, 70 Medium, 21 Heavy.

E 2901: nd New Zeland Div (2nd NZ Cav is now TOE Strength of 5 Recce Points and
6 Stuart tank Points; Less: 4 NZ Bde; Att: 9th Armored Bde 10; Att: 3 Hus, 14th
Sherwood Forresters 1)

Trucks: 30 Light, 90 Medium, 20 Heavy.

E 2801: Ist South African Div (Less: 50 SA Bde; Assg: 3 SA Bde #SA; in its
place#; ATt: 8th RTR #1 Army#, 1st SA Field Arty #2 SA#, Die Middelandse MG Regt
# SA#, and 2nd Botha #5/1SA )

Trucks: 35 Light, 85 Medium, 25 Heavy.

E 2701: 5 In Bde (4 Jn; Less: 1 Royal Fusilier and 4/6 Rajp Rifles; Assg: 1/4
Essex* and 3/10 Baluchies in their places); 6th Rajput Rifles MG Bn; Ist Field
Arty Regt (4 Zn); 149th AT Regt; 11th Field Arty Regt; 32nd Field Arty Regt;
57th Light AA Regt HQ: 4th In Div (Less: 11 In Bde, 31st Field Arty, and Central
In HOrse R; Det: 5th and 7th In Bdes and ist Field Arty).

Trucks: 10 Light, 25 Medium, 10 Heavy.

E 2601: 7th In Bde (4 In; Less: 4/11 Sikh; Assg: 1/2 Gurkha Rifles in its place)
and 161st In Motor Bde (consists of: Ist Argyll & Sutherland 16/17, 1/1 Punjab
Regt, 4/7 Rajputanis /1/4 In).

Trucks: 5 Light, 25 Medium, 5 Heavy.

2501: 50th Inf Div (Less: 150 Bde, 2nd Chesire MG Bn and 72 Field Arty; Assg:
Greek Bde and 111th Field Arty Regt in place of the Inf Bde and Arty Regt
respectively; Att: 154th Field Arty Regt, 102nd AT Regt 2Spt/2 and 34th Light AA
Regt).  Trucks: 35 Light, 65 Medium, 21 Heavy.

E 2302: 7th Armored Div (Consists of: 4th Armored Bde #consists of 4/8 Hus**,
Royal Scots Grays (8/10) and IKRRC (7 Spt/7); 22nd Armored Bde consists of 1 RTR
(7/7), 5 RTR 3/2), 4 CLY (22 Amr Bde), and 1 Rifle Bde (2/2); 11th Hus r; 7; TOE
Strength of 83 RHA Which now is considered a regular artillery unit; Possesses 6
TOE Strength Points of 25Ibrs; 4th Field Arty Regt; 97th Field Arty Regt20/10
In; 65th AT Regt; 15th Light AA Regt; AH: 2nd Derby Yeomanry R, 8; Strength of
6; 44th Recce Regt 44. Trucks: 75 Medium, 40 Heavy.

E 3005: lst Armored Div (Consists of: 2 Armored Bde Less: Ist RflBde, 7th Motor
Bde 7; Which consists of: 2nd Rifle Bde (7Spt/7), 7th Rifle Bde (23/8) and 2nd
KRRC (/Spt/J), 2nd RHA #Spt/2, 4th RHA /7Spt/7, 11th RHA self-propelled counter,
78th Field Arty, 76 AT RegtSp?t/J, 1st Royal Northumberland Fusiliers MG Bn,
42nd Light AA, and 12 Lancers R; /Spt/J; Att: An ad hoc Bde—level formation
known as "Hammerforce'; consisting of: 4/6 SA Armored Car Regt*** with a TOE
Strength of 7, 146th Field Arty, 73rd AT Regt and 56th Light AA Regt).

Trucks: 10 Light, 90 Medium, 30 Heavy.

E 3007: 8th Armored Div (Det: 40 RTR and 50 RTR of the 23rd Armored Bde, 2nd
DerYoe R; Less: 24th Armored Bde, 7th Rifle Bde of the 23rd Armored Bde); 121st
Field Arty.

Trucks: 5 Medium.

E 2805: 10th Armored Div (consists of: 8 Amr Bde 10; Less: SctsGray; Assg: 3rd
RTR (//2; in its place) and Ist Buffs (1), 24th Armored Bde [8], 133rd Inf. Bde
[44]. lst Royal Dragoons R, 1 RHA, 104 RHA, 98sth Field Arty, Sth RHA
selfpropelled counter, 84th AT, and 53rd Light AA).

Trucks: 75 Medium, 40 Heavy.

E 2904: lst Army Tank Bde (Det: 8 RTR)

Trucks: 5 Medium.

E 2401: 44th Inf Div (Det: 44th Recce; Less: 133Inf Bde; Att: 53rd Field Arty).
Trucks: 20 Light, 55 Medium, 6 Heavy.

Within one hex of E 2403: Ist Free French Bde

Trucks: 10 Light, 35 Medium, 5 Heavy.

2nd Free French Bde. Trucks: 5 Light, 12
Medium, 1 Heavy.

Within two hexes of el Alamein

(E 3002): 14th Light AA; 16th Light AA; 27th Light AA; 88th Heavy AA; 94th
Heavy AA.  Trucks: 5 Medium.

2ist In Bde (0 In; consists of 1/6 Rajput Rifles 11/4 In, 3/7 Rajputama Regt 61
In Mtr Bde and 2/8 Gurkha Rifles); 7th Medium Arty Regt; 64th Medium Arty; 69th
Medium Arty Trucks: 10 Light, 25 Medium, 7 Heavy.  *This is a British unit whose
counter bears the Indian units' coloration.

**Formation created by combining the 4th and 8th Hussars. Use the counter for
the 8th Hus (7/7).  The unit's max TOE Strength is still 10.

***Formation created by combining the 4th and 6th SA Armored Car Battalions. Use
either counter. The unit's max TOE Strength is now 8.  Certain of the above
units may have their equipment and TOE upgraded, using the rules sections for
such as references.

A. Each non-motorized infantry battalion (CPA of 10) may add 1 TOE of 6-pounder
AT guns; and

B. Each motorized battalion of infantry (10+ CPA) may add 2 TOE of 6-pdr AT
guns.

C. 40% (rounded up) of all AT units may replace their 2-pdr AT guns with 6-pdr
AT guns.

D. Armored car (not armored recce) units may be upgraded as per the rules for
such. (It is not necessary to use Replacement points; simply upgrade them as if
they had used Replacement Points)

E. Any artillery units with 18-pounders or 18/25 pounders may replace them with
25 pounders.

[#63_32]*[63.32]* Commonwealth Tank Battalion Composition

The following tank battalions are listed as to their assigned parent formatin(s)
for this scenario and their starting compositions, in TOE Strength Points, if
they differ from their listing on the OA Sheet. Parent

Tank Battalion Formation(s) Composition

40 RTR 23/8 8 Valentines

46 RTR 23/8 10 Valentines

50 RTR 23/8 9 Valentines

8 RTR 1 Army* 10 Valentines

3rd Hussars 2 Grants, 2 Shermans, 3 Crusader T's

Ryl Wi Yeomanry 9/-t 3 Grants, 2 Shermans, 3 Crusader
I's

Warwick Yeo 3 Grants, 3 Shermans, 3 Crusader
Il's

9th Aus Div Cav 9 Aust 3 Crusader II's, 1
Stuart 6 ID Code
oe 1 1' >

Royal Scots Greys 4/7 4 Stuarts, 3 Grants

4/8 Hussars 4/7 9 Stuarts

1RTR 22/7 4 Stuarts, 5 Grants

5RTR 22/7 4 Crusader II's,
5 Grants

4CLY 22/7 6 Crusader II's,
2 Grants

Queens Bays 7 Shermans,
3 Crusader II's

9th Lancers 2/1 6 Shermans,
4 Crusader II's

10th Hussars 2/1 5 Shermans,
5 Crusader II's

7th Motor Bde HQ 1 Churchill

3 RTR 8/10 3 Crusader III's,
2-Shermans,
3 Grants

Nottingham Yeo 8/10 3 Crusader III's,
2 Shermans,
4 Grants

Staffordshire Yeo 8/10 3 Crusader III's,
2 Shermans,
4 Grants

41 RTR 24/10 3 Crusader III's,
6 Shermans

45 RTR 24/10 3 Crusader III's,
6 Shermans

47 RTR 24/10 3 Crusader III's,
7 Shermans

42 RTR 1 Army 10 Scorpions

44 RTR 1 Army 10 Scorpions

*Starts attached to the Ist SA Div.

{Starts attached to the 2nd NZ Division.

£This armored unit is a tank battalion for these
scenarios.

[#63_33]*[63.33]* Commonwealth Air Strength

[cols="1,1,5"]
|===
|Location |SGSU's (Type and #'s Available) |Planes (Type and #'s Available)

|Burg el Arab (E 3109)
|3
|Spitfire VB (18); Hurricane IIA (12); Tomahawks (6); Marylands (4); Baltimores (4)

|Wadi Natrun (E 2418)
|1
|Marylands (12)

|Deversoir
|*
|Mitchell II (39)

|Amiriya Air Complex (see _Air Facilities_ below)
|28
|Boston III (48); Baltimore II (24); Baltimore III (24); Tomahawk (16); Kittyhawk I (56); Kittyhawk II (91); Kittyhawk III (39); Hurricane IIB (48); Hurricane IIC (64); Hurricane IID (32); Hurricane IIE (16); Spitfire VB(48)

|Idku (E 3817)
|2
|Beaufighter IC (16); Beaufighter VIF (16)

|Abu Seier
|*
|Wellington IC (32)

|Jebel Hamzi (E 2024)
|2
|Wellington IC (32)

|Kabrit
|*
|Wellington IC (16); Wellington II (16)

|Degheila (E 3512)
|2
|Albacores (24)

|Ismailia
|*
|Hudsons (32); Bombays (22)
|===

*=SGSU's not needed; off-map base.  All Commonwealth Planes are Refitted!

Pilots Available

Rating Number Available
Four 1

Three 5

Two 22

One 31

Air Facilities

The Commonwealth Player places six Airfields within one hex of Amiriya (The
Amiriya complex).  He has an Airfield at Burg el Arab (E 3109), Alexandria, and
Cairo. He has a Landing Strip at Wadi Natrun (E 2418). The Commonwealth Player
may also place 1 additional Airfield and 3 Landing Strips, 1 Flying Boat Basin
and 1 Flying Boat Alighting Area anywhere on Map E, but not within five hexes of
an enemy unit, or in the Qatarra Depression. The Commonwealth Player's seven
off-map facilities are all undamaged.

[#63_34]*[63.34]* Commonwealth Trucks Second-Third Line Trucks (In Convoy):

Anywhere on gamemapsD&E: 200 Light, 725

Medium, 225 Heavy

The Commonwealth Player receives 100 Medium and 60 Heavy trucks for distribution
among his Air Facilities.

[#63_35]*[63.35]* Commonwealth Supply

The Commonwealth Player receives 10 Supply Dumps plus 3 Dummies, for a total of
13 Dumps.  As many as five of these dumps may be placed within one hex of the
Front Line (i.e., any hex east of and adjacent to an Axis unit.) One dump each
must be placed at el Alamein, E2805, and E2403.  The remaining dumps may be
placed anywhere on Map B£, but not within one hex of the front.

Front Line Dumps receive (amongst them) 2500 Ammo points, 2000 Fuel Points, 1500
Stores, and 1500 Water Points. The other dumps split (in any way the Player
wishes) the following: 1000 Ammo Points, 3000 Fuel Points, 500 Stores, 2000
Water Points.

Remember, there is unlimited supply available in Alexandria and Cairo. All
Trucks not carrying men may be loaded with supplies as the Player wishes. The
Commonwealth has no temporary repair facility. Alexandria and Cairo are Major
Repair Facilities.

[#63_36]*[63.36]* Commonwealth Fleet

The Commonwealth Player receives the following warship counters in Alexandria: 2
Heavy Cruisers, 3 Light Cruisers, 4 Destroyers.

[#63_37]*[63.37]* Malta

All Air Facilities are operating at full capacity.
The following planes are available in Malta:

[cols="3,1,1"]
|===
|Type |Number |Refitted

|Wellington V
|5
|5

|Baltimore I
|4
|4

|Baltimore II
|3
|3

|Beaufighter IC
|12
|5

|Beaufighter VIF
|8
|6

|Spitfire VB
|54
|33

|Spitfire VC
|18
|10

|Hurricane IIC
|8
|8

|Albacore
|3
|3

|Swordfish
|3
|3
|===

48 AA Points are Available for placement as desired, The Following Pilots are
available:

Rating Number
Three 1
Two 5
One 5

[#63_38]*[63.38]* Reinforcements and Replacements

All Reinforcements are taken as per the Reinforcement Schedules. Ail
Replacements are taken normally, except that all available points are reduced to
10%, rounded up, of their listed maximum.  However, the Infantry and Truck
Production Tables' output are unaffected. In any case, no Replacement points may
arrive before the first OpStage of Game-Turn 105, and these may be planned
before the scenarios starts. Replacements for the 106th Game-Turn may also be
planned at the start of the scenario. There are no Replacements or
Reinforcements for the "Last Chance”' scenario.

[#63_4]
=== AXIS FORCES

[#63_41]*[63.41]* Axis Land Forces Initial Deployment

(Hex: Units)

D3328: 90th Light Div (Det; 580 Aufklarungs Bn {R]); Trucks: 10 Light, 40
Medium, 7 Heavy

D3132: 15th Panzer Div (Less: 200th and 104th Regts; Det: 33 Recce; Assg: 2 MG
Bn /5 Le); Trucks: 15 Light, 40 Medium, 10 Heavy.

D3032: 164th Light Div; Trucks: 5 Light, 45 Medium, 5 Heavy.

D2931: 3 Aufklarungs Bn (R; 2/); Trucks: 2 Light.

D2831: 21st Panzer Div (Less: 2nd MG Bn; Assg: 200th Rifle Regt /15]; which
begins the scenario detached); Trucks: 7 Light, 20 Medium, 10 Heavy.

D2733: Ramcke Bde; Trucks: None.

D2630: 104th Rifle Regt (Now assigned to the 21 Panzer); Trucks: 5 Light, 25
Medium.

D2532: 33 Aufklarungs Bn (R; 15).  12431: 580th Aufklarungs Bn (R; 90 Le);
Trucks: 5 Light.

D 3327: 136th GGFF Div (1) Trucks: 25 Light, 15 Medium.

D 3326: 101st Trieste Div (I; Det: 21 Arty Regt; ATT:III(M) Trucks: 5 Light, 55
Medium, 5 Heavy.

D 3325: 16th Pistoia Div (1) TRucks: 30 Light, 30 Medium.

D 3232; 133rd Littorio Div (T; Det: 12th Bersaglieri Regt; Less: X(M) and XII(M)
tank Bns and V and VI Arty Bns self-propelled: Assg: in their places,
respectively [V(M) and LI(M) tank Bns and DLIV and DLVI Arty Bns self-propelled)
Trucks: 25 Light, 25 Medium, 6 Heavy.

E 3133: 12th Bersaglieri Regt (I; Littorio( Trucks: 6 Light, 20 Medium.

D 2933: 102nd Trento Div (I; Det: 7th Berg Regt) Trucks: 68 Medium, 7 Heavy.

D 2932: 7th Bersaglieri Regt (102 Trn) Trucks: 20 Medium.

D 2833; 25th Bologna Div (1); 21st Arty Regt (10/ Tst) Trucks: 12 Light, 60
Medium, 10 Heavy.

D 2732: 27th Brescia Div (1) Trucks: 10 Light, 65 Medium, 7 Heavy.

D 2632: 132 Ariete Div (T; Less: VII(M) tank Bn; Assg: LII(M) tank Bn in its
place, V and VI Arty Bns self-propelled; Littorio; Att: XIII(M) tank Bn; The 132
Arty Regt now contains 3 TOE Strength Points of 105/28 guns and 2 TOE Strength
Points of 90mm Flak guns heavy AA Trucks: 25 Light, 45 Medium, 10 Heavy.

D 2533: 185th Folgore Div (I) Trucks: 30 Light, 30 Medium.

D 2432: 17th Pavia Div (I) Trucks: 10 Light, 65 Medium, 7 Heavy.

Anywhere on Map D: Italian XXIV Cp Arty; XXVI Cp Arty; 1/2AR Arty Bn; 2/2AR Arty
Bn; 3/2AR Arty Bn; 4/2 AR Arty Bn; RECAM (R); III/133 Fanterie Inf Bn I(L) and
II(L) tank Bns.  German: Sonderverband 288 Regt (I); 707th and 708th Heavy
Weapons Coys; 13th Coy of the Bandenburg Regt (I).

Anywhere on Map A thru D: Any four Oasis Coys and the 778th Naval Engineers. All
remaining unassigned German independent (i.e., no parent unit) artillery and
anti-aircraft units. This includes the 1st and 2nd African Arty HQ's and the
155th and Arko 104 Arty Hq's and their subsidiary units.

Modifications to units strength: All Axis Infantrytype units are reduced to 2/3
(round fractions up) of their maximum TOE Strength.

[#63_42]*[63.42]* Tank Deployment

The following are exceptions to the OA Chart

[cols="2,5"]
|===
|Unit |Strength

|I/5 Panzer
|2 PzII; 4 PzIIIH; 1 PzIIIE; 4 PzIIIJ Specials

|II/5 Panzer
|2PzII; 2PzIIIE; 4PzIIIH; 4PzIIIJ Specials; 1 PzIVE

|I/8 Panzer
|1PzII; 4 PzIIIH; 5 PzIIIJ Specials; 3 PzIVF^2^ Specials

|II/8 Panzer
|1PzII, 3PzIIIH, 1PzIII6,3PzIII-JSpecial, 1PzIV6,3PzIvF^2^

|LII/(M)
|6 M/13/40's

|VIII/M
|6 M/13/40's

|I/(L)
|6 L6's

|II/(L)
|4 L6's
|===


Broken down in Tobruk's Repair Facility: 3
PzHIH's; 1 PzIVD.

[#63_43]*[63.43]* Axis Air Strength

German Planes

The following planes may be located at any air
facility in Africa. Planes not refitted may not be
readied until the second OpStage of the scenario
(they are not ready for the first OpStage).

[cols="3,1,1"]
|===
|Type of Plane |Total Avail |Refitted

|Ju87D
|70
|44

|Me Bf109F
|83
|40

|Me Bf109G
|90
|50

|Me Bf109E
|16
|6

|Me Bf110C
|16
|10
|===

SGSU's available: 21

Pilots Available:
Rating Available
Four 4

Three 4

Two 11

One 16

The Axis Player has available in Crete the following planes: 75 Ju88's (60
refitted) and 15 Hel11's (10 refitted). No SGSU's or pilots are needed.

.Italian Planes
[cols="1,1,1"]
|===
|Type of Plane |TotalAvail |TotalReady
|Cant.Z.1007 |14 |14
|Fiat CR42 |125 |75
|Fiat G.50 |12 |0
|Macchi C.200 |58 |40
|Macchi C.202 |139 |84
|S.M.79 |34 |24
|===

SGSU's Available: 27

Pilots Available:

Rating Available

Four 1

Three 3

Two 20

One 18

Air Facilities

The Axis Player has nine Airfields, eight one Flying Boat Basin and One Flying
Boat Alighting Area. He may place these wherever he wishes, on Maps A-D.

[#63_44]*[63.44]* Axis Trucks

Second-Third Line Trucks (In Convoy):

May be placed anywhere on game maps A thru D: 115 Light, 350 Medium, 75 Heavy.

The Axis Player receives 50 Light and 100 Medium trucks for distribution among
his Air Facilities.

[#63_45]*[63.45]* Axis Supply

The Axis Player receives ten Supply Dumps, three of which are Dummies. At least
five of those dumps must be placed on Game-Maps A, B or C.  The other five may
be placed on game-map D (or A-C, if desired). In addition, the Axis Plyaer
receives supplies at several cities/villages, as listed below. He may use Supply
Dumps for those villages listed, in addition to those given to him.

.Location
[cols="1,1,1,1,1", options="header"]
|===
|Location |Ammo |Fuel |Stores |Water
|Map D Dumps* |2700 |4000 |1500 |800
|Other Dumps* |500 |500 |500 |500
|Ghazal(D3328) |200 |500 |0 |500
|Mersa Matruh |500 |1500 |250 |500
|Sidi Barrani |200 |500 |0 |500
|Bardia |300 |1000 |250 |0
|Tobruk |800 |3000 |250 |0
|Derna |200 |500 |0 |500
|Benghazi |300 |1000 |250 |0
|Marble Arch |200 |500 |250 |500
|===

*No one dump may contain more than 33% of the total supplies of each type
listed.

Each Airfield has 150 Ammo points, 350 Fuel points, 25 Stores and 50 Water
except Tripoli/Tunisia.

Each Strip, Flying Boat Basin/Alighting Area has 20 Ammo points, 25 Fuel points,
10 Stores and 10 Water Points.

Trucks may be assigned to the dumps, cities as needed fromthe 2nd-3rd Line
Trucks available.

The Axis has a Major Repair Facility in Tobruk, and Temporary Repair Facilities
in Bardia and Mersa Matruh.

Axis Coastal Shipping (all units/tonnage) is available. Ships may be placed at
any port between Tobruk and Tripoli.

[#63_46]*[63.46]* Axis Mediterranean Air Force Deployment

The Axis Player may transfer 10% of his available force to Italy or Sicily but
no more. He may not have more than 10% of his air power in Italy or Sicily.
Strategic air attacks against Malta may be made only in the Long Retreat
scenario (see 44.41).

[#63_47]*[63.47]* Replacements and Reinforcements

For the "Last Chance" Scenario, ignore all Reinforcements and Replacements.

For the "Long Retreat" scenario, Reinforcements as normal. As for Replacements,
Axis Player must reduce all his Points Available to 5% (rounded down) of what is
listed in the Axis Replacement Pool. Moreover, any Replacement Points sent must
be sent to Tripoli and must stay there, unless the following occurs: If the Axis
Player still holds Tobruk, Bardia, or Mersa Matruh by the third OpStage of
Game-Turn 105, then 25% of Replacement Points in Tripoli may be released the
following OpStage. After that, 25% of all available Replacement Points (by type,
and rounded up) may be released in the first OpStage of Game-Turn
108.

This rule takes into effect the Allied Landings (feared and actual) to the West,
and the historical fact that almost all manpower at this time was being diverted
to Tunisia.

[#63_48]*[63.48]* Upgraded Axis Equipment

A. All eligible Axis armored car and armored recce units may be upgraded as per
rules for such.  It is not necessary to use Replacement Points; simply upgrade
the units as if they had used Replacement Points.

B. Any two of the four following Italian infantry divisions may have their
assigned artillery units' OA Sheet listing of two or three 75mm heavy antiair
TOE Strength Points replaced with two 90mm heavy anti-air TOE Strength Points:
16 Pistoia, 17i Pavia, 25 Bologna and 27 Brescia.

C. The following German anti-tank units have their weaponry upgraded replacing
their OA Sheet listing: The 605th SP of the 21st Panzer has 6 TOE Strength
Points of Marder SP anti-tank guns. The 3.7mm anti-tank guns in the 15th and
21st Panzers are replaced by the same number of 5cm guns. The Scm guns in the
15th and 21st Panzers and 90th Light are replaced by the same number of <<7_62>>
Pak(R) guns.

D. Any four eligible Italian brigade-level HQ's are ad hoc anti-tank batteries
each with 4 TOE Strength Points of Italian AT guns. Any two eligible German
brigade-level HQ's are ad hoc antitank batteries, each with 4 TOE Strength
Points of 2.8cm anti-tank guns.

E. All Italian artillery units originally assigned to a division (i.e., as
listed in the OA Chart) have their 75/18 Gun-Howitzer TOE Strength Points
replaced by an equal number of 75/27 guns. The two self-propelled artillery
units in the Littorio and the two in the Ariete each possess 4 TOE Strength
Points of Semovente 75/18 SP guns.

F. The following German artillery units are upgraded: The III/220 and III/220
artillery battalions of the 164th Division each consist of 3 TOE Strength Points
of 1S5cmK18 guns and 3 TOE Strength Points of 15cm sFH18 guns (replacing their
OA Sheet artillery). The 149, 526 and 533 Coastal Defense artillery battalions
replace their artillery with, respectively, 3 TOE Strength Points of 15cm sIG33
guns, 3 TOE Strength Points of 17cm K18 guns and 3 TOE Strength Points of 21cm
Mrs18 guns.

[#63_5]
=== SPECIAL RULES

The following rules may not be used:
A. 10th Italian Light Flotilla
B. Raid on Rommel

[#63_6]
=== INITATIVE

Historically, the Germans had the initiative during the first OpStage of this
scenario. However, the Players may at their discretion roll the die to determine
who has the iniative on the first OpStage. (If the Commonwealth Player gains the
initiative for the fist week, it will be even more depressing than usual for the
Axis Player, of course.)

[#63_7]
=== CONSTRUCTION
[#63_71]*[63.71]* All unfinished Roads have been built.

[#63_72]*[63.72]* The entire unfinished railroad complex has been built.
However, the RR in the three hexes immediately west of el Alamein are destroyed.

[#63_73]*[63.73]* The only pipeline available is that in railroad hexes. The
Axis Player may draw water through it from Tobruk while the Commonwealth Player
may draw water through it from Alexandria.

[#63_74]*[63.74]* All ports are at full (listed) Efficiency except Benghazi, at
Efficiency Level One, and Tobruk at Efficiency Level Five.

[#63_75]*[63.75]* Level One Fortifications are placed in the four hexes adjacent
to Tobruk. In addition, the Axis Player may place a total of three Level One
Fortifications among the four hexes adjacent to Bardia.

[#63_76]*[63.76]* Commonwealth Player places minefields in the following hexes:
D3033, and on map-section E3101, 2901, 2801, 2701, 2702, 2601, 2501, 2401, 2302
and other five hexes (on map-section E). Of the fifteen, ten are Real and five
are Dummy; the distribution is at the Commonwealth Player's choice. All start
the scenario at unknown status (i.e., face-up).

[#63_77]*[63.77]* The Axis Player places minefields in the following hexes of
map-section D: 3233, 3133, 3032, 2933, 2833, 2733, 2632, 2633, 2533, 2429, 2433,
2831, 2832, and 2731. Of the fourteen, eleven are Real and three are Dummy; the
distribution is at the Axis Player's choice. In addition the Axis Player may
place up to five Real and two Dummy minefields in any eligible hexes within
three hexes of Tobruk and a maximum of two Real and two Dummy minefields in any
eligible hexes on game map-section A thru C that are not within five hexes of
Tobruk. ("Eligible" refers to the ability of the Players' to construct a
minefield in that hex under the normal game restrictions.) All start the
scenario at unknown status (i.e., faceup).

[#63_8]
=== AIR & LOGISTICS GAMES ABSTRACTIONS

This case covers the adiustments needed in addition to those given in Case
<<59_6>> in order to play these scenarios without the Air and/or Logistics
Game(s).

[#63_31]*[63.31]* Air Abstracted (Land & Logistics Games): The Commonwealth
initial supplies are reduced as follows: The Front Line Dumps now total 2250
Ammo, 1750 Fuel, 1500 Stores and 1250 Water Points. The other dumps now total
500 Ammo, 2000 Fuel, 400 Stores and 1600 Water Points (see Case <<63_35>>).

[#63_82]*[63.82]* Air & Logistics Abstracted

(Land Game only)

A. The Players' ability to bring in Motorization Points is equal to their
respective abilities to bring in Medium Trucks (i.e., each Medium Truck equals
one Motorization Point).

B. Axis Initial Supply Status: Case <<63_45>> is replaced by the following:

[cols="2,1,1,1",options="header"]
|===
|Location |Regular Supply Units |Ammo |Each with Fuel

|"Other Dumps" Supply units* |14 |40 |20
|"Map D Dumps" Supply units† |2 |40 |25
|Ghaza (D 3328) |1 |40 |60
|Mersa Matruh (D 3714) |1 |40 |60
|Sidi Baranni (C 4131) |1 |40 |60
|Bardia (C 4321) |2 |20 |60
|Tobruk (C 4807) |3 |40 |60
|Derna (B 5925) |1 |40 |60
|Benghazi (A 4827) |2 |25 |60
|Marble Arch (A 2109) |1 |40 |60
|===

*These plus 2 dummy supply units may be placed in any hexes on maps A thru D at
the Axis Player's discretion except that no more than a total of four supply
units (i.e., regular plus dummy) may be placed on maps A through C.

†These, and in addition | dummy supply unit, may be placed in any hexes on Maps
A through C.

C. Commonwealth Initial Supply Status: Case 63.35 is replaced by the following:
The Commonwealth Player receives 13 regular supply units, each with 40 Ammo and
20 Fuel Points, to be placed at his Front Line in any fashion with the
restriction that at least one regular supply unit must be placed in each of the
following hexes: el Alamein (E 3002), E 2805 and E 2403. The Front Line is
defined as hexes E 3002, E 2805, E 2403 and any hex that is east of and adjacent
to an Axis unit. In addition, the Commonwealth Player receives 2 regular supply
units, each with 40 Ammo and 60 Fuel Points, which may be placed anywhere on map
E except that neither may be placed within two hexes of the Front Line (this
includes Front Line hexes not occupied by supply units).

[#63_83]*[63.83]* Logistics Abstracted

(Land & Air Games):

A. The Players' ability to bring in motorization points is equal to their
respective abilities to bring in Medium plus Heavy Trucks (i.e., each Medium and
each Heavy Truck is equal to one. Motorization Point).

B. Axis Initial Supplies: As in <<63_72>> "B" above plus 2 depot supply units,
each with 180 Fuel and 40 Ammo Points, one at Mersa Matruh and one at Tobruk. In
addition, a total of 9 regular supply dumps, each with 30 Ammo and 50 Fuel
Points, to be distributed among and placed on any Axis air facilities other than
Mersa Matruh and Tobruk.

C. Commonwealth Initial Supplies: As in <<63_72>> “C”' above plus a total of 2
depots, each with 40 Ammo and 180 Fuel Points, one each at any Commonwealth air
facility not within three hexes of a Front Line hex.

[#63_9]
=== VICTORY CONDITIONS

[#63_91]*[63.91]* "The Last Chance" Scenario

A. The Axis Player wins a Strategic Victory if he can occupy at least one hex of
Alexandria with at least a Brigade-equivalent unit. Supply doesn't matter.

B. Failing the above, the Axis Player totals the number of TOE Strength Points
(any type) on Game-Map E, the Commonwealth Player totals those TOE points he has
on Game-Map D (exclusive of Layforce and SAS units). The Player with the most
TOE points (in comparison to the other) is the winner of a tactical victory.

[#63_92]*[63.92]* ‘“The Long Retreat" Scenario

The name of the game is survival here. How good is the Axis Player at delaying,
at giving territory grudgingly. He cannot win in a military sense (the Allies
are landing, Africa is lost—at least in retrospect). However, the better he
fights,the more attention the Allies will have to pay to Africa. Here the Axis
Player is playing against actual history. Can he do better than Rommel on this
retreat? Rommel didn't do badly; see if you can best his record (if you don't
fall asleep first). In essence, the Axis Player gains points for occupying
certain locations. Occupying means that all combat units in that City/Village
must have at least one Game-Turn's worth of Stores, be able to fire all weapons
twice, and have enough fuel for all units to move 20 CP's,

[cols="1,1",options="header"]
|===
|Location |Axis Pts for Occupying
|Mersa Matruh |1
|Bardia |3
|Tobruk |5
|Derna |2
|Benghazi |3
|El Agheila |1
|Marble Arch |1
|===

Axis Pts for Occupying

If the Axis Player can get 10 or more points he wins a Strategic Victory.

If he can get 4-9 points, he wins a Substantive Victory.

If he gets 1-3 points, he wins a Marginal Victory.

If he get no points, the Commonwealth Player wins.
