
[#36_0]
== AIR FACILITIES

GENERAL RULE:

Air facilities include airfields, air landing strips, flying boat basins and
flying boat alighting areas.  These facilities are differentiated by the type
and number of planes they can handle in terms of flight and maintenance. Air
facilities are constructed (see Case <<24_7>>), and counters are provided for
that purpose for each type of air facility. Some air facilities exist at the
start of each Scenario; these are noted in the instructions for that Scenario.
Air facilities may be damaged and/or destroyed by Enemy bombardment. The number
of SGSU's and airplaines which can use an air facility is dependent upon its
current capacity level. Thus take-off, recovery, and maintenance are limited.

CASES:

[#36_1]
=== AIRFIELDS

[#36_11]*[36.11]* Airfields are fully-equipped and engineered air facilities,
with repair shops, full maintenance facilities and runway capacity for a large
number of squadrons. Airfield construction is covered in Case <<24_7>>. Each
airfield is noted by an airfield counter in the hex in which the airfield has
been constructed.

[#36_12]*[36.12]* Each Airfield has a capacity level of six (maximum). This
means that it may handle a maximum of six squadrons (regardless of squadron
size) at any one time. There may never be more than six SGSU's in a given
airfield hex. However, see Case <<36_5>>.

[#36_13]*[36.13]* If an airfield is landing six squadrons planes in a given
Operations Stage, it may not receive any more airplanes, even in an emergency.
Such excess planes must seek other fields or strips at which to land. Likewise,
no more than six squadron's worth of planes may be readied at a given airfield
(see Aircraft Maintenance Section <<38_0>>).

[#36_14]*[36.14]* The capacity of an airfield (its levels) may be reduced by
enemy bombardment (air or artillery). Players should keep track of the capacity
level of an airfield. Thus, if bombing has reduced the capacity of an airfield
from six to three, that airfield may handle only three squadrons at a time,
until it is built back up to six. Note that, regardless of the capacity of an
airfield, each airfield may still have six SGSU's with it, even though some may
not be able to function because of a reduced capacity level. If an airfield is
reduced to zero capacity, it is considered destroyed for all purposes.

[#36_15]*[36.15]* Airfields may also be damaged by desert raiders. However,
normal land units never damage airfields (except by barrage; see Cases
<<36_14>>and <<12_5>>). Land combat units may capture or destroy (entirely) an
airfield by occupying its hex. Airfields are, in essence, non-denominational;
they may be used by anyone.

[#36_16]*[36.16]* Players should keep in mind that, while it is the airfield
that has the capacity for maintenance, it is the SGSU that actually performs
that maintenance (see Case <<35_17>>).

[#36_17]*[36.17]* An airfield is a supply dump for supplies to be used by the
SGSU's on that airfield. Fuel, ammunition, stores, etc., may be stored at an
airfield as if it were a dump. Land units may not use airfield supply dumps
unless it is an emergency.  Exactly what constitutes an emergency is left to
the Player. Any SGSU at an airfield may make use of the supplies there to
maintain and ready its planes.

[#36_18]*[36.18]* Airfields have an intrinsic anti-aircraft Strength Point of
one (in addition to any other anti-aircraft units present). The Strength Point
may only be used against planes on strafing and/or dive-bombing combat missions.

[#36_2]
=== AIR LANDING STRIPS

Air landing strips are simply locations cleared and leveled for take-offs and
landings, with only minimal maintenance facilities. They are represented by air
landing strip counters, and they are treated exactly as airfields except that
each air landing strip has a maximum squadron capacity of one. If that capacity
level is destroyed, the strip is eliminated and removed from the game-map (see
Case <<24_7>> for construction details, and Case <<36_1>> for capacity details).

[#36_3]
=== FLYING BOAT BASINS

Flying boat basins are "airfields" for flying boat seaplanes. All flying boats
must use a flying boat basin (or alighting area) for landing and maintenance.
They may not use airfields or landing strips. Basins have the same features as
an airfield, with the exception that their Capacity is three Squadrons.
Construction details are in Case <<24_7>>. Players should note that they can bring
supplies to a flying boat basin simply by bringing trucks into the hex; they
need no other transport.  Flying boat basins are placed in any coastal hex.  As
with airfields, flying boat basins have one intrinsic Strength Point of anti-air
(see Case <<36_18>>.  Flying boat basins may not be used for normal aircraft.

[#36_4]
=== FLYING BOAT ALIGHTING AREAS

Alighting Areas are the same as flying boat basins, except that they have a
capacity of one Squadron and they are immune to artillery barrage. They are
still susceptible to Air Bombardment (see Cases <<24_7>> and <<41_36>>).

[#36_5]
=== OFF-MAP AIR FACILITIES

There are several off-map air facilities: e.g., the Tunisia boxes, the
Commonwealth facilities such as Deversoir, on map E, et cetera. These are
treated the same as other, on-map facilities with three exceptions:

a. There are unlimited supplies for airplane maintenance and repair;

b. They may exceed the SGSU limit up to the limit listed on the field;

c. They may never be destroyed by bombing (although they may be reduced to
zero), and may be rebuilt using the Malta AirFacility Construction Table (one
roll gives total levels for all CW air facilities each game-turn).

Axis Mediterranean bases are also different in one other way: they may not be
bombed.
