[#4_0]
== GAME EQUIPMENT

[#4_1]
=== THE GAME-MAPS

The game-map takes up a great deal of space (it is almost ten feet in length),
and it is virtually impossible to play any scenario without all the maps.
This is because of the logistical nature of the game and the emphasis on supply
lines and transport.  Players will also find that they will be using areas of
the game-map for dropping counters, piling markers, etc. True, there are areas
of the maps that will remain virtually untouched by combat units. Simply
remember what's in play, and what is just being used. Playtesting of CNA, which
usually took anywhere from six to 12 Players at any given time, revealed, among
other things, that most action took place in one section of the game- maps. It
can get pretty crowded in that area at times, so try to keep your displays and
other information out of harm's way.

For those Players experiencing difficulties, the five Map Sections are labeled A
through E and are laid long side by long side from west to east respectively
(see diagram). The Map Sections should be laid so that the Oixx hexrow of a Map
Section overlays the 39xx hexrow of the Map Section whose letter immediately
preceeds it in the alphabet (that is, Map Section E partially overlays Map
Section D which partially overlays Map Section C, etc.).

[note]
====
A B C D E
====

[#4_2]
=== THE COUNTERS

There are actually few counters in play at any one given time. However, each
division on the game- map is comprised of a large number of lesser-sized units.
These battalions and brigades might be brought into use at any given time, so
the players should sort their counters into divisions, and organize their
divisions so that they know where the individual units of that division are. It
may even be wise to have a separate table for placement of such units.

[#4_21]
*[4.21]* Sample Units

[WARNING]
====
Counter images that need to be worked out 

HEADQUARTERS UNIT 

COMBAT UNIT

AXIS COASTAL SHIPPING UNIT

COMMONWEALTH WARSHIP

SQUADRON GROUND SUPPORT UNIT

AIR FACILITY MARKER

FORTIFICATION MARKER

AIRPLANE CLASS MARKER
====

[#4_22]
*[4.22]* Unit Type Symbols

[WARNING]
====
Page 8 is fully of symbol we will have to create corresponding images
====


[#4_23]
*[4.23]* Counter Summary

[WARNING]
====
Page 8 is fully of symbol we will have to create corresponding images
====

[#4_24]
*[4.24]* Informational Marker Summary
[WARNING]
====
Page 8 is fully of symbol we will have to create corresponding images
====

[#4_25]
*[4.25]* *Counter Deployment*

A unit attached to another unit is not represented by a counter on the game
map.

For example: The First Greek Infantry Brigade Group is comprised of the Ist
Greek Brigade HQ counter, the Ist Greek Field Artillery Regiment counter and the
Ist Greek Infantry, 2nd Greek Infantry and 3rd Greek Infantry Battalions
counters. If the three infantry battalions and the artillery regiment were
attached to the headquarters unit, the entire brigade would be represented on
the game map by the headquarters counter. Unless specifically stated, all
assigned units beginning a scenario in the same hex as their parent unit are
attached to that parent unit. The counters representing said units are therefore
not deployed on the game-map.

[#4_26]
*[4.26] Holding Boxes*

Certain hexes on the game-map "attract" a large number of counters. These hexes
are represented by Holding Boxes which are nothing more than large spaces for
deploying all of the counters which are actually located in the hex the Holding
Box is representing.

[#4_3]
=== CHARTS AND TABLES

There are an inordinate number of Charts and Tables in CNA. Most of them can be
found in the Charts and Tables Booklet. However, some are located on separate
loose sheets of paper or printed on the game-map or in the Rules booklets.

[#4_4]
=== ORGANIZATION AND ARRIVAL SYSTEM

In any given scenario, the Players receive units via the Initial Deployment
(given in each scenario) and via the Reinforcement Schedules. In addition to
these, Players may plan for Replacement Points to augment depleted units; the
discussion of these can be found in <<20_2>>. The Cases below give the Players
a base for using and understanding the terminology and location of the terms
and tables for acquiring and using units.

[#4_41]
*[4.41]* There are three types of charts which the Player will refer to
in order to gain information on his units. These are the Characteristics Charts,
which show what capabilities and characteristics each unit or unit-type has (in
terms of. ratings and numbers), the "OA" Sheets, which list the organization of
units and arrival dates for each parent unit (usually division), and the
Reinforce- ment Schedules, which list the names and dates of all newly arriving
land units. Air units have separate reinforcement charts and tables which
determine their arrival.

[#4_42]
*[4.42]* The following procedure is used to deter- mine which units
arrive during a Game-Turn and the abilities of those arriving units. The Player
consults the appropriate Reinforcement Schedule and determines the current
Operations Stage of the Game-Turn in progress; noting the units arriving, he
finds the OA (Organization at Arrival) Chart for each of those units. Parent
Formations are easy to find (e.g., divisions and brigades); smaller detachments
arriving piecemeal are usually given their parent formation for easy reference
to the correct OA Sheet. Having located the correct OA Sheet for each unit, the
Player notes the Characteristics Code for each individual unit (that has
arrived) in that Parent, and refers to the Characteristics Charts to determine
the capabilities of those units. Each Parent unit arrives with all lesser
units listed on the OA Chart, unless the unit has a later arrival date and/or is
listed as excluded on the Reinforcement Track.  Players should then draw up a
TOE Sheet for each such Parent Formation (and its lesser units). To more clearly
understand the above procedure, Players should at this time run through a sample
turn of Reinforcements, using any turn on the Track. Such a brief examination
will quickly show how this process operates.

[note]
====
The Player is provided with an inter-locking series of charts and tables,
each dependent on the other for information. Although there are a lot of tables
and the profusion may seem confusing, just a brief scanning of these tables and
tracks will be enough to show how they work. Remember, each different table or
track provides a piece of information, and the tables and tracks often contain
information found on the other such tracks or tables for purposes of
cross-checking. Example: The Reinforcement Schedule shows the arrival of the
18th Australian Brigade. The Commonwealth Player, noting that, looks forthe OA
Sheet for the 18th Australian Brigade. The OA Sheet also gives the Arrival Date,
which is a cross-check with the Reinforcement Schedule. The Player now notes the
units within the brigade, their Characteristic Code Letters, and consults the
Unit Characteristics Charts for those units to determine what their capabilities
are. This information is then placed on the TOE Sheet for the 18th Brigade,
along with any other information needed or desired.
====

[#4_43]
*[4.43] Reinforcement Schedules*
(see Charts and Tables)

[#4_44]
*[4.44] Aircraft Characteristics Charts*

There are two identically organized Aircraft Characteristics Charts one for each
Player. Within each nationality the planes are grouped into those needing
pilots and those not requiring pilots. Each plane is listed individually.
Certain bear two or more rows of information. With these planes the owning
Player may freely choose which line of characteristics and capabilities he will
assign that plane every time he readies it. The explanation of the various
ratings is discussed in <<34_1>> of the Air Game.

[#4_45]
*[4.45] Organization At Arrival Charts (OA)*

A great deal of time (perhaps too much time) was spent in arriving at the most
accurate Order of Battle possible. As with any major campaign, sources differed,
and the designers were forced, for a variety of reasons, to make several
decisions which abstracted some units (especially anti-aircraft units). We feel
that CNA has, by far, the most accurate Order of Battle ever done for the
Campaign for North Africa. However, if you have information to the contrary
about a specific unit, feel free to adjust the game to fit that information. If
you feel like it, we would also like to hear about that information.

There are three identically organized OA Charts, one for Allied units, one for
German units, and one for Italian units. Each chart is subdivided into sections
hereafter termed sheets. Each sheet contains game and historical information
on a major unit or grouping of units (e.g., all unassigned artillery units;
50th Infantry Division) of that Player's forces. The sheet is laid out as
follows: the name of the major unit or regrouping is at the top.  Below that is
the Basic Morale Rating for all of the counters comprising that unit (untrained
Commonwealth unit's morale at instant of arrival is indicated in parentheses
where needed). This is followed by a list of the counters comprising the unit
and any notes at the bottom of the sheet. The counters comprising the unit are
arranged with the headquarters unit (if any) for that group at the top. Any
units assigned directly to that HQ are indented, and any unit assigned to a
subsidiary unit is further indented and listed in the rows directly below their
brigade level parent unit. The explanation of the information contained under
the column headings is as follows:

_Unit Name_: The historical name of that unit. Certain abbreviations have been
made for each nationality and they are listed at the end of the Chart.

_Counter Abbreviation_: The type as it appears on the counter.

_ID Code_: One, two, or three letters which summarize the unit's
 characteristics. The unit's ratings for a particular ID Code
are listed on the Unit Characteristics Chart for that nationality.

_TOE and Weapons Systems_: A unit comprised of a
single type of weapons system (i.e., TOE Strength Points with identical
cHaracteristics) bears an N(ormal), U(nderstrength), or. O(verstrength)
indicator. If the unit is normal, it arrives (or begins deployed) at its maximum
possible TOE Strength.  If the unit arrives understrength or overstrength its
TOE Strength at arrival will follow the U or O. If, on arrival, a unit comprises
tank, artillery, or antitank TOE Strength Points, the number and then the type
of the different TOE Strength Points will be listed.'

_Arrives_: The Operation Stage/Game-Turn on which the unit arrives. If the unit
beings the first scenario already deployed on the map, it is noted as a D. This
column is a check on the Reinforcement Schedule.

The OA Sheets are needed for a purpose other than pure numerical information.
The OA Sheets list the units originally assigned to a Parent unit.  This is
important, as units assigned to a Parent unit may stack and unstack, attach and
detach themselves quite freely compared to other units being attached to that
same Parent unit. The OA Sheets also, on occasion, list units that were
historically attached to a Parent Formation at certain times during the
Campaign.

There are numerous units that are not assigned to a division. These may be
brigades (the Commonwealth Player has many of these) or simply solitary
battalions, artillery regiments, etc. These units are grouped on OA Sheets
according to their most important assignment characteristics (i.e., all of the
British unassigned anti-air units are on a single OA Sheet).

The designers of CNA have chosen the division/brigade/battalion terminology
system because it was (1) the basic system of a majority of the units in the
campaign, and (2) the system with which they were most familiar. In many places
it does not reflect the actual organizational levels of a unit. This is further
exacerbated by the maddening British desire to call everything a regiment or a
brigade when, in fact, it is a battalion. Thus, the 7th Rifle Brigade is, in
game terms, a battalion (actually the 7th Battalion, the Rifle Brigade) and most
of the "Tank Regiments" are battalion-size units. Most Players familiar with the
campaign should have little trouble with items such as these (few people will
think that the 1st King's Royal Rifle Corps is, in fact, an actual Corps).

[#4_46]
*[4.46] Unit Characteristics Charts*

There are three identically organized Unit Characteristics charts, one for
Allied units, one for German units and one for Italian units. The Unit
Characteristics Chart lists each ID Code's maximum TOE Strength Points and its
values for the various Ratings. Unless otherwise indicated on the chart, all
tank, artillery, anti-tank, and certain HQ units may comprise any combination of
the variety of the weapons systems listed. These units take on the
characteristics of the assigned TOE Strength Points (weapons systems). A unit
comprising multiple weapons systems is a single unit for all purposes.
However, all actions are undertaken using the ratings of the individual TOE
Strength Points (e.g., an artillery unit comprising two TOE Strength Points of
eighteen pounder guns and four TOE Strength Points of twenty-five pounder guns
engaging in Barrage will fire at two times the eighteen pounder gun Barrage
Rating plus four times the twenty-five pounder gun Barrage Rating). Note that a
unit comprising different TOE Strength Points normally possess a CPA of that of
the slowest TOE Strength Point. The characteristics of the individiual weapons
systems are listed on the appropriate nationality's Tank and Gun
Characteristics' Chart. Certain unit posses parenthesized combat ratings. These
units are discussed in <<3_3>>. Certain headquarters units' maximum limit in
assigned TOE Strength Points are enclosed in parentheses. Any weapons system TOE
Strength Points assigned to such a unit operate with parenthesized combat
values.  Players should note that the maximum number of assigned TOE Strength
Points for British Tank Regiments (battalion-equivalents) changes slightly in
early 1942, with the influx of the first American tanks. Tank regiments with
only American tanks (Grants and/or Shermans and/or Stuarts) now have a maximum
of 9 TOE Strength Points, not ten. The reason for this decision is not clear;
the allotment of tanks to a regiment, however, was dropped from 52 to 44 when
the tanks were American. This was readjusted later on.


[#4_47]
*[4.47] Commonwealth Tank and Gun Characteristics Chart*
(see charts and tables)

This chart lists the values for TOE Strength Points
of a specific type of tank or gun. The definitions of
these characteristics are listed in <<3_3>>.

[#4_48]
*[4.48] Italian Tank and Gun Characteristics Chart*
(see Charts and Tables)

[#4_49]
*[4.49] German Tank and Gun Characteristics Chart*
(see Charts and Tables)

[#4_5]
=== LOG SHEETS

Because of the enormous amount of information provided with CNA, and because of
the game system devised for its use, there are a great number of Play-aids, in
the form of Informational Sheets.  The playing counters themselves have little
combat information other than the unit designations and Stacking Points, and
there are few "tracks" by which the Players can keep visual record of various
supply levels. The reasons for this are many: the desire of the designer to
include as much information as possible; the problem of keeping vital
information secret from other Players; the fact that the game-map itself is so
large that having a plethora of charts and tracks would make it necessary to
rent The Hearst Estate at San Simeon to play it, etc. Therefore, players will
keep track of virtually all the information they need which is quite extensive
on the various sheets. The following sections describe these sheets,
although we hope that they have been so designed that their utilization becomes
self-evident. Players should feel free to devise any other sheets or methods
they feel necessary to ease the flow of the game; most of the sheets in CNA were
"designed" by the playtesters.

One copy of each type of Log Sheet is provided with CNA. Players should
therefore produce as many copies of each form as they need, The designers
suggest you use pencils and write lightly to make complete erasures easy.

[#4_51]
*[4.51]* The Log Sheets have been divided into four groups on the basis
of their "owning" Player's usage. This is simply a presentation decision and
has no effect on who actually uses what in a game.

[#4_52]
*[4.52] Field Commander's Group*

These forms are used by the Players in charge of frontline fighting combat
units.

_Field Commander Control Sheet_: This is designed to help the Field Commander
coordinate his forces. Each row on the sheet is meant for each counter on the
game-map under the Player's control. These counters will normally be
Division-Eq, and a few Brigade-Eq's. Space is provided for keeping track of the
unit's Capability Point expenditure(s) in that Operations Stage, its Capability
Point Allowance (CPA), current Cohesion Level, Actual Points the unit could
contribute to a Barrage and Offensive and Defensive Close Assault, and its
reserves of Ammo and Fuel. There is space for your "weekly" Stores requirements
for the units as a whole (Players rarely transport Stores on Attached Trucks,
because the Stores are required only once per game-week). The bottom section of
the sheet is for notes, normally detailing peculiarities of certain of the units
attached to the counters listed above them on the sheet.

_TOE Log Sheets_: There are three of these in order to ease handling five basic
division formation and organization structures and counters representing
Brigade-Eq and smaller units. The TOE Log Sheets are the equivalent, for play
purposes, of a giant combat unit counter. Each Parent Unit possesses its own TOE
Log Sheet, and on it the Players keep track of the various strengths and ratings
of the units within that formation, the changes to them and the supplies and
trucks carried by and attached to that unit. The sheets can all be divided into
the following sections or information areas:

_A: Counter Identity_: This is the area on the top of the sheet. The counter's
historical name, its Basic Morale, its Current Morale (if Commonwealth), and
any other useful information (such as its assigned Parent Unit, if any, Garrison
location, engineering capability, etc.) should be written in this section.

_E: Logistics_: This is the area marked "1st Line Transport." The area is
subdivided into Trucks Available and Supplies. The first grouping consists of
two paired rows of three boxes. They are for indicating the total attached
Trucks and of those trucks, which are currently transporting nothing, by
division into Heavy, Medium and Light trucks. The second grouping is for
supplies and troops and/or guns being motorized by the attached trucks by the
amount and the number of trucks and the type that are carrying them.

_F: Combat Information_: Boxes for recording (usually the maximum) number of
actual Points that the unit is capable of in each of the categories.

_D: Augmentation_: This is for recording the attachment of units over that
formation's organization structure. (See Section on <<19_0,Unit Organization>>). The method of
filling out the boxes in this section is identical to that of Maneuver and
Division Assets below. Any unit going i this section is attached to the counter
the Log Sheet represents, although it may be assigned to some other unit.

_G. Notes_: Anything appropriate, ranging from which units are out of ammo or
supplies to the amount of Water required by the elements comprising the counter
every Operations Stage.

_C Divisional Assets/Support Units_: Applies to those units attached directly to
the division and not under a Brigade-Eq HQ (unless ina Common wealth Armored
Division). The boxes are filled in the same manner as Maneuver section.

_B. Maneuver Elements_: These boxes are the heart of the Log Sheet. They are
where the information for the main combat forces comprising the counter is
recorded. Basically, each box is used to record a single counter (i.e.,
attached unit). The information to be recorded consists of the unit's type,
CPA, Fuel and Breakdown Rates (if any), current TOE Strength, name, and its
ratings for barrage, anti-armor, vulnerability, armorprotection, offensive
close assault, defensive close assault and anti-aircraft. Information
concerning whether the unit is simply attached to the unit without being
assigned, and/or is assigned to another parent unit or is a garrison unit,
etc., is best recorded in the notes section. A tank or gun unit that is
comprised of more than one weapons system (i.e., type of TOE Strength Point)
will require more than one box to represent the unit (as many boxes as there
are weapons systems). A unit assigned but not at present attached to the unit
whose Log Sheet you are handling still occupies space within the formation's
organization. This space may not be filled by attaching other units in its
place. For ease of play, fill in "detached" in the box of sucha unit.

The recorded information may be written in or adjacent to the unit's box in any
manner the Player desires as long as he and the other Player's have no problems
in reading it.

_Brigade TOE Log Sheet_: This is used for counters representing Brigade-Eq and
smaller units. The formation's organization limits can be found by using the
Formation Organization Chart and the Formation Attachment Chart. It is useful
to put these limits in the Notes Section. As this is a multipurpose form, the
boxes in the Maneuver Elements and Augmentation sections are unadorned and can
be divided in any manner necessary.

_Infantry Division TOE Log Sheet_: The boxes in the Maneuver Elements section are
organized in a very restricted fashion. Some of the boxes in the Divisional
Assets and all of the boxes in the Augmentation sections are unadorned to
permit recording of multiple weapons systems occurring in the same unit. The
division's organization and augmentation limits can be determined from the
charts indicated above.

Allied and Italian Armored and German Division TOE Log Sheets This is free form
with the boxes unstructured so as to permit the expected variations in both
multiple weapons systems in a single unit and variations in division
organization.

[#4_53]
*[4.53] Rear Area Commander's Group*

This group belongs to the Player in charge of construction, demolition, mopping
up operations, and other rear area jobs having nothing to do with supplies.
(The Player will usually have a Trucks and Major End Items Control Sheet as he
will normally be assigned some trucks in order to handle routine operations
without bothering the Logistics Commander).

_Vehicle Repair Control Sheet_: Permits the Player to handle all broken down
vehicle, destroyed tanks and abandoned vehicle counters.

_Naval Convoy Log Sheet_: While designed primarily for Axis strategic Naval
convoys it is also used for either Player's tactical shipping. The sheet permits keeping track of naval transport, its location, destination, transit, what is being transported, etc.

_POW Control Sheet_: Designed to handle all POW's, their Capability Points
expended, location and inhabitation of the POW Camps, and the TOE Strength and
infantry-type of their Guards.

[#4_54]
*[4.54] Air Marshal's Group*

The Player in charge of all the airplanes uses the following two forms and
usually the Supply Dump Control Sheet to simplify required aircraft supply
expenditures the aircraft require.

_Squadron Ground Support Unit Sheet_: The sheet contains space for controlling
six squadrons of planes, the maximum number that can be berthed at an airfield.
Each squadron section permits counter location, basic composition, aircraft
characteristics recording, and the state and Mission of each plane in the
squadron.

_Air Mission Log Sheet_: Permits the Player to coordinate all air missions
assigned in that Operations Stage/Game-Turn, by hex and by squadron supplying
the planes.

[#4_55]
*[4.55] Logistics Commander's Group*

The Player in overall charge of supplies.

_Trucks and Major End Items Control Sheet_: Used for the Player's Truck Convoys.
Organized to identify, within each counter, the number of each type of truck in
the convoy, what supplies are being transported and by what trucks; which
trucks are ‘empty', any replacement points, repaired vehicles, returning
Guards, etc., being returned or exchanged between units.

_Supply Dumps Control Sheet_: Enables the Player to keep track of the supplies
and location of each of his supply dumps. It is strongly suggested that the
Logistics Commander determine which of his dumps will be actively or constantly
used and those which are not and separate them into different sheets, as the
actual supply dump counter ID number has no effect.

_General Supply Net Sheet_: The .Logistics Commander's chief headaches are how
much supply does he have, how much is coming in, and how much of that supply is
likely to be used in the near future. This sheet is set up to help prevent him
from running out of a supply by accident, as it were, either locally or
strategically.

_Supply Requisition Form_: The Logistics Commander is in charge of disbursing
these to the various Field Commanders and Air Marshals. This may seem humorous
at this point, but the form proved quite helpful in maintaining good supply
organization, and it sure beats yelling at the top of your voice for 100
gallons of fuel.

[#4_6]
=== INVENTORY OF GAME PARTS

One Game-Map (five sections)

Nine sheets of 200 die-cut counters (1800 total) One Land Game Rules Booklet

One Air & Logistics Game Rules Booklet

Two Charts & Tables Booklets

One 5/8” and one 3/8” plastic die

One Game Box assembly

One 22" x 34" log sheet

One Historical Article Booklet

If any parts are missing or damaged, write, fill out the enclosed Complaint
Card and return to SPI for replacement. 

[note]
====
The process used to manufacture
counters sometimes results in images being slightly off-center or in colors
spilling along the edges of differently colored counters. Counters displaying
such minor imperfections cannot be replaced by SPI. Only in cases where the
counters are not legible can SPI supply replacement parts.
====

In the Land Game, the Players deal with the fine distinctions of terrain and
local and variable weather encountered by the actual combatants. The
interlocking and detailed movement and combat systems permit the Players to
recreate real time and space "continuous" movement and combat. The
organization and equipment rules create voluminous options, allowing the
Players to deploy and maneuver company level and larger forces with equal ease
while at the same time differentiating between raw, poorly motivated, or badly
armed units and veteran, well motivated, well equipped forces as well as
changes in the same unit from one state to the other.

