[#31_0]
== ROMMEL

GENERAL RULE:

The Axis Player receives a counter representing General Rommel. The Rommel
counter aids the Axis Player in several ways (see also Raid on Rommel,
Section <<27_6>>:

1. Rommel has a Movement Capability Point Allowance of sixty (60); the Rommel
counter is considered a vehicle (treat as 4-wheel drive medium truck with AM
radio only and no ).  He has no combat ratings.

2. Rommel may react and retreat before assault when approached by any unit
except an LRDG.  He may Retreat through an Enemy Zone of Control with impunity.

3. If Rommel is in the same hex as a unit involved in combat during the Combat
Phase, all units in that stack have their Morale increased by one.

4. If Rommel starts an Operations Stage with a unit(s) and remains with that
unit for the entire Operations Stage, such unit may increase its Capability
Point Allowance by five points.

In addition to the above, there is a chance that Rommel has been called back to
Berlin or has flown to Germany for health reasons. At the beginning of each
Game-Turn that Rommel is present the Axis Player rolls two dice. If he rolls a
12 Rommel is in Germany, and the Axis Initiative falls to 3 for that Game-Turn.
Rommel returns the next Game-Turn (unless the Player throws another 12).

A brief Designer's Note: The inclusion of Rommel as a counter (without using
other specific commanders) was a pure design decision. While Rommel did have a
great affect on tactical operations and decisions, including only him in the
game is a Design Affectation, pure and simple. However, the effect of the Rommel
counter is historical.
