= Scenarios

[#59_0]
== INTRODUCTION TO SCENARIOS

COMMENTARY:

There are five scenario groups in Campaign for North Africa. Each scenario group
contains at least one separate game. Of course, one is for the playing of a
campaign game. The groups cover what the designer felt were the most important —
and most accessible, in terms of information — areas of the campaign. Specific
battles, such as Gazala, were avoided as they did not fit within the concept of
the game (operational). Each scenario is a self-contained game and each
highlights certain problems.

Those wishing to get the most out of CNA without becoming enmeshed in a lifetime
occupation are advised to try the Rommel's Arrival scenario — it is fast-moving
and a lot of fun. It is also not too long or difficult (the small number of
units involved keeps paperwork to a minimum). For those interested in seeing why
trucks are so important and want to keep all their work in a small area, try the
Italian scenario. For those interested in seeing a lot of units sit around doing
nothing, try El Alamein —aremarkably boring situation (in game terms, if not
historically).

Players should take great care in setting up each scenario, as a great deal of
information is provided. The bigger scenarios could take 10 to 15 hours to
prepare. A further word to the Africa buffs: given all the information in the
game, it should be fairly easy to concoct your own situations and scenarios.
Your major problem would be logistical information.

On the subject of Victory Conditions, it is the designer's feeling that, in a
game of this size and scope, few Players will patiently battle through 100-200
hours of playing time and feel they have actually lost (or won). Finishing is an
event in itself. The Victory Conditions have been thought out carefully, in
light of not only what was actually accomplished, but also what had to be
accomplished. Yet the conditions are somewhat general, especially the campaign
game objectives. This is because outside considerations that could not possibly
have been simulated had to be taken into effect. Any Player worth his salt will
know whether he has accomplished what he set out to do without checking what
we've told him he must do.

CASES:

[#59_1]
=== SCENARIO ORGANIZATION

[#59_11]
*[59.11]* The scenarios in CNA are divided into five groups. The first
four of these groups deal with individual battles or offensives, and the fifth
covers the campaign game.

[#59_12]
*[59.12]* Each of the first four scenario groups contains the following information:

a. Length of the scenarios in the group.

b. Victory Conditions of the scenarios in the
group.

c. Initial location and strength of all land and air
forces.

d. Initial location and amount of all supplies.

e. Initial location and number of all trucks.

f. Forces available on Malta & Crete/Italy/Sicily.
g. Abstractions necessary to play the scenarios
without the Air and/or Logistics Games.

h. Special rules for the individual scenarios.

[#59_2]
=== HOW TO READ THE SCENARIO SET-UPS

Basically, all air and land units, supplies, and trucks available at the start
of a scenario are listed by hex location. Generally, the parent unit will be
listed, and Players must refer to the appropriate OA Chart to determine which
subordinate units are assigned to that parent unit. Whenever a given unit has a
composition different from the one listed on the OA Chart, that is noted in
parentheses.

Hex Location. If more than one hex is listed for a given group of units, the
Player may divide the listed units between the hexes in any way he chooses, so
long as stacking limitations are not exceeded.

Unit Type. If not apparent from the name, this is noted with an abbreviation.
Where noted, it is always the first item enclosed in parentheses.  I = infantry;
R = reconnaissance (recce); T = tank; Ar = artillery; AT = anti-tank; AA =
anti-air; HQ = headquarters (the headquarters counter only).

Parent of Listed Unit. If the listed unit has been assigned to a parent unit
(whether or not it still is), that parent unit's designation is listed, in bold
type, as it appears on the listed unit's counter. This is to facilitate
identification of the listed unit.

Listed Unit Lacks Subordinate Units Originally Assigned. All such subtractions
from what is listed on the OA Chart are noted after the indicator "Less".

Listed Unit Includes Subordinate Units Not Originally Assigned. All such
additional units (which may be detached) are listed after the indicator "Assg".

Assigned Subordinate Units Are Detached. These are listed under the parent unit
after the indicator "Det". Of course, they are listed separately in the hex(es)
they themselves are in.

Listed Unit Has Entirely New/Different Roster of Assigned Units from Those
Listed on OA Chart.  AJl subordinate units listed after indicator "Consists of".

[note]
Whenever a unit inside parentheses requires expanded explanation, that explanation
is enclosed inside double parentheses: e.g., (f....)).

Listed Unit Exceeds Formation Organization Limits. Such units may operate
normally, including being themselves assigned and/or attached, with the
exception that no new subordinate units may be assigned or attached to them, and
should any units be detached, no new ones may be attached in violation of the
limits.

Listed Unit Includes Subordinate Units Attached But Not Assigmed. All such units
are listed after the abbreviation "Att".

Disposition of the Units in a Hex. All units listed to begin in the same hex may
be organized as the owning Player chooses, within the limits of the Formation
Organization rules and stacking limitations. In other words, units in the same
hex may be freely detached or attached to each other at the start of the
scenario, in any fashion deemed desirable.

Trucks. All listed trucks are first line trucks and must be assigned to the
units in the hex, in any manner deemed desirable.

Abbreviations Used in Scenario Set-Ups.

Div = division; Bde = brigade; Regt = regiment; Bn = battalion; Coy = company;
In = Indian; Gds = Guards; RTR = Royal
Tank Regiment; RHA = Royal Horse Artillery;
Hus = Hussars; SA = South African;
NZ = New Zealand; Cp = Conps; CLY =
County of London Yeomanry; Gaf = Garrison
troops; CCNN = Blackshirts; * = no parent
organization.

[#59_3]
=== INITIAL AIR STRENGTHS

[#59_31]
*[59.31]* Each scenario lists the starting Axis and Allied plane types,
numbers, pilots, air facilities, and squadron ground support units. This listing
is divided into forces available in North Africa and Malta for the Allied Player
and to forces available in North Africa and Sicily/Italy/Crete for the Axis
Player.

[#59_32]
*[59.32]* Planes are listed by type, with the ready planes indicated as
a portion of the total available.  All planes (refitted or not) are considered
to begin a scenario fueled and armed (at no cost to the supplies available).

[#59_33]
*[59.33]* Planes may be distributed among the squadron ground support
units as the owning Player desires within the restrictions on squadron
composition listed in Case <<35_2,35.2>>.

[#59_34]
*[59.34]* Pilots may be assigned to planes and squadrons as the owning
Player desires.

[#59_35]
*[59.35]* Squadron ground support units may be placed on any of the air
facilities owned by the Player. However the number of SGSU's may not exceed an
air facility's readying capability.

[#59_36]
*[59.36]* Maintenance may not be _ performed onplanes during the first
OpStage of a Scenario.

[#59_4]
=== INITIAL TRUCK STRENGTHS

[#59_41]
*[59.41]* Trucks initially available to each Player are divided into Ist
line, 2nd-3rd line available for supplies, and 2nd-3rd line available for air
facilities,

[#59_42]
*[59.42]* First line trucks are listed by hex in the land forces initial
deployment section of the scenario. These trucks must be assigned to units in
their listed hex. The trucks may be divided among the units in that hex in any
manner the Player desires.

[#59_43]
*[59.43]* Second-third line (in convoy) trucks available for air
facilities must be placed on an air facility.

[#59_44]
*[59.44]* Second-third line trucks available to transport supplies must
be placed (if the Axis Player is not starting them off-map) on a hex occupied by
a Friendly combat unit, a supply dump, or a major city/town/oasis. These trucks
may be distributed as the owning Player desires.

[#59_45]
*[59.45]* Trucks may start a scenario transporting supplies or
motorizing troops or anti-aircraft units at no cost or penalty. Any trucks
starting with supplies may load any type of supply. These supplies are in
addition to those listed in the supply section of the scenario.

[#59_5]
=== INITIAL SUPPLY

[#59_51]
*[59.51]* Each scenario lists the location and amounts of a Player's
initial supplies.

[#59_52]
*[59.52]* The supplies are divided into those available at air
facilities and those available at supply dumps. Air facilities automatically
possess a supply dump. If a Player places supplies available at a supply dump in
the same location as those available at an air facility, the totals are combined
and it becomes one dump (see Case <<36_17,36.17>>). Some scenarios separately list an
aggregate number of supplies available at a player's air facilities: These may
never be allocated to off-map facilities.

[#59_53]
*[59.53]* Certain scenarios list a Player as receiving active and
non-active supply dumps. Non-active dumps are dummy dumps and cannot, therefore,
be placed in the same hex as an air facility.

[#59_54]
*[59.54]* Axis coastal shipping begins all scenarios unloaded (i.e.,
empty).

[#59_6]
=== ABSTRACT LOGISTICS AND AIR

[#59_61]
*[59.61]* If only the Air Game is abstracted, the Players simply ignore
all Trucks and supplies available at/for Air facilities in the initial set-ups.
Play is then governed by the rules in Section <<58_0,58.0>>.

[#59_62]
*[59.62]* If the Logistics Game is abstracted, whether or not the Air
Game is also abstracted, Players will be using Motorization Points and Supply
Units. The initial set-ups for the Supply Units and Motorization Points are
given in the following cases.

[#59_63]
*[59.63]* Initial Motorization Point Strengths: The initial motorization
points available to each Player are calculated from the trucks listed in the
scenario set-up.

A. Attached Motorization Points: These are calculated, hex by hex, from the Ist
Line trucks available to the Player unless specifically modified by a Scenario's
instructions. Each Medium Truck and each Heavy Truck is equal to one
Motorization Point. Example: In the first Scenario Group, the 4th CCNN is listed
as beginning the scenario with 10 Light, 25 Medium and 10 Heavy Trucks. It
possesses 35 Motorization Points.

B. Unattached Motorization Points: These are calculated from the second-third
Line trucks available to each Player in the same manner as in "A." If the Air
Game is being abstracted, ignore all trucks available atair facilities. Note
that the initial distribution/placement of these trucks will affect their
ability to start a scenario loaded with supplies in addition to those listed as
available in supply dumps (see Case <<59_66,59.66>>).

[#59_64]
*[59.64]* Initial Motorization Point distributions may be, with one
exception (see Case <<59_66,59.66>> "B"), freely altered once the game starts as per
the Land Game rules on attachment and detachment.

[#59_65]
*[59.65]* Supply Units: The Player's initial supply levels are listed as
to the number, location, and contents of regular and depot supply units
available. Regular supply units are described in Section <<32_0,32.0>>. Depot supply
units — used only if the Air Game is being played and the Logistics Game is
being abstracted — are described in Section <<47_0,47.0>>. Initial supply unit
placement may exceed stacking limitations only if unavoidable due to scenario
distribution instructions. There is no penalty in such situations; however, no
additional supply unit may be stacked in that hex. Once the supply unit
distribution meets stacking restrictions all normal stacking restrictions for
that hex must be met from that point on. (Remember that motorization points
transporting supply units do not count against hex stacking limits.)

[#59_66]
*[59.66]* Additional Supplies:

A. Motorization Points may begin a scenario loaded with supplies. These do not
count against supplies listed in the scenarios supply dumps.

B. Each attached Motorization Point (see Case 59.63 "A") not initially
transporting men or guns may start loaded with 1 Ammo Point or 3 Fuel Points.
the unit must consume these supplies first (i.e., it may not draw on a supply
unit) in order to meet any supply expenditure requirement. These supplies may
not be transferred to a supply unit.  The Motorization Points transporting these
supplies may be detached from the unit only if remaining attached to a
subsidiary combat unit of that parent unit (Note that the Motorization Point is
under this réstriction only while it is transporting these initial supplies).

C. Unattached Motorization Points (see Case 59.63 "B") are divided into those
that are listed as initially available at air facilities (these appear only if
playing the Air Game) and all other unattached Motorization Points. Air facility
Motorization Points may begin by transporting additional supply units as
follows: Each 50 Motorization Points in a hex may start with a depot supply
unit; each 30 Motorization Points in a hex may start with a regular supply unit.
Each 30 other unattached Motorization Points in a hex may start with a regular
supply unit. Example: 80 air facility and 100 other Motorization Points may
begin with the air facility points transporting one depot and one regular supply
unit while the other points may begin with three regular supply units. Note that
for these Motorization Points to begin with a supply unit they must be in groups
of 30 (and/or 50 if air facility) points (i.e., 20 Motorization Points may not
begin with a supply unit). The Tripoli/Tunisia boxes are hexes for the purposes
of this Case.
