
= THE AIR GAME

The following rules Sections cover the air war in CNA. In essence, all planes
are represented individually, and fighters have pilots. Each type of plane has
differing characteristics and mission capabilities. All of these are listed in
the Aircraft Characteristics Charts for each nationality. Yet, in keeping with
the tone of the land game, the feel of the game is operational. While there is
plane-to plane combat, it is not resolved tactically, and all strengths have been
considered operationally.

Ideally, the air portion of the game requires a separate Player for each side.
There is a large amount of paperwork involved, and, even though there were
relatively few planes in Africa, a Player may have to juggle operations for 500
to 1000 aircraft during a given OpStage. The rules for the Air Game are a lot
simpler than those for the land game. Air Commanders should simply keep their
Characteristics Charts handy and be prepared to do a lot of planning.

[#33_0]
== SEQUENCE OF PLAY: Air Game

[note]
It is possible to use the Land Game and Air Game Rules while omitting the
Logistics Game Tules.

[unnumbered]
=== LAND/AIR GAME-TURN SEQUENCE OF PLAY

Play of the game should proceed in accordance with the following outline.

[upperroman]
. INITIATIVE DETERMINATION STAGE
+
The Players determine who will have the initiative for the coming Game-Turn (see
Section <<7_0,7.0>>. The Player going first within the Operations Stage (see below)
is known as "Player A"; the other is “Player B".

. STRATEGIC AIR PLANNING STAGE
.. *Designation Phase:*
+
The Players assign their airplanes to fly Land Support or Strategic missions.

.. *Axis Malta Availability Determination Phase*
+
The Axis Player determines the amount of support he' will receive from his
abstracted N. African Theatre airforce for Raids on Malta.

.. *Strategic Mission Assignment Phase*
+
Planes designated as flying. Strategic missions are assigned. The Axis Player
assigns his planes to Raids on Malta or naval convoy protection. The
Commonwealth Player assigns his planes to naval Recon missions or Bombing
Reserve.

.. *Malta Raid Phase*
+
The Axis Player resolves flak suppression, antiaircraft fire and bombing
missions against Maltese air facilities (Note that Commonwealth warships
stationed at Valetta may only be attacked by Land Support Missions).

. NAVAL CONVOY STAGE

A. *Naval Convoy Schedule Phase*
+
The Axis Player refers to the Axis Naval Convoy
Level Chart and then to the Axis Convoy Capacity Table and rolls one die to
determine the total tonnage available for the next Game-Turn. He then plans what
specific cargoes the convoys will carry and their routes.

B. *Convoy Resolution Phase*

... Naval Convoy Reconnaissance Segment
+
The Allied Player resolves Strategic Convoy Reconnaissance missions.

... Convoy Lane Assignment Segment
+
Axis convoy protection aircraft are assigned CAP missions in specific Convoy Lanes. Commonwealth Bombing Reserve aircraft are assigned
CAP, Flak Suppression or Convoy Bombing missions in specific convoy lanes.

... Convoy Bombing Segment
+
All air-to-air combat, Flak Suppression, anti-aircraft, and convoy bombing is carried out.

. FIRST OPERATIONS STAGE

A. Initiative Declaration Phase
+
The Player who gained the initiative in Stage I now states whether he will be
"Player A" or "Player B" for this particular Operations Stage.

B. Weather Determination Phase
+
The Player with initiative rolls for weather (see Section <<29_0,29.0>>). All adjustments
for unusual weather are made at this time, including any additional evaporation
of Fuel/Water from "Hot Weather.”

C. Organization Phase
+
(The following Segments are undertaken in any order desired).

... Reorganization Segment
+
Attachment and/or assignment of reinforcements, replacements, or any other
non-assigned units including Trucks may be undertaken. Detachment of attached
units may also be done.

... Construction Segment:

.... Construction Completion Step:
Any work scheduled for completion is finished, markers being removed or added as
required. Units that have completed construction may freely be moved.

.... Construction Initiation/Continuation Step:
Any continuing (or ensuing) work on projects is noted. Any units involved in
such work may not be moved (voluntarily) during the remainder of the current
Operations Stage.

... Training Segment:

.... Training Completion Step:
Units and Replacement Points completing a level of training are noted and the
effects in Morale Applied.

.... Training Initiation/Continuation Step:
Any units beginning or continuing training are noted. They may not be moved
(voluntarily) in the remainder of the Operations Stage (exception: Reaction).

... Supply Distribution Segment: Supplies in the same.hex as land units may be redistributed at this time,
subject to the maximum innate capacity of the unit(s) and the hex. Trucks may be
loaded/unloaded:

... Tactical Shipping Strength:
Both Players execute the transport of cargo between African ports. Note: Axis
coastal ships are represented in the game by counters. Allied coastal shipping
is not represented by counters, and is limited only by the port capacities.

D. Naval Convoy Arrival Phase
+
All land and air reinforcements, Replacement Points, and Supplies scheduled for
arrival (and actually arriving) appear in their designated ports of arrival or
entrance hexes. Check Reinforcement Tables and Convoy Rules. The Axis Player
plans for the arrival of future Replacement Points from the Axis Replacement
Points Pool, if he is the phasing Player. In his first Naval Convoy Arrival
Phase of each month, the Commonwealth Player consults the Commonwealth
Production Table and determines how many Replacement Points he will receive one
morith hence and plans for their arrival.

E. Commonwealth Fleet Phase

1. Fleet Assignment Segment: The Commonwealth Player assigns his Ships to any Sea or
Coastal hexes for Bombardment purposes.

2. Fleet Repair Segment: Any Repair work on ships is undertaken at this time.

F. Land Support Air Phase
+
(Only those planes assigned to Land Support Missions may be used in this Phase.)

... _Mission Assignment Segment_:
All planes that are fueled may be assigned Missions by the Player.

... _Mission Deployment Segment_:
Counters representing each type of plane assigned a Mission are placed in their
hex of assignment.

... _Air-to-Air Combat Resolution Segment_:
Combat between opposing aircraft, including any caused by Scramble and
Interception, is resolved. Mission aborts may take place before combat
resolution.

... _Flak Resolution Segment_: Aircraft in the same hex as enemy anti-aircraft
units undergo Flak fire.

... _Mission Completion Segment_: All missions that can be completed (e.g.,
bombing, strafing, etc.) are completed. Aborts may take place here,
too.

... _Return to Base Segment_: All surviving aircraft are returned to their base
of origin (excepting those on transfer missions and some other rare occasions).

... _Tactical Maintenance Segment_: Both Players may attempt to ready all planes
eligible to fly land support missions for the next OpStage.

G. Reserve Designation Phase
+
Player "A" designates which of his units he is placing in Reserve Status,
indicating that with a Reserve marker (see Section <<18_0,18.0>>).

H. Movement and Combat Phase
+
The following four Segments comprise the Movement
and Combat Phase. Player "A" may, if he so wishes, repeat Segments 1 through 4
as many times as he desires within the restrictions of the Continual Movement
rules  <<8_2,8.2>>. Each repetition must include all four Segments.

1. Movement Segment: All units except unattached trucks and tank recovery
squadrons not in reserve and eligible to be moved may be moved.  Non-Phasing
Player ("B") may move units in accordance with the Reaction movement rules (see
Case <<8_6,8.6>>.
2. Breakdown Determination Segment: All
vehicles and Motorized units of both sides are
checked for Breakdown (Section <<21_0,21.0>>. Broken
down vehicles are indicated with an appropriate
marker.
3. Combat Segment:
a. Position Determination Step: Both Players
determine the “position” (Front or Back) of all
Gun and Armor class units. °
b. Barrage Step: Players secretly plot and then
execute any barrages.
c. Retreat Before Assault Step: Player “B”' may
retreat before assault any of his units eligible to
be so moved (see Section <<13_0,13.0>>.
d. Force Assignment Step: Both Players secretly assign TOE Strength Points to anti-armor or
close assault. Player “A” determines which
assaults will be probes (although he need not
reveal this decision) and which TOE Strength
Points will be withheld from assault.
e. Anti-Armor Step: Both of the Players simul
taneously resolve any anti-armor fire, extracting any casualties. Destroyed tank markers are
deployed as required.
f. Close Assault Step: Close Assaults are resolved in any order as determined by Player “A.”
He announces which of them are actually probes
after each is resolved.

4. Reserve Release Segment: Player "A" may
release any of his reserves that he wishes to. ~

I. Truck Convoy Movement Phase Player "A". may move his Second and Third Line
(unattached) Trucks, replacement points and any POW's and Guards.
J. Commonwealth Rail Movement Phase If Player "A" is the Commonwealth Player, he
may utilize rail movement (see Case <<8_7,8.7>> to move land units or supplies.
Otherwise this Phase is omitted.

K. Repair Phase

1. Towing Segment: Player "A" may tow broken
down and recovered vehicles.

2. Maintenance Segment: Player "A" may attempt to repair broken down, or
destroyed vehicles which were not towed in this Phase.

L. Patrol Phase

If the Phasing Player has not engaged in Assault, he may use patrols for
reconnaissance purposes.

At this point, Phases G, H, I, J, K, and L are repeated, except that for "Player
'A' read "Player 'B'",

. SECOND OPERATIONS STAGE

Both Players repeat all facets of the First Operations Stage.

. THIRD OPERATIONS STAGE

Both Players repeat all facets of the First Operations Stage.

. STRATEGIC AIR RECOVERY STAGE

A. Return to Base Phase
+
All surviving planes from missions flown in Stage
Il are returned to their base or origin if possible.

B. Aircraft Maintenance Phase
+
Both Players may attempt to ready planes that have flown missions during the
Strategic Air Stage.

. END OF GAME-TURN

You have now completed one full Game-Turn, replete with airplanes and sandstorms
and the lot!  Congratulations. You may put in for a transfer, but before doing
so, keep in mind that the Russian Front is the only other active Theatre.
