from Infantry (7 x 2 x 3 = 42) and 21 Raw from
his tanks (7 x 3 = 21) for a total of 63 Raw
Points, or 6 Actual. As he has 21 Infantry TOE
Points and only 3 Tank TOE Points, he has no
problems with Combined Arms effects on Assault.
The Commonwealth Player has 10 Raw Infantry
Points (5 x 2 = 10) plus 28 from his Crusaders (7
x 4 = 28) for a total of 38, for a 4 Actual.
However, as he has two more Tank TOE Points
than Infantry (7 to 5), he subtracts 1 Actual Point
for Combined Arms Effects. The Basic Differential is thus 6 to 3, or +3 for the Axis.

Each Player now checks for his actual Morale at
time of Assault. The Axis Player has a +2 Basic
Morale with a Cohesion Level of — 2; he consults
the Morale Modification Table, throws a 21, and
gets a No Change to his Basic Morale. So his Adjusted Morale is +2. The Commonwealth Player
has a Basic Morale of + ! with a Cohesion Level of
— 3, Using his —3 Cohesion he also consults the
Morale Modifier Table, throwing a 53. This results
in a modification to his Morale of ~ 2, for an Adjusted Morale of —1. Comparing his Morale to
that of the Axis Player shows a Finalf Adjusted
Morale of +3 (+2 — [~1] = +3). This +3
means that the Axis Player will adjust the Assault
Differential Column three in his favor. However,
the Commonwealth units are in Rough Terrain,
which is a two-column adjustment in their behalf,
so the final column adjustment is +1 for the Axis.
(There is no question of a unit Size/Organizational
Difference here.) Thus, with a Basic Differential
of +3, and a one-column adjustment for the Axis,
the assault takes place on the +4 Column.

Each Player now throws two dice and consults his
portions of the Assault Combat Results Table to
determine his losses. The Axis Player throws a 32.
That means he loses 5% of his Assaulting Force,
and there are no other results for him (i.e., he is
not Engaged). The Commonwealth Player throws
a 21. He has several results from this: (1) He loses
15%; (2) He has 33% of these Captured (an additional die roll of 4); and he must Retreat all his
units at least one hex (or take an additional 10%
loss, which would further affect the Captureds).

The Axis Player Assaulted with 63 Raw Points,
which he multiplies by his 5% Loss to get 3.15, or 4
Raw Points (the Attacker always rounds upwards). He removes two Infantry TOE Points
(onefrom each of two battalions) to absorb the 4
Raw Points (each of his Infantry has an Assault
Offensive Rating of 2, so 2 TOE of these equals 4
Raw Points). In addition, the Axis Player has his
Artillery forward, so he must remove 50% of his
Raw Points Lost in terms of Vulnerability Points.
This means he has lost 2 Points (Vulnerability) of
Artillery. As each 105mm Gun has a Vulnerability
of 9, he would have to remove one of his Guns to
absorb the 2 point loss. The Axis Player's losses
are thus 2 TOE Points of Infantry (or about
200-300 men), 5 Panzers (1 TOE), and 1 TOE of
105mm guns (or 4 guns, for this type of gun).

The Commonwealth Player now determines his
losses. He used 38 Raw Points; but he also has Pinned Stuarts, which must be included in the total.
There are 8 TOE of these, with a Defensive Assault
Rating of 4, for a total of 32 Raw, for a Grand
Total of 70 Raw Assault Points. His losses are
15%, or 10.5 Raw Points, rounded down to 10. Of
these, 33% are captured, or, rounding upwards, 4
Raw Points Captured. The Commonwealth Player
has 2 Infantry TOE Points Captured (to absorb
the 4), and eliminates | TOE of Stuart Tanks (4
Raw) and 1 more Infantry Point (2 Raw) to satisfy
the 10 Points lost. He then Retreats his entire
Force one hex, rather than incur additional losses.
He has had about 150 men killed, about 300 men
captured, and lost 5 Stuart and 10 Crusader
Tanks. He has also lost his position.

The Commonwealth suffers no additional losses
to his Cohesion Level, aside from those earned in
moving the one hex (to Retreat), However, the
Axis Player earns three Reorganization Points for
pushing the Commonwealth Player out of the hex.

[16.0] PATROLS AND
RECONNAISSANCE

GENERAL RULE:

Patrols may be conducted in order to determine
the identification and strength of opposing units.
In any Operations Stage in which no Anti-Armor
or Close Assault combat has taken place a Phasing
Player may "pull" men out of certain types of
units to patrol in the Patrol Segment. To patrol,
the Phasing Player announces how many Patrol
Points are Reconnoitering a given hex. He consults
the Patrol Survival Table, takes losses, if any, then
refers to the Reconnaissance Table to see how effective his patrol has been. Depending on his success on the Reconnaissance Table, the nonPhasing Player must tell him information about a
given number of units. No units actually move
during patrol; patrolling is handled abstractly.

PROCEDURE:

To patrol, the Phasing Player announces the
number of Patrol Points he wishes to allocate to a
given patrol, expends the necessary fuel and ammunition, and states which hex is being patrolled.
He consults the Patrol Survival Table (16.6) and
rolls one die to determine any Patrol casualties
(unless no combat units are present in the hex; see
Case 16.32). If Patrol Points remain (that is, if the
patrol is not wiped out), the Phasing Player rolls
one die and cross-references the result with the
number of remaining Patrol Points on the Reconnaissance Table (16.7) to determine what (if any)
information his patrol garners. The non-Phasing
Player must now reveal information as required by
the results of the die roll. Finally, the Phasing
Player rolls one die and consults the Objective
Loss Table (16.8) to determine if there are any
non-Phasing unit casualties and, if so, they are extracted.

CASES:
[16.1] WHICH UNITS MAY PATROL

[16.11] Only Recce-type, Light Tank (Italian
CV/33's, British Mark VI Lights, or German
Panzer I's), or Motorized Infantry may supply
Patrol Points for Reconnaissance.

[16.12] The Phasing Player subtracts — or rather
detaches — TOE Strength Points from the
unit/TOE types allowable (Case 16.11) and
designates them as Patrol Points. Example: a
Phasing Player detaches two Recce TOE Strength
Points from a Recce battalion in Hex A and
assigns them as Patrol Points to Reconnoiter
Enemy-occupied Hex B. The Player notes on his
TOE Log sheets the assignment and any resultant
casualties.

[16.13] No more than 2 TOE Strength Points may
be assigned as Patrol Points from any one hex,
regardless of the number of units in that hex..

[16.14] The maximum number of Patrol Points
that may be sent to an Enemy-occupied hex is 3,
with Patrol Points from different hexes having the
capability of combining forces for a Reconnaissance operation.

[16.15] No unit with a Cohesion Level of —8 or
worse may assign TOE Strength Points to patrol
duty.

[16.16] For each Patrol! Point sent out on Reconnaissance, the Phasing Player expends one Am
munition Point and 2 Fuel Points. These supplies
must be present in the hex the Patrol Points
originate from, and they are expended regardless
of the result of the patrol.

[16.17] No Patrols may originate from or be
directed into any hex affected by a Rainstorm or
Sandstorm.

[16.2] RESTRICTIONS ON
PATROLLING

[16.21] In any Operations Stage that a Phasing
Player does not engage in Anti-Armor Combat or
Close Assault against any Enemy units, he may
patrol. In addition, although a Player may patrol
if he has used Artillery Barrage during a given
Operations Stage, he may not Reconnoiter any hex
which has undergone any type of Barrage or Air
Bombardment. A Phasing Player may launch as
many patrols as he wishes.

[16.22] Patrol. Points may reconnoiter any
Enemy-occupied hex within five hexes of the hex
the Patrol Points originate from. The five-hex
path may not include any terrain impassable to the
units in the patrol (see Case 16.11), nor may they
pass through an Enemy-controlled or occupied
hex other than a hex in the Zone of Control ofthe
unit being reconnoitered.

[16.3] PATROL LOSSES

[16.31] Both Players — the Patroller and the
Patrollee — must check for any possible combat
losses from Patrol action. However, each Player
checks at a different time.

[16.32] The Phasing Player, after assigning his
Patrol Points to Reconnoiter a specific hex, consults the Patrol Survival Table before reconnoitering, with one exception. The non-Phasing Player
must inform him if there are no combat units in the
hex which is being reconnoitered. If there are no
combat units in that hex, the Phasing Player skips
the Patrol Survival Table and suffers no losses.
AA/Flak and Engineer units are not combat units
for this purposes.

[16.33] The Phasing Player now rolls one die and
consults the Patrol Survival Table. If ¢// his Patrol
Points are from Recce units he subtracts one from
the die roll. Any losses — in TOE Strength/Patrol
Points eliminated or captured by the non-Phasing
Player (including trucks) — are deducted immediately (Phasing Player's choice as to unit
type), Captured Points become Prisoner Points.
Ifno Patrol Points survive, the Phasing Player
goes no further; he gets no information.

[16.34] After the Phasing Player has gotten his information, or after having had all his units
eliminated (whichever comes first) the Phasing
Player rolls another die to see whether he has inflicted any losses on the non-Phasing Player,
regardless of the losses he (the Phasing Player) has
taken. There is one exception to this: if the Phasing Player's patrol is eliminated in entirety, the
Captured result on the Objective Loss Table
becomes an Eliminated. The choice of loss (in
TOE Strength Points) is up to the non-Phasing
Player, but it must come from a combat unit. If
there are no combat units, the non-Phasing Player
may eliminate either Truck Points, AA/Flak
Points, Engineer Points, or HQ Points, in that
order of priority.

[16.4] DUMMY TANK FORMATIONS

Dummy Tank Formations consisted of mock-ups
of Tanks, usually made from wood or canvas
covered cars (the Germans used Volkswagons),
designed to fool Enemy intelligence into thinking
there were Tank Brigades in places where they
weren't.

[16.41] Each Player may use Dummy Tank Formations. These are the equivalent of Tank battalions in size, but they are worth nothing in combat. Their CPA is zero.

[16.42] To bring a Dummy Tank battalion into
play, a Player must expend 10 Stores, which must
be present in the hex in which the Dummy is
“placed.'? Dummy Tank battalions are placed in
the Construction Segment. There are no actual
counters for Dummy Tanks.

[16.43] No Player may ever have more than three
Dummies in existence at any one time. No more
than one Dummy may be in any one hex. No
Italian formations may ever make use of Dummies, even when mixed with German formations.

[16.44] Dummy Tank battalions may be assigned
identifications actually used by other Tank battalions in play. Example: The Commonwealth
Player may say Dummy Tank Battalion #1 is the
4th Royal Tank Regiment, even though the 4 RTR
is in play elsewhere on the game-map.

[16.45] Dummies really have only one function:
to confuse Enemy intelligence. Thus they are
worthless alone in a hex. Whenever a Player conducts Reconnaissance against an Enemy hex, the
Enemy Player, if he has a Dummy Tank unit in
that hex, may tell him that he has the "X" Tank
battalion of any TOE Strength desired, when
revealing information. The patrolling Player has
no way of knowing that this is a dummy or not (until he attacks).

[16.46] If a formation with a Dummy Tank battalion undergoes any type of Close Assault, the
Dummy Tank Battalion is eliminated. If a formation undergoes Anti-Armor fire and has no armor
— or loses all its armor — the Dummy Tank Battalion is eliminated. Anti-Armor fire committed
against Dummy Tanks may not be switched to
Assault if the only "armor" is Dummy Tanks!

[16.47] For the historians, The Household
Cavalry Regiment, a Commonwealth Armored
Car unit, was assigned to North Africa. However,
it does not appear in the OA Sheets as it saw
minimal action and was assigned mainly to handling the task of fitting out and overseeing the
Commonwealth Dummy Tank Formations.

[16.5] RESULTS OF PATROLS

The Reconnaissance Table (16.7) results are expressed in terms of the number of battalion-size
units about which the non-Phasing Player must
reveal information. Thus, if the Phasing Player
has two Patrol Points and obtains a die roll of 4, he
will be told about two of the Enemy's units.

(16.51] The non-Phasing Player must reveal the
following information about units: historical
designation (e.g., 1/8 Panzer Battalion), type of
unit (mechanized infantry, armored cars, etc.),
whether the unit is motorized or not, and the exact
TOE Strength within two of the actual strength at
the time of the Patrol.

[16.52] The non-Phasing Player may choose the

‘units in a hex about which he will reveal the information listed in Case 16.51, if more of his units are
in.the hex than he is required to give information
about (exceptions: see Case 16.53, 16.54, and
16.55).

[16.53] Information must be revealed about
battalion-sized units, unless only smaller (or
larger) units are present.

[16.54] Information may not be revealed about
HQ units or AA/Flak units unless there are no
combat units in the hex. Information may be
revealed about Engineer units.

[16.55] The Phasing Player may specifically list
units about which he does not wish to receive in
formation, and the non-Phasing Player may not
choose such units to satisfy the requirements of
Case 16.5. (Presumably, such units would be ones
that the Phasing Player already had adequate information about, because of previous patrols or
combats.)

[16.6] PATROL SURVIVAL TABLE
(see Charts and Tables)

[16.7] RECONNAISSANCE TABLE
(see Charts and Tables)

{16.8] OBJECTIVE LOSS TABLE
(see Charts and Tables)

[17.0] MORALE

GENERAL RULE:

The Morale Rule in CNA attempts to quantify a
facet of combat that is so. subjective that it virtually defies all such attempts. The result: subjective
opinion plays an important part in what is otherwise a highly objective game. In any case, the
Morale rules combine the elements of a Basic
Morale Rating (representing initial training,
fitness, enthusiasm, secondary command capability, etc.), which is a fixed number (with one exception; see Case 17.3), with the effects of constant
campaigning and victory or defeat. The Cohesion
Level of a unit is used to raise or lower the Morale
Rating of a unit at the instant of Close Assault.
This adjusted Morale Rating is then compared
with that of the opposing Player to adjust the
Assault Differential one way or the other.

CASES:

[17.1] UNIT BASIC MORALE RATINGS

Each unit in the game has a Basic Morale Rating,
listed on its OA Sheet, which, with the exception
of Training (Case 17.3), never changes (although it
may be adjusted by Cohesion for individual
assaults). The Morale Ratings run from +3 to
—3. The Basic Morale Rating of a battalion (or
brigade) is always that of its assigned Parent Formation, unless the unit has been attached to
another force or has been out onits own.

[17.2] ADJUSTMENTS TO BASIC
MORALE RATINGS

[17.21] Every time a unit is involved in a Close
Assault (or Probe) its Basic Morale Rating may be
adjusted by its Cohesion Level at the instant of
Assault. The effect of Morale on Assault has been
discussed in Case 15.6.

[17.22] In order to determine the effect of a unit's
Cohesion Level on its Basic Morale Rating, the
Players use the Morale Modification Table (17.4).
This is another table that uses a two-dice sequential read out (11-66), with the diceroll taking up the
“‘center" of the Table. In this case, the Cohesion
Level of the unit is on the left, comprising the rows
of the Table, while the Morale Modifier — the
number the Player is rolling for — is on the top of
the Table, comprising the columns. Example: A
unit has a Basic Morale Rating of +1. It goes into
an Assault with a Cohesion Level of —4. The
Player consults the Morale Modification Table
and throws two dice, getting a 42. Locating the
row for —4 Cohesion, the Player reads across until he finds the column in which a diceroll of 42 is
located. That roll is in the —2 column, so the
Morale Modifier is —2, and the Basic Morale is
adjusted by that number (+1 —~2 = —1). The
unit's Adjusted Morale Rating for that Assault is
-1.

[17.23] The maximum Adjusted Morale Rating a
unit can ever have is +3, and the minimum — 3,
regardless of what mathematical possibilities occur. Thus a unit with a +2 Basic Morale Rating
that earns a + 4 modifier does not get an Adjusted
Rating of +6, but just +3 (exception: see Case
17,28).

[17.24] Ail Cohesion Levels of ~— 17 or worse use
the "- 17 et seq'? row. All Cohesion Levels of +8
or higher use the " + 8”' row.

{17.25] The farthest column on the right is the
Surrender column. If a combination of Cohesion
Level and diceroll places the Modifier in that column, the affected units immediately Surrender
(and become Prisoners, see Section 28.0; Exception: Case 17.26). If both units, for some strange
reason, get a Surrender Modifier, the Surrenders
are ignored, no assault occurs, and both sides are
Engaged.

[17.26] If a unit or a Formation with a Basic
Morale (individual or combined) of + 1 or better is
involved in a Morale Adjustment computation,
such unit follows the Morale Adjustment Table
normally with one exception: it ignores all Surrenders (treating them as a —4 adjustment).
However, it does not ignore the "Surrender" it
one of the following is in effect:

a. The unit has a Cohesion Level of ~11 or
worse; or

b. The Enemy unit(s) has af least 3 times the
Strength (Enemy Raw Offensive Assault to
Friendly Raw Defensive Strength).

[17.27] It is possible that a given Player has units
of different Cohesion Levels in the same assault.
The method of determining the applicable Cohesion Level is the Largest Unit Rule, discussed in

Case 6.27.

XXXX
obs
Rommel
DAK

[17.28] Axis units stacked with General Rommel
at the instant of Assault have their Adjusted
Morale Rating further adjusted by +1. Thus a
unit with an Adjusted Morale Rating of 0 that is
assaulting under the direct command of Rommel
has an Adjusted Morale Rating of +1.

[17.3] TRAINING

Several of the Commonwealth units arrived in
Egypt ill-prepared to fight a desert campaign.
Therefore, their Morale Rating on arrival is lower
than their assigned Basic Morale. In order to reach
their assigned Basic Morale they must undergo
Training.

To forestall questions on the subject, only
Commonwealth units must undergo training for a
variety of reasons. Most German units had already
undergone considerable combat before arriving in
Africa, and, although they were no more desertacclimated than any other forces, this previous experience counted for much, in the designers'
minds. As for the Italians, most of these units had
served in Africa, had seen, combat, or are of too
low a designated morale to bother with training.
Those Commonwealth units designated for Training are based on unit descriptions and fitness
reports in the various sources. .

{17.31] Units that are in need of Training have, on
their OA Sheets, two Basic Morale Ratings. The
rating in parentheses is the Untrained Rating: the
other Rating is the maximum level of Training and
Experience that that unit may reach, through
Training.

17.32] A Commonwealth unit undergoes Training in any one of three areas: Cairo (any one of the
city hexes); Helwan (1430); or Alexandria (any city

27

28

hex), or Amiriya, Abougir or Deghelia.

[17.33] To undergo Training a unit may not expend any Capability Points during an Operations
Stage. If, for any reason whatsoever, a unit expends CP's during an Operations Stage, its Training has been interrupted.

[17.34] For every six Operations Stages that a unit
undergoes Training, it raises its Untrained Basic
Morale Rating one point. (Thus, a —1 would
become a 0, a +1 a +2, etc.) It may never exceed
its designated Basic Morale.

[17.35] In order for a unit to undergo Training, a
combat battalion which has (or has reached) its
designated Basic Morale must be present in the hex
with the Training unit during each Operations
Stage of Training. Infantry divisions or brigades
may use an Infantry-type battalion; any unit with
tanks must have a Tank battalion present to train.
Such instruction battalions do not count against
stacking limitations, and such battalions used for
instructional purposes must be at least '4 of their
assigned TOE Strength. Each instruction battalion
may train as many units as may be stacked in that
hex, ;

[17.36] Units are not required to undergo Training; they may enter combat with their lesser
Morale Rating and then be pulled back at a later
time for Training. However, only Training can
permanently raise the Basic Morale Rating,
regardless of the amount of combat encountered.

[17.37] Commonwealth And Axis (see Case
20.43) Training Areas are indicated on the game
maps.

[17.4] THE MORALE MODIFICATION
TABLE (see Charts and Tables)

[17.5] VOLUNTARY SURRENDER
OF UNITS

A Player's units may be captured thru lack of combat ability or be forced to surrender as a result of
morale determination during a Close Assault, lack
of ammunition of possessing 26 or more
Disorganization Points. A player may voluntarily
Surrender his units under certain conditions.

[47.51] A Player may voluntarily surrender units.
The surrendered units are treated as though they
were captured or involuntarily surrendered (e.i.,
create prisoners for the infantry and turn the
tanks, guns, and aircraft into replacements).

[17.52] In order to voluntarily Surrender the
following conditions must be met:

A. The event is not occuring during Step "b”' thru
‘<f?? of a Combat Segment.

B. All of the units, Replacement Points, etc. in
that hex at that instant are being surrendered.

C. The surrendering units must be adjacent to an
Enemy combat unit and be able to be moved
directly into that unit's hex.

[17.53] Units may be surrendered to an Enemy
combat unit of any size or status (except 17.54).

[17.54] The enemy unit must accept the surrender,
expending 2 CP's to do so. If the Enemy unit cannot expend 2 CP's the units may not voluntarily
surrender.

[17.55] The owning Player may attempt to
destroy part of the unit's material at the instant of
voluntary surrender. This may only occur after he
has declared that units in a hex are being voluntarily surrendered. The Player may not attempt to
destroy anything that may not be moved or may
only be moved in his Phasing Truck Convoy or
Repair Phase.

[17.56] The Player may attempt to destroy any
portion of his eligible material. Two determina
tions are made, one for tanks and guns and one for
trucks/Motorization Pointr The Player determines how his attempt at destroying tanks and
guns has fared by rolling one die, subtracting one
from the die roll and then multiplying by 10%
(e.g., aroll of 4 results in the destruction of 30% of
all designated tank and gun TOE Strength Points).
Trucks/Motorization Point destruction is determined in a similar manner except that the modified
die roll is multiplied by 20%. Round fractions
down.
{17.6] TRAINING CHART

(see Charts and Tables)

[18.0] RESERVE STATUS
COMMENTARY:

The Reserve Rule was prompted by the unusual
Time-in-Space problems encountered using the
Capability Point Allowance System and Continual
Movement. It protects the Defender from having
the Phasing Player perform feats of incredible
speed and agility far out of synch with the Laws of
Motion, Time, and Inertia while, at the same time,
enabling the Phasing Player to hold back certain
units to exploit holes in the line. In essence, units in
Reserve — not moving while the other units are —
are still consuming "time" while they stand. Thus
their capability to move and fight is reduced according to how long they spend in Reserve.

GENERAL RULE:

Reserve is a status which enables units to circumvent the rule that states a unit must be within two
hexes of an Enemy unit to take advantage of the
Continual Movement Concept. Units are placed in
Reserve Status in the Friendly Reserve Designation
Phase. At varying times during the Movement/Combat Phase the Player has the opportunity to pull a unit out of Reserve and use it, with
varying degrees of restrictions, dependent on the
length of stay in Reserve.

CASES: Reserve
[18.1] WHICH UNITS MAY BE 1
PLACED IN RESERVE

[18.11] Any units belonging to the Phasing Player
may be placed in Reserve. The non-Phasing Player
may not place units in Reserve.

[18.12] Units assigned to Reserve Status must be
so designated in the Reserve Designation Phase of
the Operations Stage. Units are so designated by
placing a Reserve I marker on top of them.

{18.13] Units still in Reserve during the first
Reserve Release Segment of each Movement/Combat Phase, must either be released or
have their Reserve I marker flipped over to its
Reserve ET side.

(18.14] Units in Reserve II Status remain in that
status until either they are released in a subsequent
Reserve Release Segment of that Operations Stage
or the Operations Stage ends.

[18.15] Units may be placed in Reserve only in the
Reserve Designation Phase. No unit may be placed
in Reserve during the Movement/Combat Phase.

[18.2] EFFECTS OF RESERVE STATUS

[18.21] There are two states of Reserve: Reserve I
and Reserve IT. The Reserve marker on top of the
units indicate their current Reserve Status.

[18.22] In a Movement Segment, units in Reserve
I status may move one hex (regardless of Capability Point expenditure) as long as they do not enter
an Enemy-controlled hex. Units in Reserve IT
status may never move.

[18.23] A unit in Reserve / status may be released
from such status in the Reserve Release Segment in

the first Reserve Release Segment in that Operations Stage; i.e., after other units have been moved
once. Such a released unit may then move and
fight in the ensuing Movement and Combat
Segments with the following restrictions:

1. It may not voluntarily exceed its Capability
PointAllowance in that Operations Stage; and

2. lt may engage in only one offensive Close
Assault in that Operation State.

[18.24] A unit in Reserve IT Status may be released
in any Reserve Release Segment subsequent to the
first Reserve Release Segment of a given Operations Stage. Such a unit may then move and fight
with the following restrictions:

1. It may' not voluntarily exceed one-half its
Capability Point Allowance (rounded down) in
that Operations Stage. Thus, a non-motorized infantry unit emerging from Reserve II Status would
have a CPA of ‘5' that Operations Stage, which it
could not voluntarily exceed; and

2. It may engage in only one offensive Close
Assault (or Probe), within the restrictions of (1),
above, in that Operation Stage; and

3. If it does voluntarily engage in any Close
Assault, Anti-Armor or Barrage that Operations
Stage it automatically earns one Disorganization
Point, in addition to any others it might earn.

[18.25] Units released from Reserve may be moved (in the immediately subsequent Movement Segment only) even if they are not within two hexes of
an Enemy unit, which is an exception to Case 8.23.

[18.26] Placing a unit in and releasing it from
Reserve Status does not cost any Capability
Points.

[19.0] ORGANIZATION AND
REORGANIZATION

COMMENTARY:

As has been discussed previously in a variety of
sections, the Organization of the various units —
i.e., which battalions are part of which Brigade,
which Brigades and support units form which
Division, etc. — is important to the play of the
game, particularly as pertains to Stacking. The
basic Organizational heirarchy is pyramidical: 2-3
battalions form a brigade, and 2-3 brigades forma
Division. This Section discusses which units are
Assigned to a Parent Unit and which units may be
Attached, how to Attach and Detach units, and
when and how units may be built up to maximum
strength,

Important: Players should be aware that this Section is one that could cause considerable problems
unless certain basic tenets are understood. First of
all, this Section is an attempt to formulize
Organizational Doctrine; the Players are being
forced to mold and use their armies in much the
same way as the commanders did 30 plus years
ago. And if it frustrates the Player not to be able to
do things that are clearly beneficial, imagine how
it was to those actually fighting this campaign.
Furthermore, these Organizational rules are not,
and should not be, considered as strict, rigid proscriptions. Rather, Players will find them easier to
use if they attempt to understand the principles
underneath them, and then use the accompanying
charts and tables as guides. The charts and tables
reflect the maximum Attachments and
Assignments; anything within those limits can certainly be accomplished. Most of all, this Section
should be played with attention to the flavor and
meaning of the campaign which is being fought.

GENERAL RULE:

Each unit represented by a counter in the game is

either independent or assigned and/or attached to
a Parent Formation. Companies, battalions, and
brigades may be assigned and/or attached; division HQ units are always independent. Divisions,
brigades, and battalions may have subsidiary units
attached or assigned to them (i.e., be Parent Formations). Historical assignments are listed on the
Organization at Arrival Chart (O/A Chart, see
Case 4.4); within limits, Players may alter these
assignments. Players may more freely alter attachments. Limitations on such alterations are generally related to the capacity of the Parent Formation(s) to absorb subsidiary units. The historical
TOE of battle (not the units themselves, but how
many of each type there were) of every potential
Parent Formation is listed on the Formation
Organization Chart (19.3). Restrictions on additional attachments are listed for each Formation
on the Maximum Unit Attachment Chart (19.5).

[19.1] DIFFERENCE BETWEEN
“ASSIGNED” AND
“ATTACHED” UNITS

[19.11] A unit is assigned to a specific Parent Formation if that unit is considered a part of that
Parent Formations organization (e.g., the 8th
Panzer Regiment — a Brigade equivalent, see Case
9.2 — begins the game assigned to the 15th
Panzer Division).

[19.12] A unit is attached to a specific Parent Formation if the counter representing the Parent Formation on the map represents the attached unit as
well. (i.e., not only are both the attached unit and
the Parent Formation in the same hex, but they are
functionally combined into one unit).

[19.13] It is possible for the same unit to have two
different Parent Formtaions simultaneously, one
to which it is assigned, and one to which it is attached. A unit may never be attached to more than
one Parent Formation at once; nor may a unit ever
be assigned to more than one Parent Formation at
once. Note: A unit must be in the same hex as a
Parent Formation to which it is attached (indeed,
it is represented on the game-map by the Parent
Formation's counter); it need not be in the same
hex as a Parent Formation to which it is assigned.
Of course, a particular unit may be both assigned
and attached to the same Parent Formation.

[419.14] It is possible for the same unit to be a
Parent Formation and to simultaneously be, in
turn, assigned and/or attached to another (higher
level} Parent Formation. Note that the units attached to a particular Parent Formation may affect whether or not it can be attached in turn to
another unit.

Example: If the lst Kings Royal Rifle Corps was
detached from the 7th Armored Division (its
assigned Parent Formation) and sent to support
the 2nd New Zealand Division; the Ist KRRC,
when absorbed by the 2nd NZ would become attached to one units and assigned to another.

[19.2] UNIT ASSIGNMENTS

Each Parent Formation (or potential Parent Formation) has an inherent set of limitations on the
number and/or type of subsidiary units which may
be assigned to it. These limitations are listed on the
Formation Organization Chart (19.3). Example:
An Italian armor Brigade may have assigned to it
three armored battalions.

Units enter the game already assigned to a specific
Parent Formation. Assignments are generally permanent, with excepetions for eliminated units for
historical assignment shifts and assignment pattern shifts, and for British battalions, as detailed
in the following Cases. Any new assignments or reassignments are accomplished during the Player's

Reorganization Segment and recorded on the appropriate Parent Formation's TOE Log Sheet.

[19.21] Any Parent Formation which has fewer
units assigned to it than its maximum (see Case
19.3) may be assigned additional independent
(non-assigned) units up to that limit (e.g., If only
two armored battalions were attached to an Italian
armor brigade, the Axis Player could, in his
Reorganization Segment, assign any independent
Italian armored battalion to that brigade). In
order to be assigned to a Parent Formation, an independent unit must be currently attached to it.

{19.22] Should a unit's assigned Parent Formation be eliminated, (see Case 19.11), if that — presumably detached — unit survives, it is considered
independent and eligible for re-assignment in accordance with Case 19.21 and 19.3.

[19.23] Should an assigned unit be eliminated, the
assignment is considered terminated and another
independent unit may be assigned to the Parent
Formation in the eliminated unit's place. (i.e.,
eliminated units do not count towards the limitations listed in Case 19.3).

[49.24] The OA Chart (Case 4.45) contains notes
concerning historical shifts in assignment relationships for several units. Players are free to either institute or ignore such assignment shifts at their option, within the restrictions of Case 19.21 (see also
Case 19.25). Such re-assignments must be accomplished sometime during the month listed on
the OA Chart note, or not at all.

Example: When the German 15th Panzer Division
arrives it contains the 115th Panzergrenadier
(motorized infantry) Regiment, albeit in a
somewhat reduced state. At a later date, listed in
the notes of the 15th Panzer and S5th/21st Panzer
divisions, that the 115th Regiment, originally
assigned to the 15th Panzer, becomes part of the
21st (nee' 5th Light) Panzer Division, taking on
some additional units to flesh out its structure. If
the Player wishes to switch the 115th to the 21st
Panzer Division, the 115th would then be assigned
to the 21st Panzer as per this case.

[19.25] As indicated on the Formation Organization Chart (19.3), the historical assignment limitations on Commonwealth armored divisions and
brigades changed three times. The Commonwealth Player may, at his option, assign available
independent units to such Parent Formations
when these changes allow additional units to be
assigned, The Commonwealth Player must "unassign" excess units whenever new, limitations require him to doso.

[19.26] A special rule applies to Commonwealth
Brigades (both Infantry and Armor). Throughout
the war, the Commonwealth made it a practice to
shuffle individual battalions from one "assignment" to another. This was especially prevalent in
the Indian units, where battalions like the 2/5
Mahratta Light Infantry appears virtually everywhere. Therefore, the Commonwealth Player is
permitted to pull assigned battalions from a
Brigade and replace them with others from
another Brigade (or from the unassigned group).
Such battalions are then considered assigned to
their new Brigade. Battalions may only be reassigned or shuffled; they may not simply be "unassigned" and made independent. Example: The
2nd Armored Brigade (1st Armored Division) may
pull the 10th Royal Hussars and 9th Lancers out,
send them to Alexandria for refitting (with,
perhaps, new tanks, etc.) and replace them with
the 4th and 7th Royal Tank Regiment. The latter
two units are now assigned to the 2nd Armored
Brigade.

[19.27] Some units (designated with an asterisk on
their counters) are assigned to Parent Formations

that never made it to Africa. Except in accordance
with Case 19.26, such units may not be reassigned.

[19.28] Only independent units may be assigned
to a Parent Formation. No unit assigned to one
Parent Formation may be assigned to another, except as noted in Case 19.26.

Remember: Assigned units take up "space" in a
Parent Unit's TOE, regadless of where they are.
Even if not attached, an assigned unit occupies its
allotted space in the Parent Unit's TOE.

[19.3] FORMATION ORGANIZATION
CHART
(see Charts and Tables)

The Formation Organization Chart lists the
assignment limitations of "normal" units of divisional and brigade level. The maximum number of
assigned units of each type that make up the units
normal organizational structure are listed. A
number of units have singular organizational
structures, as noted on the OA Chart; such units
are limited by those strictures, and not by any
listed on the Formation Organization Chart.

[19.31] Allied Formation Organization Chart
(see Charts and Tables)

[19.32] Italian Formation Organization Chart
(see Charts and Tables)

[19.33] German Formation Organization Chart
(see Charts and Tables)

[19.4] RESTRICTIONS ON
ATTACHMENT AND
DETACHMENT

Any units assigned to a particular Parent Formation may freely be attached to or detached from
that Parent Formation. Most Parent Formations
may have some number of additional nonassigned units of certain types, over and above
their assignment limits, attached to them. These
attachment limits are listed on the Maximum
Attachments Chart (19.5). Non-assigned units
may also be substituted for "missing" assigned
units (Case 19.45),

[19.41] A unit assigned but not attached to a
Parent Formation may become attached to that
Parent Formation at any time so long as both units
are in the same hex, at.a cost of one Capability
Point each to both the subsidiary unit and the
Parent Formation. The counter representing the
attached unit is removed from the map. Note that
moving such a unit into the hex with the Parent
Formation (or vice versa) and immediately attaching it would have no effect upon the Stacking
Point value of the Parent Formation (unless if it
was a Shell; see Case 9.26).

{19.42} A unit not assigned to a Parent Formation
in the same hex may be attached to that Parent
Formation subject to the restrictions of Cases 19.4
and 19.5 (if applicable) at a cost of two Capability
Points for both units during the owning Player's
Reorganization Segment, only. Note that the unit
would have to be moved into the hex containing
the Parent Formation (or vice versa) during an
earlier Movement Segment, subject to all stacking
restrictions.

[19.43] A unit assigned and attached to a particular Parent Formation may be detached from
that Parent Formation at any time at a cost of one
Capability Point to both units.

[19.44] A unit attached but not assigned to a
Parent Formation may be detached from that
Parent Formation only during the owning Player's
Reorganization Segment or Movement Segment
at a cost of one Capability Point each to both
units. However, note that units are moved individually or.as a stack, and once stopped, can be

30

moved no further. Thus, jf a unit is detached from
a Parent Formation during a Movement Segment,
movement of either the detached unit or Parent
Formation must cease (unless they are moved on
as a stack).

[19.45] A unit(s) may be attached to a Parent Formation that has fewer units assigned to it than the
maximum restrictions listed on the Formation
Organization Chart (19.3) as a substitute for the
“‘missing" (that is, not in the games, or reassigned as per Case 19.66) unit(s). Such a unit
must not exceed, in its own organizational structure, the maximum limits that would apply to the
missing assigned unit it is being substituted for.
Example: If one infantry brigade assigned to a
Commonwealth infantry division were eliminated,
the Commonwealth Player could attach an -independent infantry brigade to that division as a
substitute. He could not, however, attach an infantry brigade to which more than three infantry
battalions were assigned as a substitute, since that
unit would exceed the applicable Formation
Organization limits.

[19.46] A unit attached to a Parent Formation
which is itself in turn attached to a larger Parent
Formation is considered attached to the larger
Parent Formation also. Note: This requirement
may render it impossible (unless detachments are
made) to attach a certain unit to a Parent Formation because other units attached to the first unit
cannot be fitted into the Parent Formation's
organizational structure. Exception: Units attached to a Parent Formation in turn attached to a
larger Parent Formation in accordance with Case
19.45 do not count as being attached to the larger
Parent Formation.

[19.47] Any units currently attached to a Parent
Formation may be detached in such a way that
they end up attached to one another at a cost of only the Capability Points required for detachment.

For example, the 132nd Regimente Corazzate and
the Nizza Cavelleria Regiment are detached fromthe Ariete Division. The N.C. Rgt. may be attached to the 132nd R.C. at this point without any additional expenditures.

[19.5] MAXIMUM ATTACHMENT
CHART
(see Charts and Tables)

The limits listed on this chart apply to all units of
the indicated size and type, regardless of whether
or not the unit's organization is "standard'”' (i.e.,
whether it appears on the Formation Organiztion
Chart, 19.3) or not.

[19.6] REBUILDING DEPLETED UNITS

The method of replacing TOE Strength Points
and/or Rebuilding units is covered in Replacements (Case 20.4). It should be pointed out here,
however, that no unit may ever be rebuilt or
augmented to the point that it exceeds its printed
ID Code Maximum TOE Strength. Example: The
Italian Light Tank battalionsmay never have more
than nine TOE Strength Points of Tanks.
(Whether these can be Light and/or Medium is
covered in Case 19.64).

There are some cases, albeit rare, where the arriving TOE Strength is below the "paper" strength of
the unit. This fact is usually listed in the TOE &
Weapon System(s) section for that unit, and the
Players may increase these units accordingly.

[19.61] Units that have been depleted (reduced) by
combat, attrition, etc., may be augmented by
Replacements (see Case 20.4). No unit may ever be
increased above its stated maximum TOE Strength
Level (listed in the OA Chart for that unit).

{19.62] Units that have been completely
eliminated because of attrition on combat—not
breakdown (i.e., no TOE Strength Points remaining) may not be rebuilt. However, HQ units that
have lost aff their assigned battalions may have
new battalions assigned (up to the number listed
on the OA Chart) as long as the HQ unit exists asa
cadre.

[19.63] If a HQ unit (counter) is eliminated, it
may not be rebuilt unless at least 50% of its assigned units still exist and are not attached to other
units. In such case, two Infantry Replacement
Points may be used to revive the HQ, Otherwise it
is gone for good.

[19.64] The use of Replacement Points is covered
in Case 20.4. However, the following principles
apply in using Replacement Points to rebuild
units:

a. Infantry Replacement Points may be used to
rebuild a wide variety of Infantry-type units, as
well as HQ and Engineer units;

b. Artillery units may be rebuilt with any type of
artillery guns. (Commonwealth Players may want,
for historical purposes to limit their Medium
Regiments to their Medium Guns and Field
Regiments to their Field Guns, etc., but this is not
arule.) ,

c. Tanks may be assigned to any Tank Battalion/
Regiment. (Historically, the Commonwealth used
a system of I- or Infantry-tanks, Cruiser Tanks,
and Light Tanks. Historians familiar with this
might want to follow this system; it is really unimportant on an Operational Level. The Italians
used a similar system that is easier to discern.)

d. Creation of Heavy Weapons Points requires
the expenditure of Infantry Replacement Points
and Gun Replacement Points.

[19.65] Armored Recce and Armored Car units
use Recce points, usually, to rebuild. However, the
Players may wish to use their Light Tanks to augment Recce units (see Case 20.6).

[19.66] In an instance where a battalion assigned
to a Parent Formation has either been eliminated
entirely or has, for any reason, been assigned to
another Formation, the assigned "space" for that
battalion may be taken by another, previously
unassigned, battalion. The latter battalion is then
considered assigned to the new Parent, although it
was not previously so. Example: The 42nd RTR of
the Ist Army Tank Brigade is destroyed completely. The Commonwealth Player may assign, say,
the 7th RTR to fill its place, even though the 7th
RTR would not normally be allowed to be assigned to the Ist Army Tank Brigade. (It would be
allowed to "switch" under Case 19.26).

[19.67] The HQ unit for a Parent Formation is,
for play purposes, its Cadre. As long as the HQ exists, that Parent Formation may be rebuilt by or
Reassignments. If the HQ is eliminated, see Case
19.62 and 19.63.

[19.68] Rebuilding units takes place in the
Organization Phase only; it may not take place at
any other time. For every two Replacement TOE
Strength Points added to a unit, that unit (and its
parent, if such is the situation) uses one Capability
Point. A unit may earn Disorganization Points by
taking on a large number of Replacement Points in
an Operations Stage. Severely depleted units a
Player wishes to so refit should be first moved to
rear areas.

[19.7] AXIS BATTLE GROUPS

[19.71] The Germans — and to some extent the
Italians — have the ability to form Battle Groups
(Kampfgruppen) out of ad hoc units or from units
from other divisions and brigades. The Germans

did this quite often, molding individual Battle
Groups to fit an occasion. Therefore, at any time
during an Organization Phase (and only then), the
Axis Player may form Battle Groups with his
units. All units must be in the same hex in the
Organization Phase, and they must conform to
Stacking Restrictions and the limits listed in the
following Cases. Battle Group counters are pro- |
vided to give HQ support. (These Battle Groups
are given historical names, but can be used in any
fashion.)

[19.72} A German Battle Group can carry a maximum of four battalion sized units of any type, but
there may be no more than one tank battalion
and/or two infantry battalions. Up to two additional companies may be attached over this limit.

[19.73] The Italians also formed Battle Groups,
but on a limited basis. No actual counters are provided, but the Italian Player, if he wishes, may
form Battle Groups using the list of Battle Groups
on the Italian OA Sheet. Italian Battle Groups
may have a maximum of three battalion-sized
units, only two of which may be infantry and only
one of which may be armor. One company-sized
unit may be attached. No more than two Italian
Battle Groups may be in existence at one time.

[19.8] FORMING AD HOC
AXIS ANTI-TANK BATTERIES

The Axis Player may use his Anti-Tank Gun
Replacement Points (his Marders will be especially
useful) to form "ad hoc" units; i.e., new units not
in the game. Essentially, he will be forming batteries of from 3 to 6 TOE Strength Points of any

one AT gun. . . ;
{19.81] The Axis Player's Brigade-Level HQ units

(including Kampfgruppe) bearing an infantry-type
symbol may contain up to six TOE Strength Points
of anti-tank guns.

({19.82] The Axis Player may augment any
Brigade-Level HQ at any point in the game with
Anti-tank TOE Strength Points if, at that point in
time, all of his anti-tank units on the map (which
includes the Tripoli-Tunisia boxes for this purpose) are ai at least 67% of their maximum permitted TOE Strength.

[19.83] The augmentation is performed by assigning anti-tank Replacement TOE Strength Points to
the HQ as if the HQ is an anti-tank unit. The initial
assignment must be at least three TOE Strength
Points.

[19.84] The assigned Anti-Tank Replacement
Points are trained at the Gun Replacement Point
rate.

(19.85] An HQ that contains Anti-Tank TOE
Strength Points possesses a CPA equal to that of
those Anti-Tank Points.

[19.86] The Axis Player may only assign a single
type of anti-tank guns to a particular HQ (if they
are eliminated completely he may begin again with
any type of anti-tank gun). Note that captured
anti-tank guns cannot be used to augment.

({19.87] An augmented HQ retains a Stacking
Point value of zero regardiess of the number of AT
points it currently contains.

[19.9] AUGMENTING COMMORWEALTH BATTALIONS WITH
ANTI-TANK

[19.91] Starting with the 75th Game-Turn (April
1, 1942), the Commonwealth Player may increase
the capabilities of certain of his infantry battalions
by giving them TOE Strength Points of Anti-Tank
guns.

[19.92] Only those infantry battalions possessing
a CPA Rating of 10 (whether or not they were
historically motorized; i.e., CPA Rating of 10+)

and Offensive/Defense Close Assault Ratings of
either 1/2 or 2/2 may be so augmented.

[19.93] These infantry unit's characteristics
change to now permit the unit to contain a second
weapons system (i.e., Anti-Tank TOE Strength
Points).

[19.94] Each historically motorized infantry battalion (CPA of 10+) may contain 2 TOE Strength
Points of anti-tank guns. Each historically nonmotorized infantry battalion (CPA of 10) may
contain one TOE Strength Point of Anti-Tank
guns.

[19.95] The Anti-Tank Points are assigned to the
infantry unit as regular Gun Replacement Points.
They undergo training at the Gun Replacement
Point rate.

[19.96] No Anti-Tank TOE Strength Points may
be so assigned if, at that point in time, any antitank regiment assigned to the infantry battalions
parent unit(s) is not at maximum TOE Strength.

[19.97] Once the Anti-Tank Points have been absorbed by the infantry unit they possess the CPA
of that infantry unit (i.e., a CPA of 10 if the infantry are walking or a CPA of 20 or 25 if the infantry
are motorized).

[19.98] Anti-Tank TOE Strength Points do not
affect any shell determinations of the infantry
unit.

[20.0] REINFORCEMENTS,
REPLACEMENTS AND
COMMONWEALTH
WITHDRAWALS

GENERAL RULE:

Both sides receive Reinforcements and Replacements. Reinforcements are entire units; Replacements are TOE Strength Points of particular
Classes. Both Players receive Reinforcements according to the schedule listed on the Reinforcement Track. In addition, the Commonwealth
Player receives Replacements according to Commonwealth Production, and the Axis Player
receives Replacements more or less at his whim out
of the Axis Replacement Pool.

Important: Any Replacement die rolls may be kept
secret from the other Players (including other
members of your own team).

CASES:
[20.1] REINFORCEMENTS

[20.11] Reinforcements are new, whole units that
arrive as specified by the Reinforcement Track.
Thus, in the September 3/2, Operations Stage, the
Commonwealth Player receives the 6th New
Zealand Brigade (and its three battalions) as well
as the 6th NZ Field Artillery Regiment.

[20.12] Reinforcements enter the game at the
beginning of the Naval Convoy Arrival Phase of
the Operations Stage. There is no Capability Point
cost for debarking; arriving units may be moved in
the first Operations Stage of arrival. (The arrival
dates have been adjusted to account for the
logistical problems of debarkation, etc.) Units do
not pay a Capability Point cost for the first hex
they are placed in.

[20.13] Reinforcements are treated as any other
units as soon as they have arrived, and they may
perform any and all game functions normally.

[20.14] Commonwealth reinforcements, unless
noted below, arrive at Cairo. Layforce Commando unit (Game-Turn 19) and the Tiger Convoy
(Game-Turn 32) of Tank Replacement Points

(which are reinforcements) arrive in Alexandria.
Returning withdrawn units arrive at Cairo or Alexandria at the Commonwealth Player's option
(subject to stacking restrictions).

[20.15] Ali Axis reinforcements arrive in Tripoli,
However, if there are no Commonwealth land
combat units west of Mersa Matruh (inclusive)
then “the Asis Player may divert forces to
Benghazi. The Axis Player may bring in one
battalion-equivalent combat unit or two companyequivalent combat units and up to ten Truck (or
Motorization) Points assigned to arrive with that
unit (or its parent unit). The Axis Player may not
divert units to Benghazi if this will exceed stacking
restrictions or if Benghazi has worse than a Level
three efficiency at that point in time. This use of
Benghazi does affect its port capacity for that
Operations Stage (see Case 55.1).

[20.2] REPLACEMENT POINTS

Replacement Points are designated by Class as
follows: Infantry Points, Gun Points, Tank
Points, and Recce Points. Replacement Points
usually enter the game for Axis Replacement
Points only — at the option of the Axis Player
from the Axis Replacement Points Pool (see Case
20.6),-or — for the Commonwealth Player only —
in accordance with the Commonwealth Production System (see Case 20.7). All Replacement
Points, regardless of the method in which they
enter the game, are covered by the same restrictions as listed in this Case.

[20.21] All Replacement Points "arrive" in the
Naval Convoy Arrival Phase of an Operations
Stage. Replacement Points mandated by the Reinforcement Track arrive in a particular Stage of a
particular Game-Turn as designated. Replacement
Points from the Axis Replacement Points Pool arrive in a particular Stage as determined by the Axis
Player; however, he must plan such arrivals two
full Game-Turns in advance (see Case 20.6).
Replacement Points from Commonwealth Production also arrive in particular Stages as determined by the Commonwealth Player; these must
be determined four Game-Turns in advance (see
Case 20.7).

(20.22] Commonwealth Replacement Points may
be—rarely—listed on the Reinforcement
Track.They are designated by type (e.g., the Commonwealth Player will receive "27 points of
Matildes," not merely "27 points of tanks").

[20.23] Replacement Points that are available in
the Axis Replacement Pool are designated by type
only. He is limited as to how many points of each
type may be brought in during any one turn. See
the Axis Replacement Pool.

[20.24] Similarly, Replacement Points available
according to the Commonwealth Production
System are designated by type and limited as to
availability.

[20.3] REPLACEMENT POINT
CONVERSION CHART
(see Charts and Tables)

[20.4] HOW REPLACEMENT POINTS

ARE USED
INF
REPL
B
[20.41] Trained Replacement Points may be

assigned to (and absorbed by) a unit any place on
the game-map (even in an Enemy Zone of Control). However, the Replacement Point and the
receiving unit must be in the same hex. This means
that "Mohammed usually goes to the Mountain,”'
rather than the latter. Points must be assigned for
eventual delivery to specific units immediately

upon arrival. Should the designated unit be
eliminated, or withdrawn, such points must be
reassigned immediately.

[20.42] Counters are provided to represent the
Replacement Points. Replacement Point counters
have all the characteristics of an actual unit, with
several major exceptions:

a. They may never voluntarily enter an Enemy
Zone of Control unless the hex is occupied by a
Friendly unit;

b. They may never be used in any type of combat
other than defending against Close Assault,
regardless of the strategic or tactical situation;

c. They all have a Basic Morale of — 3 (in their unabsorbed state);

d. They may never exceed their Capability Point
Aliowance (which is that of the unit they are being
assigned to); if they ever exceed their CPA — for
any reason — they are considered to have a Cohesion Level of — 26.

[20.43] Replacement Points (both Axis and
Commonwealth) are required to undergo Training. They must train for a specific number of
Operations Stages, which may include the Stage of
arrival, Players should consult the rules on Training (17.3) for particulars, as the same rules that apply to Training Reinforcements apply to Replacements. Axis points train in Tripoli or any major
city. Commonwealth units train in those locations
listed in Case 17.32. When in doubt as to unit size,
five Replacement Points equals one battalion. The
schedule for Replacement Training is as follows:

Type of Replacement
Point
Gun Replacement

OpStages of Training

One (Actually, not
Training; more un
crating)
Infantry Replacement Three
Tank, AC, Recce Six

Replacement

Note: This has nothing to do with Commonwealth
training for Morale.

[20.44] In essence, within the parameters of Case
20.42, Trained Infantry Replacement Points are
usually trucked (if available) to the Front Line
after undergoing Training, where they are transferred to the unit of assignation. Trained Tank,
Gun and Recce Replacement Points may move on
their own, use Railroads (Commonwealth), etc.

[20.45] Like other normal units, Replacement
Points require Stores and Fuel (if vehicles) when
moving. Remember, five Replacement Points is
the equivalent of a battalion for all purposes. They
can be assigned ammunition, but this is pretty
much a waste of supplies, given the maxims of
Case 20.42.

[20.46] Replacement Points moving toward the
Front for purposes of assignment are considered
Truck Convoys and move only in the Truck Convoy Movement Phase.

[20.47] Players should use the Replacement Point
Availability and Assignment Sheets for keeping
track of what is happening with their Replacement
Points.

[20.48] The cost in Capability Points to attach
Replacement Points to units is listed on the
Capability Point Cost Summary (6,3) Replacement Point units are considered as Assigned units
for this purpose.

[20.49] Replacement Points may be absorbed only during the- Reorganization Segment. They then
acquire the assigned unit's cohesion, breakdown
and other levels.

31

32

[20.5] UPGRADING ARMORED CAR
EFFECTIVENESS

At the beginning of the campaign, most Armored
Car and Reconnaissance (Recce) units were
“‘light”' in nature, using lightly armored cars, carriers, and AP trucks mostly equipped with antipersonnel weapons. As the war progressed, this
equipment was often upgraded with the addition
of light tanks and better-armed cars and carriers.
This rule reflects that increase in effectiveness.

[20.51] All armored reconnaissance and armored
car (i.e., Italian ID Code "ww,”' German ID Code
‘“go”? and Commonwealth ID Code "hh”' thru
““tt?? inclusive) units that arrive/deploy with an
Anti-armor Rating of zero (even those also
possessing an Offensive Close Assault Rating of
“*3" — see Case 20.54) may be increased in effectiveness with the following exception. None of the
Commonwealth Player's Recce units assigned to
Infantry Divisions (for this purpose, the 18th
Brigade of the 7th Australian Division is. considered a division) may be upgraded (i.e., the 51st
Recce Regiment of the 51st Highland division
could not be upgraded).

[20.52] To upgrade an Armored Recce or A/C
unit, the Player simply adds one TOE Strength
Point of certain types of tanks (as listed in 20.53)
to the Recce or A/C units, remembering that the
unit may never exceed its stated TOE maximum.
Thus, he may add the TOE to replace a lost TOE
Point, or he may simply add the Tank TOE in and
not increase the TOE Strength Points, if the Recce
or A/C unit is already at maximum level.

[20.53] Commonwealth Players may use Stuarts
to upgrade their Recce/AC units. German units
may be upgraded by adding Pz JJ TOE points.
Italian units may be upgraded by adding M/11 or
L6/40 Tank Points, or armored recce/armored
car Replacement Points.

[20.54] An "upgraded'”' Recce or A/C unit's TOE
Strength Point has an Anti-Armor Rating of 1, instead of zero, and an Offensive Close Assault
Rating of 3, instead of 2.

[20.55] No units may be upgraded until1/39, at

the earliest.

[20.6] AXIS PLANNED
REPLACEMENTS

Italian and German Replacement Points enter the

game from the Axis Replacement Pool (20.66) asa

result of direct planning by the Axis Player.

[20.61] In the Axis Replacement Pool, the Axis
Player will find the maximum number of Replacement Points for each type of point for the entire
Campaign Game. (Each Scenario lists the maximum available for that Scenario, if any). The
Axis Player may never use more Replacement
Points than are provided. This is further limited by
the maximum points available per turn, per type.

[20.62] The Axis Player may bring in any number
of Replacement Points of any and all Classes during any one OpStage (see Case 20.23) limited of
course by the pool restrictions. However, each
Replacement Point is counted against the Shipping
Tonnage allowance for that Game-Turn (see Case
51.5). The equivalent tonnage of each Point is
given in the Pool Table. Thus, if the Axis Player
wishes to bring in 10 Italian Infantry Replacement
Points, he would need 350 Tons of Shipping
availability.

[20.63] All Axis Replacement Points coming from
the Axis Replacement Pool must be Planned for at
least two turns in advance. In other words, Axis
Planned Replacements for July, 1941 must be
determined in the Naval Convoy Arrival Phase of
the 1/I1iGame-Turn of June, 1941. Replacement
planned in June II] may arrive in any OP Stage
Navel Convoy Arrival Phase of July I.

[26.64] Replacement Points have priority in Shipping Space over any type of supplies. The Axis
Logistics Commander thus has to keep a close
watch (and tight rein) on what he is shipping at
what time, as he rarely knows that far in advance
exactly how much shipping he will have available
(see Section 51.0). Remember, Axis Shipping is
subject to Commonwealth air Raid, so keep aneye
on Malta and the location of Commonwealth airfields.

[20.65] Replacement Points may not be absorbed
by units that have no place for them, so remember
to space your Replacements carefully.

[20.66] The Axis Replacement Poo! Table
(see Charts and Tables)

[20.67] Axis Replacement Point Type
Limitations Chart (see Charts and Tables)

[20.7] COMMONWEALTH
PRODUCTION
{20.71] Most Commonwealth units and some of
their Replacements arrive via the Reinforcement
Track. However, most -Replacements — mostly
“‘drafts"? and transport — arrive somewhat randomly as mandated by the Commonwealth Production Tables (20.78).
[20.72] The Commonwealth Player must plan two
months in advance (unless specified in a given
Scenario) for the arrival of Replacement Points via
Production. Thus, for Points required for August,
1942, the Commonwealth Player must plan — using the Production Systems. — in the first Naval
Convoy Schedule Phase of July, 1942. However,
the Commonwealth Player always uses the Production Table for the month (one months in the
future) in which he wishes his units to arrive — not
the month in which he is consulting it.

[20.73] The Commonwealth Production System
functions like the Axis Pools except for Infantry
and Truck Points. The Player uses a random dice
roll to determine what Infantry and Truck Points
he receives per turn, depending upon the date of
arrival.

[20.74] Replacement Points scheduled for any
given turn must be divided among the OpStagesas
evenly as possible. This refers to the total Points
for all types. Thus the Commonwealth Player may
bring 10 Medium Trucks in one OpStage and 10
Infantry Points in the next.

[20.75] Replacement Points listed in the Reinforcement Schedule arrive in addition to any Production. The Commonwealth Player has no Shipping Problems; his Replacement Points simply arrive.

[20.761 All Planned Replacements arrive in any
hex in Cairo or Alexandria. They, like other
Replacements, must undergo Training (see Case
20.43).

[20.77] The Commonwealth Player may
“upgrade”? his Infantry units in much the same
fashion as his Recce/AC units. This applies only
to infantry units with a 1/2 (Off/Def) Close
Assau]t Rating. The Commonwealth Player simply uses one Infantry Replacement Point for each
TOE Strength Point in the unit he wishes to
upgrade. Furthermore, the Commonwealth
Player must upgrade a// TOE Points in that unit at
the same time. The Replacement Point used is absorbed to increase the Assault Rating to 2/2; it
does not increase the TOE Strength itself. No
upgrading may take place before the July 1/1,
1942 Game-Turn, which means they may be
“planned”' in June, 1942. Infantry Replacement
Points scheduled for upgrading need not be Trained. Once upgraded additional replacements
assigned to that unit only require | Infantry
Replacement Point per TOE Point, not 2 (1&1) Infantry Replacement Points.

[20.78] Commonwealth Production System
(see Charts and Tables)

[20.8] COMMONWEALTH
MANDATORY WITHDRAWALS

During the Desert Campaign, Commonwealth
units were often withdrawn and sent elsewhere
(Crete, Greece, Syria, Iraq, Cyprus, Sudan, etc.).
This is reflected in the Commonwealth Reinforcement Schedule, which tells the Commonwealth
Player if, when, and how many units must be
removed from the game.

[20.81] Withdrawals are listed in the Reinforcement Schedule. They are listed as either actual
units or as types of units (e.g., "Withdraw any two
Armor Brigades").

(20.82]. When a Withdrawal is listed by type, the
unit chosen for Withdraw! must be at 75% maximum TOE Strength (at least), or, if no units are
up to that level, the highest TOE Strength-level
unit of its type available.

[20.83] Units to be Withdrawn must be moved to
Cairo or Alexandria on or before the Game-Turn
or Stage they are to be withdrawn. If they are not
present or at required TOE Strength (20.75) by
that time, they are eliminated. (This is a play
mechanism to forestall procrastination.) Units so
eliminated may not return (as many Withdrawls
do, later in the game).

[20.84] Once the units have reached Cairo or
Alexandria, they are simply removed from play.

[20.85] If a unit scheduled for Mandatory Withdrawal is less than 75% TOE Strength, it must be
brought up to that level by Replacement Points
before Withdrawal Date (see Case 20.82) or an
equivalent substitute unit of similar type that is at
least at 75% TOE strength.

[20.9] VOLUNTARY COMMONWEALTH
WITHDRAWALS

Throughout the Campaign, the Commonwealth
was under great military and political pressure to
support a wide variety of activities in such places
as Cyprus, Sudan, Iraq, etc. Case 20.8 discusses
large mandatory troop withdrawals. In addition,
the Commonwealth, during lulls in action, would
often send several ad hoc battalions to duty elsewhere; these units often shuffled back and forth in
almost random fashion, dependent on the situation. It would be folly to list all such movements
and even sillier to require a Player to follow them.
(We are not too happy with Mandatory Withdrawals, but such unit absences on a large scale
must be accounted for.) The Commonwealth
Player therefore has the option to withdraw small
forces at any time, thereby gaining Victory Points.
Victory Points are given because these forces
would aid campaigns elsewhere, put additional
pressure on the enemy, etc. Returning voluntarily
withdrawn units penalizes the Commonwealth
Player. See the Campaign Game Victory Conditions.

[21.0] BREAKDOWN

COMMENTARY:

The great problem with the desert was not really
the heat, which was bad enough. The major problem was the incredible wear and tear that vehicles
incurred. The desert got into everything, and this
deadly combination of heat, sand, and rocky
ground wreaked havoc on all moving parts. Tanks
used to going 1000 miles without an overhaul
would collapse after one day's hard travel. The
rules for Breakdown and Repair attempt to
simulate this facet of the Desert Campaign. Like
many other rules in CNA, Breakdown requires
working with a lot of numbers. The rule itself is

simple; it is the record-keeping that will tax the imagination (and patience). Sheets for Breakdown
and Repairs are provided.

GENERAL RULE:

Essentially, all vehicles, except motorcycles and
those vehicles assigned (abstractly) to gun units
(Artillery, Anti-Tank, AA/Flak, etc.) are subject
to Breakdown. Whether a given unit will break
down depends on the distance traveled and the
type of terrain encountered in a given Operations
Stage. Furthermore, certain types of vehicles
break down faster than others, and this is taken into account. In general, each type of terrain has a
Breakdown Factor, and for each hex entered during movement the moving vehicle accumulates
Breakdown Points. When the unit ceases movement, the Player totals the Breakdown Points accumulated, consults the Breakdown Table, adjusts
the Breakdown Point Column for vehicle type, and
rolis two dice, adding them together. The result is
the percentage of vehicles (of a given type) in that
unit that have Broken down. Broken down
vehicles may not move, defend or attack. They are
represented by Broken down Unit Counters.
Broken down units may be captured (by the
Enemy) or retrieved (by the owning Player). Either
way, Broken down vehicles may be Towed back to
a Repair Facility for Maintenance, or they may be
Repaired in the Field (see Section 22.0 for
Repairs).

CASES

[21.1] WHICH UNITS BREAKDOWN

[21.11] Only the following vehicles are subject to
Breakdown: Truck Points, tank, armored reconnaissance/armored car and self-propelled gun
TOE Strength Points whether they comprise part
of a unit or are Replacement Points.

[21.12] Each specific type of TOE Strength Point
has its own Breakdown Adjustment Rating
(BAR). BAR's are listed below and in the various
Tank & Gun Characteristics Charts. For example,
an Italian M 13/40 has a BAR of 2R while the
Commonwealth Sherman has a BAR of zero.

[21.13] The Breakdown Adjustment Rating is used to adjust the Breakdown Points column to the
left or right when rolling to determine Breakdown.

[21.14] Breakdown Adjustment Summary
Breakdown Adjustment

Type of Point Rating

All Trucks 2 Left

All Armored Car 1 Left
ArmRecce

SP Guns 1 Left, 2 Right*

Tanks 1 Left, 2 Right*

*Listed individually on the appropriate Tank &
Gun Characteristics Chart.

[21.15] Vehicles are never required to check for
Breakdown when moving to, from or amongst the
Axis off-map Tripoli/Tunisia boxes.

[21.2] WHEN BREAKDOWN OCCURS

[21.21] Each hex (or rather the terrain in the hex)
possesses a Breakdown Point Value, which is listed
on the Terrain Effects Chart (8.37). In addition,
certain types of hexsides (e.g., Wadis) also have
a Breakdown Point Value. The Breakdown Point
Value is the number of Breakdown Points a
motorized unit or vehicle accumulates when moving into that type of terrain/hex and/or through
that type of hexside. Breakdown Point Values for
given terrain types may be modified by Weather
(see Section 29.0).

[21.22] Combat does not cause Breakdown,
although any movement (Retreat, Reaction, etc.)
does accumulate Breakdown Points.

[21.23] As a vehicle or motorized unit (see Case
21.11) moves, it accumulates Breakdown Points.
All of the vehicles/motorized units in a stack or
Parent formation accumulate the Breakdown
Points for given terrain. Example:

(see bottom of this page)

[21.24] Whenever a vehicular or motorized unit
ceases movement — whether it has finished its
Movement for that Operations Stage or will be
moving again under the Continual Movement
Rule — the owning Player must check for possible
Breakdown.

[21.25] Ali Breakdown Points garnered by a unit
during a given Operations Stage are accumulated
until the end of that Stage. Simply because a
Player checks for Breakdown for a unit does not
mean those Breakdown Points accumulated up to
that point are discharged; they continue to accumulate up until the end of the Stage (see Case
21.26). In other words, Breakdown Points are
cumulative within an Operations Stage — and they
are cumulative and applicable during both
Players' portions of the Operations Stage.

[21.26] If a unit has had a Breakdown check during an Operations Stage (regardless of whether or
not it actually suffered any Breakdown), it is required to check for Breakdown again only if it has
accumulated enough Breakdown Points to carry
over into the next highest Breakdown Point Column on the Breakdown Table (21.38). Example:
The LII (M) Battalion (in Case 21.23) had accumulated 15 Breakdown Points the first time it
moved. During the same Operations Stage it
moves again, but it moves only one hex, accumulating 2 more Breakdown Points for a total
of 17. As it is still in the same column (21-30;
because M/13's adjust +1 columns _ higher
because of their Breakdown Adjustment Rating),
it need not check for Breakdown when it stops.
However, in the same Operations Stage, but in the
opposing Player's movement, the LII retreats, accumulating 10 more Breakdown Points, for a total
of 27. As it is now in a new (higher) column, the
unit must check again for Breakdown. A unit does
not check for each column; it checks only when it
stops, if it is in a higher column. Note: the
Breakdown Rate is virtually geometrically progressive — the further you move the worse it gets.
The Player is penalized for moving, stopping,
moving, stopping, etc.

[21.27] A unit does not check for Breakdown until
it has accumulated more than threee Breakdown
Points, regardless of that unit's Breakdown Adjustment Rating.

{21.28] Breakdown is determined separately for
each type of unit: Trucks, Tanks (including S.P.
Guns), or Armored Recce and A/C vehicles.
Furthermore, if there are tanks and/or Guns

In the above example, the Italian LI] (M) Tank
Battalion — containing, for example's sake, all
M/13's — has accumulated 15 Breakdown Points
for the illustrated movement: 4 Breakdown Point

within a stack/Parent formation with differing
Breakdown Adjustment Ratings the Player checks
separately for each group of tanks andGuns witha
different Rating. A different Breakdown diceroll
is used for each separate type.

[21.29] Important: In addition to Case 21.28,
Players must check separately for each type of unit
in a stack that is in a different Breakdown Point
column. Example: A Recce unit moves and accumulates 15 Breakdown Points, entering.a hex
with a second Recce unit (which has not moved),

' Recce #1 continues to move along with Recce #2,
both units picking up 23 more Breakdown Points.
Recce #1 has accumulated 38 Breakdown Points,
Recce #2, 23. Recce #1 and Recce #2 determine
their Breakdown separately, because they are using different Breakdown Point columns.

- [21.3] HOW BREAKDOWN
/ ISDETERMINED

[21.31] To determine Breakdown, the Breakdown
Table (21.38) is used. Each column on the Breakdown Table corresponds to a Range of Breakdown
Points accumulated. Thus 31-40 means anywhere
from 31 to 40 Breakdown Points accumulated at
the time of Breakdown check (all fractions are
rounded up: 20.5 = 21). The Breakdown Table
uses two dice, read sequentially. :

[21.32] After the Player checking for Breakdown
notes the Breakdown Points accumulated for a
given unit, he takes into effect any Breakdown Adjustment Rating (21.13) as well as any adjustments
to Breakdown Rates because of Weather (see Case
21.37). These two are cumulative: a 2 column left
Breakdown Adjustment Rating plus a_ onecolumn-higher shift for Weather makes for a final
adjustment of one column lower.

[21.33] Units accumulating more than 71 Breakdown Points use the 71+ column. You cannot adjust higher than that column, and that column is
considered as one column for purposes of adjustment. Units that have their column adjusted lower
than the 4-10 column do not suffer Breakdown.
Remember the adjustments are in columns, not in
points accumulated.

[21.34] Having determined the Breakdown Column, the Player throws two dice, reading sequentially , and cross-referencing that diceroll with the
Breakdown Column. The result is the percentage
of TOE Strength Points Broken down within the
units for which the Player is rolling (remember
Cases 21.28 and 21.29). Each Truck Point is
equivalent to a TOE Strength Point for this purpose. (Remember that it is the TOE Strength
Points that break down, not the units.) Example:
A stack with 30 Truck Points and 20 TOE Strength
Points of Crusader I's accumulates 35 Breakdown
Points and stops. The Player checks for Breakdown. The Trucks have a Breakdown Adjustment

for each of the two Road hexes (it was using Road
Movement), 8 for entering the Rough terrain hex,
2 for crossing the Ridge hexside and 4 for entering
the Clear Terrain hex.

33

34

Rating of 2L, and the Weather is Hot, so the
31-40 column is adjusted one lower (—2 and +1
= —1). The Player rolls a 33, consults the 21-30
column and sees that 10% of his Truck Points (or 3
Truck Points) have Broken down. He then checks
for his Crusaders: they have a Breakdown Adjustment Rating of 1R, plus 1 more for the Hot
Weather, adjusting the 31-40 column up to the
51-60 column. The Player rolls a 61, and 33% (or
1/3) of his Crusader I's — or 7 TOE Strength
Points — have Broken down.

[21.35] All Breakdown fractions are rounded up,
(as the 6.7 Tank TOE Strength Points in Case
21.34 became 7). Exception: If the Player is checking for a unit that has only one TOE Strength
Point, all percentage results of 10% are ignored.

[21.36] All breakdowns must be distributed as
evenly as possible amongst types of vehicles as well
as different units. Thus, if two German Panzer
battalions, each with different types of tanks (all
German tanks have a Breakdown Adjustment
Rating of zero) suffers 25% Breakdown, the
Breakdown must be distributed proportionally as
to all types of tanks and between the different
Panzer battalions. °

[21.37] Weather affects the Breakdown

Rates/Columns as follows (consult also Section

29.0):

a. Normal Weather: No Effect.

b. Hot Weather: For each Breakdown check,
adjust one column higher (1R).

c. Rainstorms: All Road Breakdown Point Values
are treated as Track Breakdown Point Values.
d. Sandstorms: If at least 50% of a unit's Move
ment (calculated in Capability Points expended)
in a particular Movement Phases, Retreat, Reaction, etc., is on a game-map with Sandstorms
‘adjust the Breakdown column one higher (1R).
[21.38] Breakdown Table
(see Charts and Tables)

[21.4] BROKEN DOWN VEHICLES

16 A
Z°)

[21.41] Breakdown occurs (for the sake of
simplicity) in the hex in which the units checking
for Breakdown have ceased movement. However,
if a unit checking for Breakdown started its movement within two hexes (with no Friendly units,
Friendly ZOC's; or impassable intervening terrain) of an Enemy combat unit /arger than a single
battalion, then at least 50% of all TOE Strength
Points that Break down must be placed in the hex
in which that unit began movement.

(21.42] When Breakdown occurs, the Player
places a Broken Down Vehicle marker in the hex in
which the Breakdown has occurred and records
the necessary information on his Broken Down
Vehicles Sheet. Broken Down Vehicle Markers are
numbered so that the Player may keep track of
what is represented by each different marker.

[24.43] When a Truck Breaks down, its cargo
stays with it, unless there are sufficient empty
Trucks to pick up the slack. Players will note that a
Motorized Infantry battalion that loses even one
Truck Point that it cannot replace will become
““un-motorized" because of the rule that the entire
battalion (all TOE Strength Points) must be in
trucks for the unit to be considered motorized.

{21.44] Broken down vehicles have no Capability
Point Allowance, nor may they participate in combat of any type. Broken down vehicles may be captured (by the Enemy) — see Case 21.5 — or retrieved by the owning Player (see Towing, Case 21.6).

nics iiss Ea

[21.45] Supplies on broken down Trucks may be
transferred to working Trucks in the same hex at
the time of Breakdown at a cost of 2 Capability
Points (the same as to load/unload). Infantry
TOE Strength Points in broken down trucks may
‘dismount'? (1 CP) from the trucks and start
walking. Any Capability Points they have accumulated while in a Truck count against their
non-motorized Allowance of 10 (or 8), with the exception that if they have used more than 10 (or 8)
while motorized they are considered to have used
only that 10 (or 8) — not more. If the men and/or
supplies are to be picked up by Truck Points that
were not attached to the unit which broke down at
the time of Breakdown, there is a Capability Point
cost for Loading.

[21.5] CAPTURING BROKEN DOWN
VEHICLES

[21.51] Broken down vehicles may be captured by
the Enemy. Players should differentiate between
the capture of Broken down vehicles and (1) the
capture of Destroyed Tanks (see Case 14.5); as
well as (2) the Capture of abandoned vehicles.

(21.52] At any time during movement, if a Friendly combat unit of battalion-size or larger moves
adjacent to a Broken Down Vehicle marker that
vehicle (or vehicles) is captured.

[21.53] Broken down vehicles that are either
stacked with Friendly combat units, HQs, or
Engineers, or in a Friendly-controlled hex may not
be Captured.

[21.54] The capturing unit and the broken down
vehicle must be adjacent through passable terrain;
i.e., a German Panzer battalion at the bottom of
an Escarpment could not capture Enemy Broken
down tanks at the top of the escarpment because
the German tanks cannot move across and up an
escarpment hexside.

[21.35] Captured Broken down vehicles may be
placed (towed) a maximum of three hexes in any
direction at the instant of capture. The path of this
placement, which costs no Capability Points to
any unit involved, may not be traced through
Enemy units, Enemy Zones of Control or nonpassable terrain. (Units being towed are considered vehicles). Note: The capturing unit does
not expend any Capability Points for this activity,
and may indeed continue to be moved.

[21.6] TOWING

[21.61] All vehicles scheduled for repairs at a
Repair Facility — including Broken down vehicles
and destroyed tanks, whether retreived by the
Friendly Player or captured by the Enemy Player
— may be towed to a Repair Facility in order to
undergo repairs.

[21.62] Only vehicles not undergoing Field Repair
(or any other type of repair) may be towed. All
towing occurs in the Repair Stage, except for instances such as Case 21.55.

[21.63] There are no towing vehicles (however, see
22.6 and 22.7). Rather, each Broken Down Vehicle
marker or Destroyed Tank marker may move 10
Capability Points per Repair Phase. They may
move only in the Repair Phase, and they may not
React or Retreat Before Combat, etc. The marker
is towed as though it is a Medium Truck.

[21.64] No vehicle may ever be towed if it is in an
Enemy-controlled hex with the exception of towing at the instant of capture (see Cases 21.55 and
14,53). This restriction applies at a// times during
the Repair Phase. Friendly units negate Enemy
Zones of Control.

[21.65] Towing incurs no costs for Fuel, Stores or
Water. Towed vehicles do not undergo
Breakdown.

[21.66] A Broken down vehicle that unsuccessfully undergoes Field Repairs may not be Towed in
that Repair Phase.

{21.67} Broken down vehicles and destroyed

‘tanks must be towed towards the nearest Tem
porary or Major Repair Facility, if they are being
towed.

[22.0] REPAIR

GENERAL RULE:

Broken down vehicles and destroyed tanks may be
Repaired and returned to action. Repairs may be
undertaken in the field or at Temporary or Major
Repair Facilities. Vehicle repair expends supplies.

PROCEDURE:

Vehicles may undergo Repair in the Repair Phase
of the Operations Stage. The Phasing Player rolls
one die for each type of vehicle he wishes to Repair
and checks the variety of Repair Schedules, dependent upon the type of unit, the type of Repair
(Breakdown or Destroyed Tanks) and the type of
Facility. The dieroll results in the number of TOE
Strength Points repaired (Field Repairs) or a
percentage of the units which are successfully
repaired (Facility Repairs). As Repairs are attempted, supplies are expended, whether the repairs are
successful or not. Repaired vehicles are returned to
play in the form of Truck Points or Replacement
Points — for Tanks and Recce units — (see Case
20.2).

CASES:

[22.1] WHICH VEHICLES
MAY BE REPAIRED

[22.11] A Player may attempt to repair all Broken
down vehicles as well as any tanks destroyed in
combat, whether they are his nationality or not.
The only requirement is that he control the
vehicles in question.

[22.12] All repairs are undertaken in the Repair
Phase of each Operations Stage. Only the Phasing
Player undertakes repairs.

[22.13] Repairs may not take place under the
following circumstances:

a. If the vehicles to be Repaired are in an Enemycontrolled hex, regardless of the presence of
Friendly units in the hex. The only exception to
this is if the vehicles are in a Major Repair
Facility, in which case the presence of an Enemy
Zone of Control has no effect; or :

b. If there are no supplies available for Repairs
(see Cases 22.2 and 22.3); or

¢. The vehicles have been towed during the Repair
Phase; or

d. The Weather is Rainstorm or Sandstorm for
that hex. This does not apply to Major Repair
Facilities.

[22.14] The Commonwealth Player may repair all
his vehicles together (within the further restrictions below). However, the Axis Player must
repair German vehicles separately from Italian
vehicles. Captured vehicles are also repaired
separately.

[22.2] FIELD REP AIRS

[22.21] Players may attempt to repair Broken
down vehicles in the field. Destroyed tanks may
not be repaired in the field; they must be towed toa
Facility (exceptions: see Cases 22.6 and 22.7).

[22.22] Field Repairs may take place in any hex in
which there is a Broken down vehicle stacked with
a Friendly unit of any type, even a Squadron
Ground Support Unit (see Case 22.13a). Field

Repairs may not be made if the vehicle in question
has been towed in that Repair Phase (see also Case
22.6).

[22.23] To repair trucks in the field, the Player
rolls one die for Broken down trucks in the hex in
question. If he rolls a 2 he may repair one Light or
one Medium Truck Point. If he rolls a 1 he may
repair two Light or two Medium Trucks (or any
combination of Light and Medium equal to two)
or one Heavy Truck. Field repair of Trucks requires no expenditure of supplies.

[22.24] To field repair armored cars and/or Recce
TOE Strength Points, the Player rolls one die for
all the A/C's and Recce points in the hex. If he
rolls a ] he may repair one such TOE Strength
Point. No supply expenditure is required for field
repair of Armored Recce or Armored car points.

[22.25] To field repair tanks or self-propelled artillery the Player consults the Broken Down Vehicle Repair Table (22.8) under the column for
“Field Repair." He throws one die for each type
of tank undergoing repairs. Thus, it the German
Player has PzII's and PzIV Specials in the same
hex, he rolls once for the PzII's and once for the
PzIV Specials. The result is the percentage of
tanks of that type in that hex that have been
repaired. All fractions are rounded up, unless
there is only one TOE point undergoing repair. In
such case the Player ignores the 10% result.

[22.26] For each tank TOE Strength Point to
undergo field repairs, the Player must have present
in the hex and expend before rolling for repairs
one Fuel Point. He may attempt to repair only
those Tank TOE Strength Points he has expended
Fuel for.

[22.27] Weather affects Field Repairs; see Case
22.13d.

[22.28] Players will note that field repairs are a
risky proposition.

[22.3] FACILITY REPAIRS

[22.31] There are two types of Repair Facilities:
Temporary Facilities and Major Facilities. Temporary Facilities may be constructed by the Players
(see Case 24.8), and those in existence at the start
of a scenario are designated in that scenario. Major Repair Facilities are found in Tripoli (the
Tripoli Box), Tobruk (for whoever controls it),
Alexandria and Cairo (all hexes). The effectiveness of Repair facilities may be reduced or
neutralized by bombing (see Cases 22.35 and
39.37) and Artillery Barrage.

[22.32] If a Broken down Vehicle or Destroyed
Tank beings a Maintenance Segment in a hex with
a Repair Facility and that vehicle has not been
Towed during that Operations Stage such
vehicle(s) may undergo Repairs.

[22.33] Players Repair by type of vehicle: Truck
Points, Recce/AC Points, Brokendown Tanks
and Guns by Type, and/or Destroyed Tanks by
Type.

[22.34] For each type of Brokendown vehicle the
Player rolls one die and consults the Broken Down
Vehicle Repair Table (22.8) under the correct column (Temporary or Major Facility). The dieroll
may be modified by the effects of bombing on the
Fortification Level of the city (see Case 22.35).
The result of the dieroll is the percentage of that
type of vehicle that may be Repaired (see Case
22.25 for details). See Case 22.4 for Destroyed
Tanks. ,

a. If the Repair Facility is in a Major City and the
Enemy Player succeeds in reducing the Fortification Level of that City by one (see Air Bombardment Table) add one to the dieroll. If the level is
reduced by two or three add two to the dieroll

(whether reduced by Air Bombardment and/or
Barrage).

b. If the Repair Facility is not ina Major City and
the Enemy Player delivers enough Air Bombs or
Artillery Barrage that, when/if using Air Bombardment Table, to reduce a Fortification one
Level, that Repair Facility is neutralized for that
OpStage. It may not repair any vehicles.

[22.35] For each Truck Point, Gun or Tank TOE
Strength Point undergoing repair the Player must
have present in that hex and expend (before rolling
for Repairs) one Store Point-and one Fuel Point.
He may attempt to repair only those points he has
expended supplies for.

[22.36] Temporary Repair Facilities may be affected by Weather (see Case 22.13d). Major
Facilities are never affected by Weather.

[22.37] If a Temporary Repair Facility is in the

ZOC of an Enemy unit it may not be used for
Repairs unless it is in a Major City. Major Repair
Facilities may be used when in Enemy ZOC's.

[22.38] See Case 24.8 for how to construct a Temporary Facility.

[22.4] REPAIRING DESTROYED TANKS

Destroyed tanks — represented by Destroyed
Tank markers — may be repaired and put back into service. Players may repair any destroyed tanks
— theirs or the other player's — that they can get
toa Repair Facility. See Case 14.5.

[22.41] Destroyed tanks may be repaired only in
Repair Facilities. Destroyed tanks may not be
repaired in the field. However, see Cases 22.6 and
22.7.

[22.42] For each and every destroyed tank TOE
Strength Point a Player wishes to attempt to
repair, he must expend two Stores and two Fuel
Points (Logistics Game only). These supplies must
be present in the hex and a// such supplies must be
expended before any repair attempts are resolved.
le., before rolling the die for any repair attempts,
the Player must decide how many attempts he will
make and "pre-pay" for them. Supplies must be
expended for all attempts regardless of whether
they are successful or not. (Note that this is not the
case with repairing aircraft.)

[22.43] In order to attempt to repair a Tank TOE
Strength Point, the owning Player rolls one die
and consults the Destroyed Tank Repair Table (see
Case 22.44). The die must be rolled separately for
each such tank TOE Strength Point. If the attempt
is successful, the TOE Strength Point is considered
repaired; if unsuccessful, it is either considered
permanently eliminated ("junked") or nothing
happens, in which case another repair attempt may
be made.

[22.44] Destroyed Tank Repair Table
(see Charts and Tables)

[22.5] REPAIRED VEHICLES

Repaired vehicles are treated as Replacement
Points for that type of unit. See Case 20.2. They
must have fuel to move again, and they follow all
the rules laid down for Replacement Points, except
that they do not have to undergo Training.

[22.6] THE DESERT TANK
DELIVERY ORGANIZATION

The Commonwealth had special Tank Delivery
Squadrons which were used to speed up the
recovery, repair and training of Tank Units. In addition, they held any Reserves available.

[22.61] The Commonwealth Player receives, over
the course of the game, three Tank Delivery
Squadrons, which comprise the Desert Tank
Delivery Organization (a name, not a HQ unit).

TNKDEL
a

CRO

[22.62] Each Tank Delivery Squadron counter isa
sort of "advanced" Field Repair Facility. If-a
Brokendown Tank is in the same hex as a Tank
Delivery Squadron the Commonwealth Player
may subtract one from his dieroll for Field Repair
(22.2). For Destroyed Commonwealth Tanks,
TDS's repair on a die roll of "1". They do not
‘junk'? and they may not repair Enemy tanks.

[22.63] Each Tank Delivery Squadron has no
combat ratings of any type (see Case 22.64) and
has no Stacking Points. They have a CPA of 25 as
vehicles but may never voluntarily exceed that
CPA or move into an Enemy Zone of Control. If
alone in a hex and an Enemy combat unit places
the TDS in its ZOC the TDS is eliminated. An
eliminated TDS may be returned to play eight
Game-Turns after its elimination.

(22.64] Each TDS may hold up to three TOE
Strength Points of Tanks as Reserves and still
maintain a Stacking Point value of "0". These
Reserve TOE Tank Points are treated the same as
any Tank Replacement Points.

[22.65] In addition to the above capabilities,
DTS's may Tow Brokendown or Destroyed Tanks

back to a Facility at a movement rate of 20 CP's'

(as opposed to the normal 10 for towing). DTS's
may tow up to three TOEB's of tanks (in addition to
any Reserves); it still has a Stacking Point Value of
“0”. DTS's may not attempt Field Repair ina turn
in which they tow.

[22.66] TDS's that have, for any reason, exceeded
their CPA in a given OpStage may not attempt
repairs in the ensuing OpStage. They may still tow.

[22.7] GERMAN MOBILE TANK
REPAIR SQUAD

The German Mobile Tank Repair Squad is treated
exactly the same as the Commonwealth Desert
Tank Delivery Squadrpons, with the exception
that they may repair only German Tanks (not
Italian or captured Commonwealth). There is one
German Mobile Tank Repair Squad counter.

[22.8] BROKEN DOWN VEHICLE
REPAIR TABLE
(see Charts and Tables)

[23.0] ENGINEERS
GENERAL RULE:

In CNA Engineer units are used to aid in construction of a variety of items, as well as helping to
repair facilities that have been destroyed. They are
also useful in laying and removing minefields.
Realistically, engineers had a great deal more
usage than we have given them in this simulation.
However, we have abstracted a goodly number of
those uses, as the "thesis" of the simulation does
not lie in the direction of Engineer capability.
There are three types of Engineer units: Engineer
Battalions, Engineer companies, and Headquarters Units with Engineer capability.

CASES:
[23.1] ENGINEER UNITS

[23.11] Engineer counters have no real combat
value, nor do they exert Zones of Control. They
are not combat units in any way, shape, or form.
Engineer units may never enter Enemy-controlled
hexes voluntarily, and they may use their parenthesized strength only if they are stacked with a
Friendly combat unit.

35

