[#62_0]
== SCENARIO GROUP
THIREE: OPERATION
CRUSADER

{62.1] GENERAL DESCRIPTION

Operation Crusader covers the events of the
Winter of 1941-2, in which the Commonwealth
forces attempted to relieve Tobruk (under siege by
the Axis) while, at the same time, Rommel had
planned to strike eastward at the Allied forces in
Egypt. The result was an extended series of battles
in the area between Sollum and Tobruk.

[#62_2]
=== SCENARIO LENGTH AND
DURATION

The scenario starts with the 3rd-OpStage of the
57th Game-Turn. The scenario ends with the conclusion of the 1st OpStage of the 65th Game-Turn.
The estimated playing time for this scenario is between 200 and 250 hours.

[#62_3]
=== COMMONWEALTH FORCES

[#62_31]*[62.31]* Commonwealth Forces Initial
Deployment (Hex: Units)

Within 1 hex of

C4807; 32 Army Tank Bde (2; Assg: Ist RTR
[7/7]; 4th RTR and 7th RTR); Polish Bde; 70th Infantry Division (Less: 1 Argyll & Sutherland;
Assg: 2nd Kings Own Rifles [in place of the 1
A&S], Ist Royal Northumberland Fusiliers MG
Bn, Ist RHA; 104th RHA, 107th RHA; ATT:
144th Field Arty, 2/13 Aus Inf Bn [20/9 J); 12/15
Aus In Bn [TOE strength of 4; 0/9]; 13th Light
AA; 14 Light AA; 2nd Light AA and 89th Heavy
AA. Trucks: 20 Light, 135 Medium, 53 Heavy.

C4iil: 7th Armored Bde 7; Assg: 7th Hus /4/7/,
6th RTR /4/7], 2nd RTR; Less its own 1 RTR and
8 Hus; Att: 4th RHA /7Spt/7f Trucks: 30
Medium, 15 Heavy.

C4i3i: Kings Dragoon Gds (R; 2Spt/2); 67th
Medium Arty; 16th Light AA; Trucks: 6 Light, 10
Medium, 3 Heavy.

C 3814: 4th South African Armored Car Bn
Trucks: 2 Light, 3 Medium, 1 Heavy. 4th Armored
Brigade (7; Independent Bde: no longer considered assignedassigned to the 7th Armored Div;
Less: its 6 RTR and 7 Hus; Assg: 8th Hus /7/7/;
3rd RTR /1/2); 5th RTR /3/2/; Att: 102nd AT
Regt; 2nd RHA /2Spt/2)); Trucks: 45 Medium, 15
Heavy.

C3823: 11 In Bde (4 In; Less: 4/7 Rajp; Assg: 2/5
Mahratta Light Inf [in it place]); Trucks: 5 Light,
20 Medium, 5 Heavy.

C3721: Central India Horse Regt (R; TOE
Strength of 3; 4 Jn)
Trucks: 3 Light, 3 Medium.¢3944: ist South

African Divison (Det: the three Inf Bdes and 4th
SA Field Arty); Trucks: 5 Light, 22 Medium, 6
Heavy.

C3614: 7th Support Group (7; Det: 11 Hus [R] and
4th RHA; Assg: Ist Light AA and 60th Field Arty)
Trucks: 30 Medium, 15 Heavy.

C3621: 4th In Division (Det: All three Inf Bdes and
the Recce Regt); 8th Field Arty; 65th AT Regt;
57th Light AA; Trucks: 5 Light, 20 Medium, 8
Heavy

C3532: 2nd South Africa Div (Det: 7 SA Armored
Car, 2nd SA Field Arty and 2nd SA AT Regt);
Trucks: 12 Light, 70 Medium, 14 Heavy.

C3521: lst Army Tank Bde
Trucks: 30 Medium, 17 Heavy.

C3530: 73rd AT Regt; 7th Medium Arty; 64th
Medium Arty; 68th Medium Arty; Trucks: 3
Light, 25 Medium, 5 Heavy.

C3419: 7th In Bde (4 In); Trucks: 5 Light, 22
Medium, 5 Heavy.

C3426: Sth In Bde (4 In; Less: 1 Royal Fusilier;
Assg: 1 Buffs fin its place/); 2nd South Africa AT
Regt (2 SA); Trucks: 5 Light, 20 Medium, 5
Heavy.

C3410: 11th Hus (7Spt/7); Trucks: 10 Medium, 3
Heavy.

C3414: HQ: 7th Armored Division
Trucks: 2 Light, 2 Medium

C3318: 2nd New Zealand Div
Trucks: 15 Light, 75 Medium, 21 Heavy.

C 3212: 22 Armored Bde (now Assg to the 7th Armored Div)
Trucks: 15 Medium, 10 Heavy.

C3111: 1st South African Bde (ISA)
Trucks: 5 Light, 20 Medium, 3 Heavy.

C 3015: 22 Gds Bde (1; Assg: 1st Tower Hamlet
Rifles Spt/2, 3rd Coldstream Gds; Att: 51st Field
Arty)

Trucks: 20 Medium, 10 Heavy.

C2712: 5th South Africa Bde (1SA)
Trucks: 5 Light, 20 Medium, 3 Heavy.

C 1014: 6th South African Armored Car Bn; 7th
SA Recce Bn (2 SA); 29th In Bde (5 In; Less: 6/13
FFR; Assg: Ist Royal Fusiliers 5/4 In; in its place#;
Att: 2 South African Field Arty Regt 2 SA)
Trucks: 7 Light, 25 Medium, 6 Heavy.

D 3714: 2nd South African Bde (J SA); 4th SA
Field Arty (7 SA)

Trucks: 5 Light, 22 Medium, 6 Heavy.

12001: 1st South African Road Construction Bn.
Trucks: 3 Light .

[#62_32]*[62.32]* Tanks

The units listed below have the following TOE of
tanks (Unit: Tanks).

iRTR G2nd Army, Bde 12): 4 Mk VI Light
4RTR Glnd Army, Bde 12): 10 Matildas

7 RTR Gland Army, Bde 12): 4 Matildas

8 RTR (ist Army, Tank Bde): 10 Valentines

42nd RTR (ist Army, Tank Bde): 3 Matilidas (the
following OpStage, the first of game-turn 58, the
unit receives 7 more TOE of Matildas if it does not
move. If it does, it receives them the second
OpStage of game-turn 58.)

8 Hussars (4/7): 10 Stuarts

3 RTR (4/7): 10 Stuarts

5 RTR (4/7): 10 Stuarts

7 Hussars (7/7): 4 Crusader I's, 3 A/13's, 4 A/10's
6 RTR (7/7): 10 Crusader I's

2 Hussars (22nd Armor Bde): 9 Crusader I's, 1
A/10

4 CLY (22nd Armor Bde): 9 Crusader I's, 1 A/10

In addition to the above tanks, the following tanks
(in terms of TOE Points) are considered to be
broken down in Repair Shops in Alexandria.

3x Crusader I; 15x Crusader II; 18x Stuart;
7x Matilda; 8 x Valentine.

Repair on these tanks may not start until the
scenario's second OpStage.

[#62_33]*[62.33]* Commonwealth North African Air Force

Planes: These may be distributed freely amongst
the available air facilities:

Total
Plane Available Refitted
Hurricane I's 82 64
Hurricane IIA's 66 60
Hurricane IIB's 42 36
Blenheim IVF's 24 16
Tomahawks 88 64
Beaufighters 22 16
Blenheim IV F's - 142 100
Wellington IC's 110 80
Bostons 20 16
Marylands 32 12

Pilots: 1 FOUR pilot, 5 THREE pilots, 15 TWO
pilots and 20 ONE pilots.

Air Facilities: 1 Flying Boat Basin anywhere on
map-section D or E, and Port Said (off-map).

No Flying Boat Alighting Areas.

Airfields at Maaten Baggush (D 3520), Fuka (D
3323), Amirya (E 3212), Kabrit (off-map) and
Tobruk (C 4807).

Air Landing Strips at any two hexes in the
Giarabub Oasis (C 1014) complex, Gerawla (D
3516), Sidi Haneish (D 3418), El Daba (D 3329),
Qotafiya (D 3227), Abu Seier and Fayid (off-map,
i.e., both have been reduced to the ability to perform maintenance ona single squadron).

SGSU's: As per Air Game rules.

31

32

[#62_34]*[62.34]* Commonwealth Trucks

The Commonwealth Player receives the following
Second/Third Line (Convoy) Trucks for distribution to any location on game map-sections C thru
E. However, no more than 10 Light, and/or 20
Medium and/or 10 Heavy Trucks may be placed
within five hexes of Tobruk.

Type Number
Light 150
Medium - 400
Heavy 150

The Commonwealth Player receives the following Trucks for distribution to any Air Facility (except that in Tobruk): 80 Medium and 20 Heavy.

[#62_35]*[62.35]* Commonwealth Supply

The Commonwealth Player possesses dumps at
the following locations containing the listed
amounts of Supplies:

Location Ammo Fuel Stores Water
Tobruk 800 1,500 550 —
Sidi Barrani 500 1,000 300 700
Giarabub Oasis 200 400 300 —
Mersa Matruh 1,000 2,000 400 800
Bir Khamsa (C 3029) 200 600 50 300

In addition, the Allied Player receives dumps at Oxford Circus (C 3532), Bir al Sheferzen (C 3419), Sidi
Suleiman (C 3721) and any two locations on game
map section D and any one location on game map
section C. Only four of these six dumps are active. A
minimum of 20% the total of each type of the
following total available Supplies must be placed in
each active dump: 400 Ammo, 400 Fuel, 200 Stores,
and 700 Water Points.

In additon, the Commonwealth Player receives
150 Ammo, 350 Fuel, 25 Stores, 50 Water Points at
each Airfield and 10 Ammo 150 Fuel, 10 Stores and
20 Water Points at each Air Landing Strip, Flying
Boat Basin, or Flying Boat Alighting Area. (This
does not include off-map facilities.)

[#62_36]*[62.36]* Malta
The following Planes are Available on Malta

Type Total Avail Total Refitted
Swordfish 3 3
Hurricane IIB's 28 24
Beaufighter IC's 8 6
Hurricane I 10 9
Hurricane ITA 12 11
Wellington IC 13 13

The Malta air facilities have an initial capacity of
14 Squadrons. There are 24 AA Points to place
where desired. Malta receives 1 Three Pilot, 4 Two
Pilots, 5 One Pilots.

[#62_37]*[62.37]* Commonwealth Fleet

The Commonwealth Player may place all his warship counters in Alexandria. In addition, note that
the Italian 10th Light Flotilla is active this scenario
(See <<30_4>>). However, the 10th Light may not raid
Alexandria until December.

[#62_38]*[62.38]* Reinforcements/Replacements

These are taken as normal, from the tracks and
production.

[#62_4]
=== AXIS FORCES

[#62_41]*[62.41]* Axis Forces Initial Deployment

(Hex: Units)

C 4014: 33rd Aufklarungs Bn (R, /5) Trucks: 2
Light, 5 Medium.

C 4015: 3rd Aufklarungs Bn (R; 5 Le)
Trucks: 2 Light, 5 Medium.

C 41082: 32 Ariete Div
Trucks: 20 Light, 42 Medium, 11 Heavy.
C 4216: 2ist Panzer Div (consists of: Sth Panzer

Regt 5 Le; 104th Rifle Regt 15; which consists of:
2nd Bn of the 104th Inf Regt (/5), 8th MG Inf Bn
(5 Le) and the 708th Heavy Weapons Coy; 39th
Panzerjager Bn AT; 5 Le; 155th Arty Regt; and
the 200th Pioneer Bn 5 13)

Trucks: 12 Light, 45 Medium, 12 Heavy.

C4306: 26th Arty Regt (12 Pav); 57th Arty Regt
(27 Bre)
Trucks: 4 Light, 4 Medium, 4 Heavy.

C 4406: RECAM (Italian Armored Car Regt)
Trucks: 5 Light, 15 Medium.

C 4407: 17th Pavia Div (Det: 26th Arty Regt)
Trucks: 8 Light, 30 Medium, 4 Heavy.

£3C 4408: 155th Rifle Regt (90 Le)

Trucks: 5 Light, 18 Medium, 5 Heavy.

C 4411: 361 Afrika Regt (90 Le)
Trucks: 5 Light, 6 Medium, 3 Heavy.

C 4507: XXI Corps Arty; 1/2AR; 2/2AR; 3/2AR;
4/2AR; Ist and 2nd Articelere Regts (all are Arty)
Trucks: 5 Light, 20 Medium, 6 Heavy.

C4606 and/or C4706: 102nd Trento Divi)
Trucks: 25 Light, 55 Medium, 15 Heavy.

C4608: 25 Bologna Div (I) Trucks: 8 Lights, 25
Medium, 7 Heavy.

C 4610: 90th Light Div (Det: 361 Afrika and 155
Regts, 3rd Bn of the 255 Regt and 3rd Bn of 347th
Regt; Less: 190th Arty, 580th Recce, and 190th
AT. Ergo, the counter consists of the HQ and the
613th Flak Bn); 200th Rifle Regt (75; consists of
the 2nd MG Bn 5 Le and the 15/200 Kradschutzen
Bn 15. Trucks: 5 Light, 21 Medium, 1 Heavy.

C 4613: 15th Panzer Div (Det: 33rd Recce; Less:
200th Rifle Regt, 104th Rifle Regt and 140th Arty
Regt; 33rd Arty Regt has a TOE Strength of 6).
Trucks: 15 Light, 50 Medium, 16 Heavy.

C 4804: 27th Brescia Div (Italian Inf; Det: 57th Arty). Trucks: 8 Light, 30 Medium, 4 Heavy.

Divided approximately equally amongst B 4432, C
4303 amd C 4102: 101st Trieste Div (I); Trucks: 20
Light, 50 Medium, 15 Heavy.

Anywhere within the triangle formed by C
3916—Sidi Omar (C 3618)—C 3922: 55th Savona
Div (Det: II/15 and [11/16 Inf Bns); 1/104 Rifle Bn
(15 Panzer); Trucks: 10 Light, 25 Medium, 5
Heavy.

Within one hex of C 4321: 2,5,6,12, and 13th Coys
of the Oasis Bn; III/255 Rifie Bn (90 Le); I11/347
Rifle Bn (90 Le); [V Genova MG Bn (Italian); 350
GaF Arty Regt; II/15 and IJ1/16 Inf Bns (55 Say);
Trucks: 5 Light, 7 Medium, 10 Heavy.

Attached to any Italian Inf Div(s): III(M) and
LII(M) tank Bns; Trucks (each tank battalion): 2
Light, 6 Medium.

[#62_42]*[62.42]* Axis Tanks
The Axis Player assigns German tank TOE
Strength Points as follows:

Unit Tanks

1/8 4 PzIl, 2PzilICE) 5 PzliIcH), 2
PzIV(D),

11/8 4 Pzil, 3PZIN(E) 5PziICH), 4
PzIV(E)

1/5 3 Pzil, 7 PziiicH), 1 Pziv(D)

Il/5 3 PzIl, 6 PzWI(H), 2 PzIV(B)

The Axis Player assigns Italian tank TOE Strength
Points as follows:

Unit Tanks
VIICM) 6 M13/40's
VIII(M) 6 M13/40's
IX(M) 6 M13/40's
LIi(M) 6 M13/40's
11) 5 M13/40's
K(L) 5 CV33's
11(L) 5 CV33's

(Note: Over 100 additional Light Tanks—usually
CV 33's and their ilk—were spread around other
Italian units, assigned to Recce units, Bersagliere
regiments, HQ's, etc. This information is "factored" into the strengths/TOE of those units.)

[#62_43]*[62.43]* Axis Air Strength
The Axis Player receives the following planes. The
Axis Player receives 23 SGSU's.

Aircraft Available Refitted
MC 200 35 20
Cr 42 23 8
G50 28 20
BR 20 29 15
Ju87D 9 5
SM79 21 10

The Axis Player receives the following Italian
Pilots:

Rating Number
Two 5
One 11

The Axis Player receives 33 German SGSU's and
the following planes:

Aircraft Available Refitted
Ju8ssD 83 45
Hell1 27 15
Ju87D 94 90
Bf109E 19 13
Bfl09F 40 27
BFi10C 23 13

The German Player receives the following pilots:

Rating Number
Six 1
Four 2
Three 3
Two 6
One 12

The Axis Player has Airfields at Benina
(A4829), Derna (B5925), Timimi (B5229), Gazala
(B4933), Gambut (C4414), Martuba (B5526),
Benghazi (A4827), Barce (B5504) and Maraua
(B5410). The Axis Player has 3 Air Landing Strips
anywhere on maps A thru C. The Axis Player has
one Flying Boat Basin anywhere on Map A or B.
In addition, he may base planes in Crete/Italy/
Sicily within the restrictions of Case <<43_1>>
[#62_44]*[62.44]* .Axis Trucks
The Axis Player receives the
Second/Third Line (In Convoy) Trucks:

following

Light Medium Heavy
Anywhere on game

maps A&B 45 120 20
Tripoli 20 35 10
Nofilia 20 25 10
Derna 15 20 10

The Axis Player receives 30 Light and 60 Medium
trucks for distribution among his air facilities.
[#62_45]*[62.45]* Axis Supply

The Axis Player possesses dumps at the following
locations containing the listed amounts of Supplies:

Ammo Fuel Stores Water
Tripoli 200 1,300 350 —
Nofilia 500 800 500 250
el Agheila 150 450 350 400
Benghazi 650 2,200 700 _
Mechili 500 1,700 150 600
Derna 300 2,500 100 300

In addition the Axis Player receives dumps at
Gazala (B4933) Rotunda Segnali (B 4432) and any
three locations on game map section B. Only three
of these five dumps may be active. A minimum of
20% of the following total available Supplies of
700 Ammo, 1,350 Fuel, 150 Stores and 400 Water
Points must be placed in each active dump.

In addition, the Axis Player receives 150 Ammo,
350 Fuel, 25 Stores and 50 Water Points at each
Airfield (excepting Tripoli/Tunesia).

[#62_46]*[62.46]* All Axis Coastal Shipping units are
available, and may be distributed among the parts
of Maps A, BandC.

[#62_47]*[62.47]* Axis Player must plan Replacements for
all November OpStages in advance of starting the
game. After that, he plans normally.

[#62_5]
=== CONSTRUCTION AT THE START
OF THE SCENARIO

There are no minefields. All ports are at full
(listed) Efficiency. All hexes adjacent to Bardia
contain Level 1 Fortifications. All hexes adjacent
to Tobruk contain Level 2 Fortifications.

The railroad extends past Mersa Matruh.and ends
in hex C 3430. From that point, the pipeline extends in a straight line as far as Birkhamsa (C
3029). All unfinished roads are built with the exception of the Siwa Track, which is completed to
only twenty hexes from Mersa Matruh (i.e., the
hex the 1st South African Road Construction Battalion occupies, D2001).

There is a Temporary Repair Facility in Tobruk.
The Commonwealth Player may also place an additional Temporary facility in any village/city he
wishes. As usual, Alexandria and Cairo contain
Major Repair facilities.

Temp
Repair
Facility

There is a Temporary Repair facility in Derna,
plus one in any other village or city. There is a Major Repair facility in Benghazi.

[#62_6]
=== AIR & LOGISTICS GAMES
ABSTRACTIONS

This case covers the adjustments needed in addito those given in Case <<59_6>> in order to play this
scenario without the Air and/or Logistics
Game(s).

[#62_61]*[62.61]* Air Abstracted

(Land & Logistics Games): None.

[#62_62]*[62.62]* Air & Logistics Abstracted

(Land Game Only):

A. The Players' ability to bring in Motorization
Points is equal to their respective ability's to bring
in Medium Truck Points (i.e., each Medium Truck
Point equals one Motorization Point).

B. Axis Initial Supply Status: Case <<62_45>> is replaced by the following:

Regular Each with
Location Supply Units Ammo Fuel
Tripoli (box) 2 20 60
Nofilia (A2703) 3 30 25
el Agheila (A1816) 1 30 50
Benghazi (A4827) 4 30 60
Mechili (B4921) 3 30 60
Derna (B5925) 4 15 60
Group 1* 3 30 50

*These, and in addition 2 dummy supply units, are
to be placed in any of the following locations in
any distribution at the Axis Player's choice:
Gazala (B4933), Rotunda Segnali (B4432) and any
location(s) on game map-section "B".

Cc. Commonwealth Initial Supply Status: Case
62.35 is replaced by the following:

Regular Each with

Location Supply Units Ammo +t
Tobruk (C4807) 4 40 40
Sidi Baranni (C4131) 3 30 50
Mersa Matruh:

(D3714) 5 40 30
Giarabub Oasis

(C1014) 1 40 50
Bar Khamsa (C3029) 1 30 60
Group 1* 4 20 15

*These, and in addition 2 dummy supply units,
may be distributed among the following locations
at the Commonwealth Player's choice with the
restriction that no more than one regular supply
unit may be placed in any hex: Oxford Circus
(C3532), Bir al Scheferzen (C3419), Sidi Suleiman
(C3721) and. any two. hexes (other than Mersa
Matruh) on game-map-section "D". In addition,
Cairo and Alexandria each contain two regular
py units, each with 40 Ammo and 60 Fuel Points.

[#62_63]*[62.63]* Logistics Abstracted

(Land & Air Games):

A. The Players' ability to bring in Motorization
Points is equal to their respective abilities to bring
in Medium plus Heavy Trucks (i.e., each Medium
and each Heavy Truck is equal to one Motorization Point).

B. Axis Initial Supplies: As in <<62_62>> "B" above
plus 1 regular supply unit at each Axis airfield (except those off-map) with 30 Ammo and 40 Fuel
Points.

C. Commonwealth Initial Supplies: As in <<62_62>>
““C”? above plus | regular supply unit at each airfield (except Kabrit) with 30 Ammo and 40 Fuel
Points and | regular supply unit at each remaining
air facility (except off-map) each with 5 Ammo
and 15 Fuel Points.

[#62_7]
=== INITIATIVE

Historically, the Commonwealth Player should
have the Initiative for the first OpStage. However,
the Players may roll in the normal manner to
determine who has initiative in that OpStageif they
prefer. In each OpStage after the first, the Players
roll the die as per normal procedure.

[#62_8]
=== VICTORY CONDITIONS

Players amass points for controlling geographical
locations. The Player with the most points subtracts the other player's points from his and then
determines the level of victory, if any.

The Players receive Victory Points for controlling
certain cities/villages. The number of points
depends on the location and the player controlling.
Control of a city/village means occupying that
city/village with a combat unit of any strength.
That unit must have sufficient supplies to exist for
one month and Ammo for one week (one round
each OpStage).

Points Points

for Axis for Cw
City/ Village Control Control
Tobruk 6 4
Bardia 2 3
Sollum 2 2
Halfaya Pass (both hexes) 1 1
Ft. Maddelenna 1 2
Sidi Biranni 3 0
Giarabub 1 1
Siwa 2 1
Ft. Capuzzo 1 1

Point Differential Level of Victory
10+ Strategic

6-9 Decisive

1-5 Tactical

0 Draw/Standoff

Players may wish to compare losses in men and
tanks (as well as air, although that is not that
revealing) to see how well they did, in comparison
to each other, in gaining or not gaining their objectives. Players may wish to subjectively raise or
lower their victory level as per this. However,
losses can be misleading, so this type of condition
is "officially" left out of the conditions here.

[#63_0]
== SCENARIO GROUP
FOUR: EL ALAMEIN
[#63_1]
=== GENERAL DESCRIPTION

There are two scenarios which can be played from
this scenario Group. The first is a short scenario in
which the Axis Player has one week (one gameTurn) to try to break through the Commonwealth
lines and reach Alexandria (a relatively impossible
task). The second scenario is one of survival: can
the Axis army survive the end of the campaign intact? For those familiar with El Alamein they will
realize that both scenarios are, militarily (and in
terms of game-playing) quite stultifying. They are
included for historical reference, mostly.
Playtesting proved them to be as equally dull as
their gaming predecessors. The first scenario has
the advantage of being remarkably short; the other
scenario is for those who like to retreat or chase
fleeing troops.

[#63_2]
=== SCENARIO LENGTH AND
DURATION

Both scenarios begin with the Ist OpStage of
Game-Turn 1OZ. "The Last Chance" Scenario
ends with the completion of the 3rd OpStage of
Game Turn 102 lst OpStage of Game-Turn 111.
“The Long Retreat" ends at the completion of the
December 3/IV, 1942 Game-Turn. "The Last
Chance'”' should take about ten hours to play, excluding set-up; "The Long Retreat" should take
from 50to 100 hours.

[#63_3]
=== COMMONWEALTH FORCES

[#63_31]*[63.31]* Commonwealth Land Forces
Deployment

Initial

(Hex: Units)

E 3101: 9th Aus Div (Det: 24 Aus Bde; Att: 40
RTR 23/8)

Trucks: 30 Light, 55 Medium, 15 Heavy.

E3001: 24th Aus Bde (9 Aus)

Trucks: 5 Light, 25 Medium, 6 Heavy.

D 3033: S5ist Inf Div (Att: 50 RTR 23/8).
Trucks: 40 Light, 70 Medium, 21 Heavy.

E 2901: nd New Zeland Div (2nd NZ Cav is now
TOE Strength of 5 Recce Points and 6 Stuart tank
Points; Less: 4 NZ Bde; Att: 9th Armored Bde 10;
Att: 3 Hus, 14th Sherwood Forresters 1)

Trucks: 30 Light, 90 Medium, 20 Heavy.

E 2801: Ist South African Div (Less: 50 SA Bde;
Assg: 3 SA Bde #SA; in its place#; ATt: 8th RTR
#1 Army#, 1st SA Field Arty #2 SA#, Die Middelandse MG Regt # SA#, and 2nd Botha #5/1SA )
Trucks: 35 Light, 85 Medium, 25 Heavy.

E 2701: 5 In Bde (4 Jn; Less: 1 Royal Fusilier and
4/6 Rajp Rifles; Assg: 1/4 Essex* and 3/10
Baluchies in their places); 6th Rajput Rifles MG
Bn; Ist Field Arty Regt (4 Zn); 149th AT Regt; 11th
Field Arty Regt; 32nd Field Arty Regt; 57th Light
AA Regt HQ: 4th In Div (Less: 11 In Bde, 31st
Field Arty, and Central In HOrse R; Det: 5th and
7th In Bdes and ist Field Arty). Trucks: 10 Light,
25 Medium, 10 Heavy.

33

34

E 2601: 7th In Bde (4 In; Less: 4/11 Sikh; Assg:
1/2 Gurkha Rifles in its place) and 161st In Motor
Bde (consists of: Ist Argyll & Sutherland 16/17,
1/1 Punjab Regt, 4/7 Rajputanis /1/4 In).
Trucks: 5 Light, 25 Medium, 5 Heavy.

2501: 50th Inf Div (Less: 150 Bde, 2nd Chesire MG
Bn and 72 Field Arty; Assg: Greek Bde and 111th
Field Arty Regt in place of the Inf Bde and Arty
Regt respectively; Att: 154th Field Arty Regt,
102nd AT Regt 2Spt/2 and 34th Light AA Regt).
Trucks: 35 Light, 65 Medium, 21 Heavy.

E 2302: 7th Armored Div (Consists of: 4th Armored Bde #consists of 4/8 Hus**, Royal Scots
Grays (8/10) and IKRRC (7 Spt/7); 22nd Armored Bde consists of 1 RTR (7/7), 5 RTR 3/2), 4
CLY (22 Amr Bde), and 1 Rifle Bde (2/2); 11th
Hus r; 7; TOE Strength of 83 RHA Which now is
considered a regular artillery unit; Possesses 6
TOE Strength Points of 25Ibrs; 4th Field Arty
Regt; 97th Field Arty Regt20/10 In; 65th AT Regt;
15th Light AA Regt; AH: 2nd Derby Yeomanry R,
8; Strength of 6; 44th Recce Regt 44. Trucks: 75
Medium, 40 Heavy.

E 3005: lst Armored Div (Consists of: 2 Armored
Bde Less: Ist RflBde, 7th Motor Bde 7; Which
consists of: 2nd Rifle Bde (7Spt/7), 7th Rifle Bde
(23/8) and 2nd KRRC (/Spt/J), 2nd RHA #Spt/2,
4th RHA /7Spt/7, 11th RHA self-propelled
counter, 78th Field Arty, 76 AT RegtSp?t/J, 1st
Royal Northumberland Fusiliers MG Bn, 42nd
Light AA, and 12 Lancers R; /Spt/J; Att: An ad
hoc Bde—level formation known as "Hammerforce'; consisting of: 4/6 SA Armored Car
Regt*** with a TOE Strength of 7, 146th Field Arty, 73rd AT Regt and 56th Light AA Regt).
Trucks: 10 Light, 90 Medium, 30 Heavy.

E 3007: 8th Armored Div (Det: 40 RTR and 50
RTR of the 23rd Armored Bde, 2nd DerYoe R;
Less: 24th Armored Bde, 7th Rifle Bde of the 23rd
Armored Bde); 121st Field Arty. Trucks: 5
Medium.

E 2805: 10th Armored Div (consists of: 8 Amr Bde
10; Less: SctsGray; Assg: 3rd RTR (//2; in its
place) and Ist Buffs (1), 24th Armored Bde [8],
133rd Inf. Bde [44]. lst Royal Dragoons R, 1
RHA, 104 RHA, 98sth Field Arty, Sth RHA selfpropelled counter, 84th AT, and 53rd Light AA).
Trucks: 75 Medium, 40 Heavy.

E 2904: lst Army Tank Bde (Det: 8 RTR) Trucks:
5 Medium.

E 2401: 44th Inf Div (Det: 44th Recce; Less:
133Inf Bde; Att: 53rd Field Arty). Trucks: 20
Light, 55 Medium, 6 Heavy.

Within one hex of E 2403: Ist Free French Bde
Trucks: 10 Light, 35 Medium, 5 Heavy.

2nd Free French Bde. Trucks: 5 Light, 12
Medium, 1 Heavy.

Within two hexes of el Alamein

(E 3002): 14th Light AA; 16th Light AA; 27th
Light AA; 88th Heavy AA; 94th Heavy AA.
Trucks: 5 Medium.

2ist In Bde (0 In; consists of:: 1/6 Rajput Rifles
11/4 In, 3/7
Rajputama Regt 61 In Mtr Bde and 2/8 Gurkha
Rifles); 7th Medium Arty Regt; 64th Medium Arty; 69th Medium Arty
Trucks: 10 Light, 25 Medium, 7 Heavy.
*This is a British unit whose counter bears the Indian units' coloration.

**Formation created by combining the 4th and 8th
Hussars. Use the counter for the 8th Hus (7/7).
The unit's max TOE Strength is still 10.
***Formation created by combining the 4th and
6th SA Armored Car Battalions. Use either
counter. The unit's max TOE Strength is now 8.
Certain of the above units may have their equipment and TOE upgraded, using the rules sections
for such as references.

A. Each non-motorized infantry battalion (CPA

of 10) may add 1 TOE of 6-pounder AT guns; and

B .Each motorized battalion of infantry (10+
CPA) may add 2 TOE of 6-pdr AT guns.

C . 40% (rounded up) of all AT units may replace
their 2-pdr AT guns with 6-pdr AT guns.

D . Armored car (not armored recce) units may be
upgraded as per the rules for such. (It is not
necessary to use Replacement points; simply
upgrade them as if they had used Replacement
Points)

E . Any artillery units with 18-pounders or 18/25
pounders may replace them with 25 pounders.

[#63_32]*[63.32]* Commonwealth Tank Battalion
Composition

The following tank battalions are listed as to their

assigned parent formatin(s) for this scenario and

their starting compositions, in TOE Strength

Points, if they differ from their listing on the OA

Sheet. Parent

Tank Battalion _Formation(s) Composition

40 RTR 23/8 8 Valentines

46 RTR 23/8 10 Valentines

50 RTR 23/8 9 Valentines

8 RTR 1 Army* 10 Valentines

3rd Hussars -t 2 Grants, 2 Shermans, 3 Crusader
T's

Ryl Wi Yeomanry 9/-t 3 Grants, 2 Shermans, 3 Crusader
I's

Warwick Yeo 3 Grants, 3 Shermans, 3 Crusader
Il's

9th Aus Div Cav 9 Aust 3 Crusader II's, 1
Stuart 6 ID Code
oe 1 1' >

Royal Scots Greys 4/7 4 Stuarts, 3 Grants

4/8 Hussars 4/7 9 Stuarts

1RTR 22/7 4 Stuarts, 5 Grants

5RTR 22/7 4 Crusader II's,
5 Grants

4CLY 22/7 6 Crusader II's,
2 Grants

Queens Bays 7 Shermans,
3 Crusader II's

9th Lancers 2/1 6 Shermans,
4 Crusader II's

10th Hussars 2/1 5 Shermans,
5 Crusader II's

7th Motor Bde HQ 1 Churchill

3 RTR 8/10 3 Crusader III's,
2-Shermans,
3 Grants

Nottingham Yeo 8/10 3 Crusader III's,
2 Shermans,
4 Grants

Staffordshire Yeo 8/10 3 Crusader III's,
2 Shermans,
4 Grants

41 RTR 24/10 3 Crusader III's,
6 Shermans

45 RTR 24/10 3 Crusader III's,
6 Shermans

47 RTR 24/10 3 Crusader III's,
7 Shermans

42 RTR 1 Army 10 Scorpions

44 RTR 1 Army 10 Scorpions

*Starts attached to the Ist SA Div.

{Starts attached to the 2nd NZ Division.

£This armored unit is a tank battalion for these
scenarios.

[#63_33]*[63.33]* Commonwealth Air Strength

Planes (Type
and #'s Available)
Location SGSU's(Type and #'s Available

Burg el 3. Spitfire VB (18); Hurricane

Arab HA (12);
(E 3109) Tomahawks (6); Marylands
(4); Baltimores (4)
Wadi 1 Marylands (12)
Natrun
(E 2418)

Deversoir * Mitchell II (39)

Amiriya 28 Boston III (48); Baltimore II
Air (24); Baltimore III (24);
Com- Tomahawk (16); Kittyhawk
plex (see 1 (56); Kittyhawk II (91);
Air Kittyhawk II (39); HurFacilities ricane IIB (48); Hurricane
below) IiC (64); Hurricane IID

(32); Hurricane IIE (16);
Spitfire VB(48)

Idku 2 Beaufighter IC (16); Beau(E 3817) fighter VIF (16)

Abu Seier * Wellington IC (32)

Jebel 2 Wellington IC (32)

Hamzi

(E 2024) ;
Kabrit * Wellington IC (16); Well
ington
II (16)

Degheila 2. Albacores (24)

(E 3512)
Ismailia * Hudsons (32); Bombays (22)

*=S$GSU's not needed; off-map base.
All Commonwealth Planes are Refitted!

Pilots Available

Rating Number Available
Four 1

Three 5

Two 22

One 31

Air Facilities

The Commonwealth Player places six Airfields
within one hex of Amiriya (The Amiriya complex).
He has an Airfield at Burg el Arab (E 3109), Alexandria, and Cairo. He has a Landing Strip at Wadi
Natrun (E 2418). The Commonwealth Player may
also place 1 additional Airfield and 3 Landing
Strips, 1 Flying Boat Basin and 1 Flying Boat
Alighting Area anywhere on Map E, but not
within five hexes of an enemy unit, or in the
Qatarra Depression. The Commonwealth Player's
seven off-map facilities are all undamaged.

[#63_34]*[63.34]* Commonwealth Trucks
Second-Third Line Trucks (In Convoy):

Anywhere on gamemapsD&E: 200 Light, 725

Medium, 225 Heavy

The Commonwealth Player receives 100 Medium
and 60 Heavy trucks for distribution among his
Air Facilities.

[#63_35]*[63.35]* Commonwealth Supply

The Commonwealth Player receives 10 Supply
Dumps plus 3 Dummies, for a total of 13 Dumps.
As many as five of these dumps may be placed
within one hex of the Front Line (i.e., any hex east
of and adjacent to an Axis unit.) One dump each
must be placed at el Alamein, E2805, and E2403.
The remaining dumps may be placed anywhere on
Map B£, but not within one hex of the front.

Front Line Dumps receive (amongst them) 2500
Ammo points, 2000 Fuel Points, 1500 Stores, and
1500 Water Points. The other dumps split (in any

way the Player wishes) the following: 1000 Ammo
Points, 3000 Fuel Points, 500 Stores, 2000 Water
Points.

Remember, there is unlimited supply available in
Alexandria and Cairo. All Trucks not carrying
men may be loaded with supplies as the Player
wishes. The Commonwealth has no temporary
repair facility. Alexandria and Cairo are Major
Repair Facilities.

[#63_36]*[63.36]* Commonwealth Fleet

The Commonwealth Player receives the following
warship counters in Alexandria: 2 Heavy Cruisers,
3 Light Cruisers, 4 Destroyers.

[#63_37]*[63.37]* Malta

All Air Facilities are operating at full capacity.
The following planes are available in Malta:

Type Number Refitted
Wellington V 5 5
Baltimore I 4 4
Baltimore I 3 3
Beaufighter IC 2, = §
Beaufighter VIF 8 6
Spitfire VB 54-33
Spitfire VC 18 10
Aturricane LIC 8 8
Albacore 3 3
Swordfish 3 3

48 AA Points are Available for placement as
desired, The Following Pilots are available:

Rating Number
Three 1
Two 5
One 5

[#63_38]*[63.38]* Reinforcements and Replacements

All Reinforcements are taken as per the Reinforcement Schedules. Ail Replacements are taken normally, except that all available points are reduced
to 10%, rounded up, of their listed maximum.
However, the Infantry and Truck Production
Tables' output are unaffected. In any case, no
Replacement points may arrive before the first
OpStage of Game-Turn 105, and these may be
planned before the scenarios starts. Replacements
for the 106th Game-Turn may also be planned at
the start of the scenario. There are no
Replacements or Reinforcements for the "Last
Chance”' scenario.

[#63_4]
=== AXIS FORCES
[#63_41]*[63.41]* Axis Land Forces Initial Deployment
(Hex: Units)

13328: 90th Light Div (Det; 580 Aufklarungs Bn
{R]); Trucks: 10 Light, 40 Medium, 7 Heavy

13132: 15th Panzer Div (Less: 200th and 104th
Regts; Det: 33 Recce; Assg: 2 MG Bn /5 Le);
Trucks: 15 Light, 40 Medium, 10 Heavy.

13032: 164th Light Div; Trucks: 5 Light, 45
Medium, 5 Heavy.

12931: 3 Aufklarungs Bn (R; 2/); Trucks: 2 Light.

12831: 21st Panzer Div (Less: 2nd MG Bn; Assg:
200th Rifle Regt /15]; which begins the scenario
detached); Trucks: 7 Light, 20 Medium, 10 Heavy.

12733: Ramcke Bde; Trucks: None.

D2630: 104th Rifle Regt (Now assigned to the 21
Panzer); Trucks: 5 Light, 25 Medium.

1D2532: 33 Aufklarungs Bn (R; 15).
12431: 580th Aufklarungs Bn (R; 90 Le); Trucks:
5 Light.

D 3327: 136th GGFF Div (1) Trucks: 25 Light, 15
Medium.

D 3326: 101st Trieste Div (I; Det: 21 Arty Regt;
ATT:III(M) Trucks: 5 Light, 55 Medium, 5
Heavy.

D 3325: 16th Pistoia Div (1) TRucks: 30 Light, 30
Medium.

D 3232; 133rd Littorio Div (T; Det: 12th Bersaglieri Regt; Less: X(M) and XII(M) tank Bns
and V and VI Arty Bns self-propelled: Assg: in
their places, respectively [V(M) and LI(M) tank
Bns and DLIV and DLVI Arty Bns self-propelled)
Trucks: 25 Light, 25 Medium, 6 Heavy.

E 3133: 12th Bersaglieri Regt (I; Littorio( Trucks:
6 Light, 20 Medium.

D 2933: 102nd Trento Div (I; Det: 7th Berg Regt)
Trucks: 68 Medium, 7 Heavy.

D 2932: 7th Bersaglieri Regt (102 Trn) Trucks: 20
Medium.

D 2833; 25th Bologna Div (1); 21st Arty Regt (10/
Tst) Trucks: 12 Light, 60 Medium, 10 Heavy.

D 2732: 27th Brescia Div (1) Trucks: 10 Light, 65
Medium, 7 Heavy.

D 2632: 132 Ariete Div (T; Less: VII(M) tank Bn;
Assg: LII(M) tank Bn in its place, V and VI Arty
Bns self-propelled; Littorio; Att: XIII(M) tank
Bn; The 132 Arty Regt now contains 3 TOE
Strength Points of 105/28 guns and 2 TOE
Strength Points of 90mm Flak guns heavy AA
Trucks: 25 Light, 45 Medium, 10 Heavy.

D 2533: 185th Folgore Div (I) Trucks: 30 Light, 30
Medium.

D 2432: 17th Pavia Div (I) Trucks: 10 Light, 65
Medium, 7 Heavy.

Anywhere on Map D: Italian XXIV Cp Arty; XXVI Cp Arty; 1/2AR Arty Bn; 2/2AR Arty Bn;
3/2AR Arty Bn; 4/2 AR Arty Bn; RECAM (R);
III/133 Fanterie Inf Bn I(L) and II(L) tank Bns.
German: Sonderverband 288 Regt (I); 707th and
708th Heavy Weapons Coys; 13th Coy of the
Bandenburg Regt (I).

Anywhere on Map A thru D: Any four Oasis Coys
and the 778th Naval Engineers. All remaining
unassigned German independent (i.e., no parent
unit) artillery and anti-aircraft units. This includes
the 1st and 2nd African Arty HQ's and the 155th
and Arko 104 Arty Hq's and their subsidiary
units.

Modifications to units strength: A// Axis Infantrytype units are reduced to 2/3 (round fractions up)
of their maximum TOE Strength.

[#63_42]*[63.42]* Tank Deployment

The following are exceptions to the OA Chart

Listing.
Unit Strength
I/5 Panzer 2 Pzil: 4 PzIITH; 1 PzItlE; 4

PzIIIJ Specials

2PzII; 2PzZNIE; 4PzIIIH; 4PzlIIlJ
Specials; 1 PzIVE

1PzIl; 4 PzIIIH; 5 Pziily
Specials; 3 PzIVF? Specials
1PzIl, 3PzUIH, 1Pzl116,5PzillJSpecial, 1PzIV6,3PzIvF*

II/5 Panzer

1/8 Panzer

II/8 Panzer

LIT/(M) 6M/13/40's
VUI/M 6 M/13/40's
I/(L) 6 L6's
II/(L) 4L6's

Broken down in Tobruk's Repair Facility: 3
PzHIH's; 1 PzIVD.

[#63_43]*[63.43]* Axis Air Strength

German Planes

The following planes may be located at any air
facility in Africa. Planes not refitted may not be
readied until the second OpStage of the scenario
(they are not ready for the first OpStage).

35
Type of Plane Total Avail Refitted
Ju87D 70 44
Me Bfl09F 83 40
Me Bf109G 90 50
Me Bf109E 16 6
Me Bf110C 16 10
SGSU's available: 21
Pilots Available:
Rating Available
Four 4
Three 4
Two 11
One 16

The Axis Player has available in Crete the following planes: 75 Ju88's (60 refitted) and 15 Hel11's
(10 refitted). No SGSU's or pilots are needed.

Italian Planes

Type of Plane TotalA vail TotalReady
Cant.Z.1007 14 14
Fiat CR42 125 75
Fiat G.50 12 0
Macchi C.200 58 40
Macchi C.202 139 / 84
S.M.79 34 24
SGSU's Available: 27

Pilots Available:

Rating Available

Four 1

Three 3

Two 20

One 18

Air Facilities

The Axis Player has nine Airfields, eight one Flying Boat Basin and One Flying Boat Alighting
Area. He may place these wherever he wishes, on
Maps A-D.

[#63_44]*[63.44]* Axis Trucks

Second-Third Line Trucks (In Convoy):

May be placed anywhere on game maps A thru D:
115 Light, 350 Medium, 75 Heavy.

The Axis Player receives 50 Light and 100 Medium
trucks for distribution among his Air Facilities.

[#63_45]*[63.45]* Axis Supply

The Axis Player receives ten Supply Dumps, three
of which are Dummies. At least five of those
dumps must be placed on Game-Maps A, B or C.
The other five may be placed on game-map D (or
A-C, if desired). In addition, the Axis Plyaer
receives supplies at several cities/villages, as listed
below. He may use Supply Dumps for those
villages listed, in addition to those given to him.

Location Ammo Fuel Stores Water
Map D Dumps* 2700 4000 1500 800
Other Dumps* 500 500 500 500
Ghazal(D3328) 200 500 0 500
Mersa Matruh 500 1500 250 500
Sidi Barrani 200 500 0 500
Bardia 300 1000 250 0
Tobruk 800 3000 250 0
Derna 200 500 0 500
Benghazi 300 1000 250 0
Marble Arch 200 500 250 500

*No one dump may contain more than 33%
of the total supplies of each type listed.

Each Airfield has 150 Ammo points, 350 Fuel
points, 25 Stores and 50 Water except
Tripoli/Tunisia.

36

Each Strip, Flying Boat Basin/Alighting Area has
20 Ammo points, 25 Fuel points, 10 Stores and 10
Water Points.

Trucks may be assigned to the dumps, cities as
needed fromthe 2nd-3rd Line Trucks available.

The Axis has a Major Repair Facility in Tobruk,
and Temporary Repair Facilities in Bardia and
Mersa Matruh.

Axis Coastal Shipping (all units/tonnage) is
available. Ships may be placed at any port between
Tobruk and Tripoli.

[#63_46]*[63.46]* Axis Mediterranean Air Force
Deployment |

The Axis Player may transfer 10% of his available
force to Italy or Sicily but no more. He may not
have more than 10% of his air power in Italy or
Sicily. Strategic air attacks against Malta may be
made only in the Long Retreat scenario (see
44.41).

[#63_47]*[63.47]* Replacements and Reinforcements

For the "Last Chance" Scenario, ignore all Reinforcements and Replacements.

For the "Long Retreat" scenario, Reinforcements
as normal. As for Replacements, Axis Player must
reduce all his Points Available to 5% (rounded
down) of what is listed in the Axis Replacement
Pool. Moreover, any Replacement Points sent
must be sent to Tripoli and must stay there, unless
the following occurs: If the Axis Player still holds
Tobruk, Bardia, or Mersa Matruh by the third
OpStage of Game-Turn 105, then 25% of Replacement Points in Tripoli may be released the following OpStage. After that, 25% of all available
Replacement Points (by type, and rounded up)
may be released in the first OpStage of Game-Turn
108.

This rule takes into effect the Allied Landings
(feared and actual) to the West, and the historical
fact that almost all manpower at this time was being diverted to Tunisia.

[#63_48]*[63.48]* Upgraded Axis Equipment

A. All eligible Axis armored car and armored
recce units may be upgraded as per rules for such.
It is not necessary to use Replacement Points;
simply upgrade the units as if they had used
Replacement Points.

B. Any two of the four following Italian infantry
divisions may have their assigned artillery units'
OA Sheet listing of two or three 75mm heavy antiair TOE Strength Points replaced with two 90mm
heavy anti-air TOE Strength Points: 16 Pistoia,
17i Pavia, 25 Bologna and 27 Brescia.

C. The following German anti-tank units have
their weaponry upgraded replacing their OA Sheet
listing: The 605th SP of the 21st Panzer has 6 TOE
Strength Points of Marder SP anti-tank guns. The
3.7mm anti-tank guns in the 15th and 21st Panzers
are replaced by the same number of 5cm guns. The
Scm guns in the 15th and 21st Panzers and 90th
Light are replaced by the same number of <<7_62>>
Pak(R) guns.

D. Any four eligible Italian brigade-level HQ's
are ad hoc anti-tank batteries each with 4 TOE
Strength Points of Italian AT guns. Any two eligible German brigade-level HQ's are ad hoc antitank batteries, each with 4 TOE Strength Points of
2.8cm anti-tank guns.

E. All Italian artillery units originally assigned to
a division (i.e., as listed in the OA Chart) have
their 75/18 Gun-Howitzer TOE Strength Points
replaced by an equal number of 75/27 guns. The
two self-propelled artillery units in the Littorio
and the two in the Ariete each possess 4 TOE
Strength Points of Semovente 75/18 SP guns.

F. The following German artillery units are
upgraded: The III/220 and III/220 artillery battalions of the 164th Division each consist of 3 TOE
Strength Points of 1S5cmK18 guns and 3 TOE
Strength Points of 15cm sFH18 guns (replacing
their OA Sheet artillery). The 149, 526 and 533
Coastal Defense artillery battalions replace their
artillery with, respectively, 3 TOE Strength Points
of 15cm sIG33 guns, 3 TOE Strength Points of
17cm K18 guns and 3 TOE Strength Points of
21cm Mrs18 guns.

[#63_5]
=== SPECIAL RULES

The following rules may not be used:
A. 10th Italian Light Flotilla
B. Raid on Rommel

[#63_6]
=== INITATIVE

Historically, the Germans had the initiative during
the first OpStage of this scenario. However, the
Players may at their discretion roll the die to determine who has the iniative on the first OpStage. (If
the Commonwealth Player gains the initiative for
the fist week, it will be even more depressing than
usual for the Axis Player, of course.)

[#63_7]
=== CONSTRUCTION
[#63_71]*[63.71]* All unfinished Roads have been built.

[#63_72]*[63.72]* The entire unfinished railroad complex
has been built. However, the RR in the three hexes
immediately west of el Alamein are destroyed.

[#63_73]*[63.73]* The only pipeline available is that in
railroad hexes. The Axis Player may draw water
through it from Tobruk while the Commonwealth
Player may draw water through it from Alexandria.

[#63_74]*[63.74]* All ports are at full (listed) Efficiency except Benghazi, at Efficiency Level One, and
Tobruk at Efficiency Level Five.

[#63_75]*[63.75]* Level One Fortifications are placed in the
four hexes adjacent to Tobruk. In addition, the
Axis Player may place a total of three Level One
Fortifications among the four hexes adjacent to
Bardia.

[#63_76]*[63.76]* Commonwealth Player places minefields
in the following hexes: D3033, and on map-section
E3101, 2901, 2801, 2701, 2702, 2601, 2501, 2401, 2302
and other five hexes (on map-section E). Of the fifteen, ten are Real and five are Dummy; the
distribution is at the Commonwealth Player's
choice. All start the scenario at unknown status
(i.e., face-up).

[#63_77]*[63.77]* The Axis Player places minefields in the
following hexes of map-section D: 3233, 3133,
3032, 2933, 2833, 2733, 2632, 2633, 2533, 2429,
2433, 2831, 2832, and 2731. Of the fourteen,
eleven are Real and three are Dummy; the distribution is at the Axis Player's choice. In addition the
Axis Player may place up to five Real and two
Dummy minefields in any eligible hexes within
three hexes of Tobruk and a maximum of two Real
and two Dummy minefields in any eligible hexes
on game map-section A thru C that are not within
five hexes of Tobruk. ("Eligible" refers to the
ability of the Players' to construct a minefield in
that hex under the normal game restrictions.) All
start the scenario at unknown status (i.e., faceup).

[#63_8]
=== AIR & LOGISTICS GAMES
ABSTRACTIONS

This case covers the adiustments needed in addition to those given in Case <<59_6>> in order to play
these scenarios without the Air and/or Logistics
Game(s).

[#63_31]*[63.31]* Air Abstracted (Land & Logistics Games):
The Commonwealth initial supplies are reduced as
follows: The Front Line Dumps now total 2250

Ammo, 1750 Fuel, 1500 Stores and 1250 Water
Points. The other dumps now total 500 Ammo,
2000 Fuel, 400 Stores and 1600 Water Points (see
Case <<63_35>>).

[#63_82]*[63.82]* Air & Logistics Abstracted

(Land Game only)

A. The Players' ability to bring in Motorization
Points is equal to their respective abilities to bring
in Medium Trucks (i.e., each Medium Truck
equals one Motorization Point).

B. Axis Initial Supply Status: Case <<63_45>> is replaced by the following:

Regular

Supply Each with
Location Units Ammo Fuel
“Other Dumps"
Supply units* 14 40 20
‘Map D Dumps'”'
Supply unitst 2 40 25
Ghaza (D 3328) 1 40 60
Mersa Matruh
(D 3714) 1 40 60
Sidi Baranni
(C 4131) 1 40 60
Bardia (C 4321) 2 20 60
Tobruk (C 4807) 3 40 60
Derna (B 5925) 1 40 60
Benghazi (A 4827) 2 25 60
Marble Arch
(A 2109) 1 40 60

*These plus 2 dummy supply units may be placed
in any hexes on maps A thru D at the Axis Player's
discretion except that no more than a total of four
supply units (i.e., regular plus dummy) may be
placed on maps A through C.

+These, and in addition | dummy supply unit, may
be placed in any hexes on Maps A through C.

C. Commonwealth Initial Supply Status: Case
63.35 is replaced by the following: The Commonwealth Player receives 13 regular supply units,
each with 40 Ammo and 20 Fuel Points, to be placed at his Front Line in any fashion with the restriction that at least one regular supply unit must be
placed in each of the following hexes: el Alamein
(E 3002), E 2805 and E 2403. The Front Line is
defined as hexes E 3002, E 2805, E 2403 and any
hex that is east of and adjacent to an Axis unit. In
addition, the Commonwealth Player receives 2
regular supply units, each with 40 Ammo and 60
Fuel Points, which may be placed anywhere on
map E except that neither may be placed within
two hexes of the Front Line (this includes Front
Line hexes not occupied by supply units).

[#63_83]*[63.83]* Logistics Abstracted

(Land & Air Games):

A. The Players' ability to bring in motorization
points is equal to their respective abilities to bring
in Medium plus Heavy Trucks (i.e., each Medium
and each Heavy Truck is equal to one. Motorization Point).

B. Axis Initial Supplies: As in <<63_72>> "B" above
plus 2 depot supply units, each with 180 Fuel and
40 Ammo Points, one at Mersa Matruh and one at
Tobruk. In addition, a total of 9 regular supply
dumps, each with 30 Ammo and 50 Fuel Points, to
be distributed among and placed on any Axis air
facilities other than Mersa Matruh and Tobruk.

C. Commonwealth Initial Supplies: As in <<63_72>>
“C”' above plus a total of 2 depots, each with 40
Ammo and 180 Fuel Points, one each at any Commonwealth air facility not within three hexes of a
Front Line hex.

[#63_9]
=== VICTORY CONDITIONS

[#63_91]*[63.91]* "The Last Chance" Scenario
A. The Axis Player wins a Strategic Victory if he

can occupy at least one hex of Alexandria with at
least a Brigade-equivalent unit. Supply doesn't
matter.

B. Failing the above, the Axis Player totals the
number of TOE Strength Points (any type) on
Game-Map E, the Commonwealth Player totals
those TOE points he has on Game-Map D (exclusive of Layforce and SAS units). The Player
with the most TOE points (in comparison to the
other) is the winner of a tactical victory.

[#63_92]*[63.92]* ‘“The Long Retreat" Scenario

The name of the game is survival here. How good
is the Axis Player at delaying, at giving territory
grudgingly. He cannot win in a military sense (the
Allies are landing, Africa is lost—at least in
retrospect). However, the better he fights,the
more attention the Allies will have to pay to
Africa. Here the Axis Player is playing against actual history. Can he do better than Rommel on this
retreat? Rommel didn't do badly; see if you can
best his record (if you don't fall asleep first). In
essence, the Axis Player gains points for occupying
certain locations. Occupying means that all combat units in that City/Village must have at least
one Game-Turn's worth of Stores, be able to fire
all weapons twice, and have enough fuel for all
units to move 20 CP's,

Location

Mersa Matruh
Bardia
Tobruk

Derna
Benghazi

El Agheila
Marble Arch

Axis Pts for Occupying

Pe WN MN Wee

If the Axis Player can get 10 or more points he wins
a Strategic Victory.

If he can get 4-9 points, he wins a Substantive Victory.

If he gets 1-3 points, he wins a Marginal Victory.

If he get no points, the Commonwealth Player
wins.

[#64_0]
== SCENARIO GROUP
FIVE: THE CAMPAIGN
FOR NORTH AFRICA

[#64_1]
=== INTRODUCTION

If you have gotten this far you will by now have
surmised that the full campaign game of CNA
is,far and away, the most ambitious undertaking a
gamer could ever want to get involved with. The
campaign game requires not so much a commitment in time (which is always relative), but more
so a commitment to planning and foresight. A
campaign game will need at least ten players,
perhaps more. Ideally, each land division should
have a commander, plus an Air Commander anda
Logistics Commander. On top of this should be
one Player as Supreme Commander. This means a
lot of players, and, again, this is the ideal situation. The fewest number of players would be three
to a side. Lastly, it would be hard to underestimate the amount of paperwork and planning
that are involved in a campaign game. Keeping on
top of the situation is half the battle . . . and more
than half the fun. And speaking of fun, the campaign game can be a lot of fun. If you are interested in a challenge, interested in wrestling with
the problems of organizing and running a campaign, and if you simply want to experience the
complexities of. modern warfare at all levels, you
will get much satisfaction from CNA.

[#64_2]
=== SCENARIO LENGTH

There are two campaign game scenarios in CNA.
The first covers the entire war in Northeast Africa
and begins in the third week of September, 1940
(.e., the Italian Offensive, lst OpStage of GameTurn 1). The "shorter" campaign begins with the
arrival of General Erwin Rommel and the
Deutsches Afrika Korps during the fourth week of
March, 194] (i.e., the Desert Fox, 3rd OpStage of
Game-Turn 26). Both campaign games end with
the completion of the third OpStage of GameTurn 111.

[#64_3]
=== INITIAL DEPLOYMENTS

If the entire campaign is being played, the Players
use the information provided in Section <<60_0>> for
the initial placement and distribution of their land,
sea, and air forces, supplies and construction. If
the Players are starting the campaign with the arrival of Rommel, the information in Section <<61_0>>
is used.

[#64_4]
=== INITIATIVE

The Players determine Initiative using the information provided in Section <<60_0>> or <<61_0>> depending
upon where they are starting their campaign. Iniative is determined normally once the restrictions
in the appropriate section expire.

[#64_5]
=== SPECIAL RULES/ADJUSTMENTS

[#64_51]*[64.51]* There are no restrictions on normal game
actions (i.e., Raids on Rommel, the Commonwealth Fleet, etc. may be performed as per the
appropriate rules).

[#64_52]*[64.52]* The Axis Player's Malta Air Availability
is determined using the appropriate campaign
game row on the Axis Strategic Airforce Commitment Chart.

[#64_53]*[64.53]* If the shorter campaign game is being
played the Axis Replacement Pool must be adjusted as follows:

A. German Production Chart: No change.

B. Axis Truck Production Chart: The total trucks
the Axis Player may bring in are reduced to 800
Light, 2400 Medium and 500 Heavy.

C. Italian Production Chart: One-half of all
replacement points (rounding fractions up) that
could be planned up thru (i.e., including) GameTurn 24 are no longer available with the following
exception: the Axis Player still has 60 CV L.3 &
CV 33/35 tank replacement points available.

[#64_54]*[64.54]* If the shorter campaign game is being
played the Commonwealth Production System
must be adjusted as follows:

A. Commonwealth Truck Production Table: No
change.

B. Commonwealth Infantry Proudction Table:
No change.

C. Commonwealth Production Chart: The
replacement points listed below are reduced to (not
by) those numbers, all other replacement points
are unaffected:

Item Number
Armored Car/Armored Recce 75
Light Anti-air 70
25-pounder artillery 230
2-pounder AT guns 50
Mk VI Light tanks 5
A9 crusiers 3
AJ0 crusiers

A13 crusiers

Matildas 20

[#64_6]
=== ADR & LOGISTICS GAMES'
ABSTRACTIONS

Why anyone would play a campaign game without
the Air and/or Logistics Game(s) is beyond me.
However, the Players should pick their start point
(Italian Offensive or Desert Fox) and use the rules
in the appropriate section(s)  <<32_0>>, <<47_0>>, <<58_0>>) and
the abstracted set-up for that scenario group and
the replacement point adjustments in Case <<64_5>>.

[#64_7]
=== VICTORY CONDITIONS

It would be hard to imagine anything more exasperating than playing a game for five years, getting to the end, and finding out that you have lost
by one point or two hexes, or something of that ilk
Victory conditions for a game of this size and
scope are almost meaningless: survival itself is a
victory. However, you have to have some sort of
objective, and the Designer has to make some sort
of decision. Our decision here is to use Victory
Conditions that compare to what actually happened, not what each side needed to do. The reason
for this is that the Axis situation was a foregone
conclusion by 1942, what with the pending Allied
invasion of Africa from the West. Thus, the Axis
had to take Alexandria (and the Delta) or else be
caught in the desert between two armies. And
Alexandria is thus the Axis objective, historically.
As for gaming, it becomes a matter of points, or
who can hold onto what.

[#64_71]*[64.71]* If the Axis Player occupies all hexes of
Alexandria and Cairo for one full Game-Turn,
and sucn occupying units can trace a line of supply
(i.e., convoy route) back to a Supply Dump which
in turn can be supplied from Tobruk or Tripoli in
any way, and that line is 90 movement points by
truck or less, the Axis wins the game—regardless
of the turn or date. Failing that, we count points,
as below.

[#64_72]*[64.72]* Starting with the first OpStage of GameTurn 35, if there are no Axis Combat units that can
trace a line of supply of 60 Movement Points
(Truck) to a Supply Dump and thence to Tobruk
or Tripoli as per case <<64_71>>, game-map, the Commonwealth wins the game automatically. This
does not include air or coastal shipping units.

[#64_73]*[64.73]* Failing the above two cases, players
receive points for doing (or not doing) certain
things. The first of these points are Geographical
Occupation Points. The Player occupying the
given cities/villages gains the points listed. Occupation for these purposes means having a combat unit of at least 1 TOE Strength in the hex. That
combat unit, at the end of the game, must have
enough Stores and Water for one Week, and
enough Fuel and Ammunition to fire its weapons
three times and move 20 CP's. Any units failing
these "tests" do not occupy for victory conditons.

City/Village Axis V.P.'s C'wlth V.P.'s
Mersa.Matruh 100 10
Sidi Barrani 50 10
Siwa 20 10
Jalo 10° 20
Giarabub 15 10
Bardia 100 50
Sollum 25 - 10
Tobruk 200 100
Derna 25 50
Benghazi 75 100

[#64_74]*[64.74]* The next series of points are replacement
Victory Points. Each Player receives one point for
each unused Replacement Point allotted to him in
his Production Charts, not including planes
and/or Trucks and, for the Commonwealth
Player only, Infantry. Thus, if the Commonwealth Player had a total of 35 Crusader I

3/7

38

Tank Replacement Points available for the game,
but he uses only 18, he gains 17 points.

[#64_75]*[64.75]* The final type of Victory Points apply
solely to the Commonwealth Player: Withdrawal
Points. (Unit, not Drug). These apply to battalions
withdrawn from the game, other than those
Withdrawn via The Reinforcement Track. These
are voluntary withdrawals, not mandatory
withdrawals. They are earned as follows:

A. For every combat battalion (not company) or
battalion-equivalent of infantry, armour, artillery or anti-tank guns (not AA) that is at
least 75% TOE Strength that is Withdrawn
from the game the Player receives 4 point for
each week that unit is gone, to a maximum of
three points per unit. To be Withdrawn a unit
must start the Stage in Alexandria or Cairo.

B. Every time that a battalion withdrawn under
A. above is returned to the game,the Commonwealth Player loses two points. A unit
voluntarily Withdrawn and then returned to
the game may not be Withdrawn until six
months from the date of return. (This may
not be entirely accurate, but it will stop
players from doing the One-Point Two Step,
shuffling a single unit in and out to get one
point).

[#64_76]*[64.76]* The levels of Victory are as follows.
Again, anyone who actually finishes this game can
consider himself a winner (much as the soldier who
fights two-three years does when he survives.)
Questions about the balance of the campaign
scenario received before 1981 will be considered
with the seriousness which they deserve. The
following schedule is consulted after both sides
total their points, comparing the totals as a ratio of
most to least.

Ratio Result
Even (1 to 1) Draw (My God, what a waste of
time!)
Better than 1-1,
up to1%-1 Marginal Victory
Better than 1%-1
up to2%2-1 Decisive Victory
Better than
2-1 A Smashing Victory

[#65_0]
== INCONCLUSION

We have attempted, in Campaign for North
Africa, to provide the hobby with the most accurate and most stimulating simulation yet undertaken. Very little is abstracted (mostly the naval
game), and the Players are given as much to do as
we considered humanly feasible. CNA is a difficult
and complex game; it is not for the novice, to be
sure. It is our (both designer and developer) opinion that we have, in the main, succeeded in our
endeavor. CNA was playtested for nearly two
years an extensive list of "veteran" testers, most
of whom were chosen for their insight and gaming
acumen. Many researchers were used—including
the inimitable Richard Garcyznski—more than on
any other project. The amount of work put into
the game was enormous; the amount of information available is almost mind-boggling. We hope
that the amount of fun is just as great.

DESIGNER'S NOTES
In Brief

A game such as CNA certainly could use — nay,
demands — extensive background information as
to where and why. Unfortunately, to do this subject justice would require a veritable book. And
you already have enough to read with this game.
I'll simply try to cover a few subjects generally.

The general research was done mostly by me; the
specifics were done by a host of others. The task
was divided into areas — Italian OB, German air,
logistics, etc. It was done over a period of two
years, and provided many hours of confusion and
some laughter. (We felt that being provided with a
complete OB for German bakery companies was a
bit much...although the temptation to use them
was great.)

The scale of the game was decided by its scope and
size — and the map configuration. The sources are
listed in the bibliography, and suffice to say the
game-maps are borrowed from several conficting
sources. Often the designer had to make difficult
decisions as to which tracks existed and which
simply filled in the blank spaces on an Italian map.
The tracks proved most difficult — I don't think
there are two maps that agree — but defining
things-such as sand-gravel, rough, and salt marsh
was equally taxing. The map of the game is as accurate as we could get it on the scale presented.
The greatest liberties, or shall we say, abstractions,
are with ridges, slopes, and escarpments. Again
the effort was, at the scale given, to present effect
rather than strict geographical accuracy.

The system itself was developed rather quickly.
The first problem tackled was the theory and application of mobile desert warfare. Several approaches were tried, most were unsatisfactory.
What I wanted was a system that would enable
units to move as far as the player wanted them to,
but within the limits of fuel and fatigue. And I
found the germ for such an idea in an unlikely
place: Mick Uhl's Gettysburg '77. From that game
came the general idea for the Continual Movement
System. Actually, the system did not take full effect until I came up with the idea for Cohesion
Points — and, of course, a workable set of
numbers for such. Both of these provided the
game the one thing I wanted to prove — that
mobile units were more powerful not because they
had more "combat points" but because they were
more mobile.

After the movement system fell into place it took
several weeks to come up with a combat system.
The idea was to provide a tactical feel with an
operational game. (The system for CNA is
remarkably similar to Frank Chadwick's Operation: Crusader.) Of course, the backbone for the
combat system is the OB work — and especially
the values given to each unit. Lord knows where
some of these came from, but I do know that I
have a mountain of yellow sheets in my basement
with a lot of mathematical computations. Tanks
and guns were done strictly on relative strengths —
using the Italians as a base for the lowest. The
same with infantry. I'm sure questions will arise as
to why some infantry is 2/2, some 1/2, some 1/1,
etc. A lot has to do with weaponry, some with
background and training, and some is fairly subjective. The strengths themselves are not the balancing factor, the Morale Level is. And Morale Level
was based on performance, training and general
esprit de corps. (The morale system was taken
from my own Veracruz, another unusual source.)

Combat, however, is not what this game is about.
Logistics is the subject, and trucks are the thesis.
And from the very beginning that is what I concentrated on. Most of the design work went into mak
ing the logistics system work. Hundreds of computations on breakdown rates, fuel consumption,
tonnage capacities, etc., were done using available
statistics and charts. One of the hardest jobs was
the Replacement Charts. It is one thing to determine how much a man weighs, and thus a battalion; it is another to determine how much ship
space he takes up. The same can be said for guns
and other equipment. We had a fairly accurate picture of Axis shipping tonnage, but there was little
information available as to wkat was shipped on
what and how. The real problem was not coming
up with all this information, it was integrating it so
that everything meshed. Luckily, the logistics
system proved to be relatively trouble-free.

Not so for the air system, That was hell. We were
working with individual planes — a conceit of the
designer, admittedly — and thus the combat
system had to be tactical. However, this was an
operational game and I had no desire to get involved in an African version of Air War. It took a long
evening of fiddling with a calculator to come up
with the complicated series of computations that
we used to arrive at our air strengths. This was
possible only when I came up with a combat
system. If you ask me, the whole thing is a bit
much — but then you could say that of the entire
game. I would have scrapped the whole shebang
had not the playtesters enjoyed it so much. As it is,
the air system is a game within itself, with all its
logistical problems and planning. Oh, yes — having the air commander roll for refit for each plane
individually is a good way of passing time while
the land game is on.

The main question with CNA is, “Why?” The
answer, superficially, is because that's what the
feedback said you wanted. But that's a cop-out. I
did CNA as a definitive and informationally overpowering simulation because I wanted to see how
far I could take simulation gaming and still survive. CNA is virtually unplayable — as a game. It
is, for the most part, a source of information. Yet,
if it is approached from the point of view of an experience, a lesson in history, then CNA can provide remarkable insights into a fascinating campaign. One does not “play” CNA, one immerses
himself in it. Some of you will, no doubt, drown;
most will just tread water. But a few of you will
find the swim refreshing.

A word as to the accuracy of all this information.
Let's face it, I am not the definitive scholar on
North Africa — it's not even my main area of interest. There are bound to be some mistakes, some
all-too-subjective assumptions, and some pure
baloney. But all of it is based on hard research. As
I have said elsewhere, if you have better information, use it. (And let me know, too....) This is a
system for your enjoyment; it is not an ironclad
contract between gamer and designer. One thing I
do know, from all the research we did, this —
CNA —is the first commerically available source
to publish a complete battalion-level Order of Battle for all sides at all times during Africa. Just
think how many games you can devise from that
alone!

Some brief words of thanks to those involved.
CNA took a long time (as those who ordered the
game two years ago will no doubt attest to). Along
the way many people gave freely (and not-sofreely) of their time and energy. To Redmond
Simonsen goes the credit for coming up with the
idea for this game — and he knows how I feel
about that brainstorm. To our fearless leader, Jim
Dunnigan, a devotee of the Torquemada School of
Persuasion, goes some dubious thanks for assigning me to this project. An honest vote of thanks to
my very good friend Howard Barasch, for spending many hours with his voluminous notes on the
campaign. And to my two OB researchers —

David Ryan and, especially, the incredible Richard
Garzcynski, I can only say that they saved my proverbial rear-end more than once. But most of all, I
would like to thank the game's developer, Marty
Goldberger. Marty stuck with this project through
worse than I had to do. I may have designed it, but
he had to make heads or tails of it...and he was the
one who took all the grief when we screwed up. A
remarkably dogged individual, Marty G. provided
a sense of structure and parameter that was sorely
needed. And finally, much gratitude goes to my
wife Karen, who can now stop saying, “Africa?
Are you still working on that damn game!”

BIBLIOGRAPHY FOR CNA
A Brief Note

The books and references listed here are not an extensive or complete list of all works consulted.
Some works were too general to be of use, and
while they provided interesting background you
could not say they were used as a source. Other
works are not listed simply because, in the long
delay in putting the game together, we just lost
track of the exact title (the book having been
returned to its owner, etc.) Other works, such as
the Commonwealth histories — including New
Zealand, Australian, Indian, and South African
— were definitely used but can usually be found in
any standard work on the subject. The same can be
said for the famous Playfair volumes, the fourbook work on the British effort in the Mediterranean. Playfair is an incredible work, but it is flawed. It is difficult to read, having been written by
committee, as it were, and there is much information that is missing, as well as some that is wrong.
Altogether, however, it is still the single most important source.

Finally, it must be noted that our two main OB
researchers, the estimable Messrs. Garzcynski and
Ryan, made use of a large number of unit
histories, military studies, microfilms, and private
letters and correspondence.

Italian Tanks and Fighting Vehicles of
World War 2, by Ralph Riccio. Oxon, England,
1977. Pique Publications.

Regia Aeronautica, by Christopher Shores.
Michigan, 1976. Squadron/Signal Publications.

World War II Airplanes, Volume I, by Enzo
Angelucci and Paolo Matricardi. New York,
1978. Rand McNally & Co.

Combat Aircraft of the World, by John Taylor.
New York, 1969. Putnam's Sons, Inc.

Italian Armor in the Desert, Jon Jeffrey Kelger.
(Source unknown; this was a photocopy of an
article.)

Italian Armor at El Alamein, Jon Jeffrey Kegler.
(See previous entry.)

A Short History of the Italian Medium Tank,
Bruno Benvenuti. (Another photocopied magazine article.)

The Vuinerability of the Manned Airborne

Weapon System, Peter Bogart. International
Defense Review, 1977.

AFY-G2, Baron Publishing Company,
California. (A series of magazines, from which
several articles were consulted.)

Uniforms, Organization, and History of the
Afrika Korps, by Roger J. Bender and Richard
D. Law. Bender Publishing, 1973.

The Sidi-Rezeg Battles, 1941, by Agar-Hamilton
and Turner, Capetown, Oxford University
Press, 1957.

Armour Camouflage and Markings: North
Africa, 1940-1943, Ontario, Canada. Published
privately, 1971.

Panzer Battles, by Maj, Gen. von Mellenthin.
Harman, University of Oklahoma, 1955.

I Paracadutisti, by Nino Arena. S.T.E.M.,
Mucchi, 1972.

Stato Maggiore Dell'Escercito Ufficio Storio
(The Italian Official Histories). Eight volumes.

Desert Tracks, Baron Publishing Co., 1978.

Verbande und Truppen der deutsches Wehrmacht und Waffen SS in Zweiten Weltkrieg, by
Georg Tessin. (The standard German Order of
Battle work.) Frankfurt, date unknown.

German Tanks of World War IT, by F. M. von
Senger undEtterlin. New York, Galahad Books,
1969.

Artillery of the Second World War, by Emil
Franzi. Tucson, Arizona, Whitehouse Press,
1978.

Orders of Battle, by H. Joslin, HMSO, London
(British Orders of Battle — the standard
reference.)

Commonwealth Armoured Formations of World
War IT, by Duncan Crow. Profile Publications,
England.

Map Sources
Sonderangabe I, 1941. 1:400,000 Cyrenaika
Sonderangabe II, 1941. 1:2,000,000 Libyen

Geographical Section, General Staff No 4076.
1:100,000

World (Africa). 1:1,000,000 Series 1301, Edition
6AMS, US Army Map Service

